### ISSUE TITLE
tour: For Continued

### ISSUE THREAD

**Issue by ZimCodes** [golang/tour#1001]
Context: https://tour.golang.org/flowcontrol/2

Salutations, citizen! 

The shorthand For Loop example returns *1024* instead of *1000*.

**Comment by ALTree** [comment]
Hi, 

the loop's body doubles `sum` until it's over 1024, starting from 1; so `sum`  goes 1, 2, 4, ... 512, 1024, and then the loop exists. Since this is working as intended, I'm closing here.
