### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by ctmnz** [golang/tour#1005]
Context: https://tour.golang.org/basics/3

Change the title above to describe your issue and add your feedback here, including code if necessary:

The result of the script execution: 
./prog.go:9:14: cannot refer to unexported name math.pi
./prog.go:9:14: undefined: math.pi

Go build failed.

**Comment by AlaaRdwan94** [comment]
in the Go playground description they said "to fix the error, rename math.pi to math.Pi and try it again." 

> Context: https://tour.golang.org/basics/3
> 
> Change the title above to describe your issue and add your feedback here, including code if necessary:
> 
> The result of the script execution:
> ./prog.go:9:14: cannot refer to unexported name math.pi
> ./prog.go:9:14: undefined: math.pi
> 
> Go build failed.

**Comment by ctmnz** [comment]
It is an intentional error (as explained by AlaaRdwan94). 

Apologies. I didn't read the description to the end.
