### ISSUE TITLE
tour: Random int only ever produces the number 1 even after reset

### ISSUE THREAD

**Issue by coolk13** [golang/tour#1010]
Context: https://tour.golang.org/basics/1

No changes, just reset and rerun always shows value of 1.

**Comment by EvanPeterson1324** [comment]
The reason for this is in the note at the bottom of the example. This is not an issue and should be closed.

**Comment by ALTree** [comment]
Yes:

> Note: The environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. 

Please remember to always read the text beside the code example before opening an issue. Thanks.
