### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by JamesLeeYJ** [golang/tour#1018]
Context: https://tour.golang.org/welcome/2

When click the link of [Japanese — 日本語], the below message is shown on the target page
[Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.]

**Comment by ALTree** [comment]
Thanks for reporting this. I've opened #1039 to track this. Japanese is already fixed btw. Closing here.
