### ISSUE TITLE
tour: append should mention that it might resize to larger than required

### ISSUE THREAD

**Issue by arungpro** [golang/tour#102]
Context: http://127.0.0.1:3999/moretypes/15

This has wrong capacity shown on array, Please check the attachment.
<img width="1274" alt="screen shot 2016-11-02 at 12 34 02 pm" src="https://cloud.githubusercontent.com/assets/20789273/19919419/b2e8510a-a0f8-11e6-9767-3c72dc3b1330.png">

**Comment by robphoenix** [comment]
The capacity here isn't wrong, but it is different. It is different to the output on the go tour site, but it is the same as the output I get when running the tour locally.
There is an explanation as to why here: https://stackoverflow.com/questions/38573983/capacity-of-slices-in-go
From that post:
>how much the capacity of the slice is expanded by isn't mentioned in the specification and different versions of Go (or different implementations, or the same version on different architectures, etc.) can expand the slice by different amounts.

**Comment by robphoenix** [comment]
May be worth adding a note to the go tour regarding this?

Otherwise this can probably be closed @adg @rakyll @broady @arungpro

**Comment by robphoenix** [comment]
https://go-review.googlesource.com/c/44951/ @adg

**Comment by adg** [comment]
I think this is too fussy of a detail to mention in the tour itself.
