### ISSUE TITLE
tour: Update Korean go-tour url to a new project

### ISSUE THREAD

**Issue by umi0410** [golang/tour#1027]
As you can see in #709 , the original Korean go tour project is very old and no one manages it so no updates have been available so long.

I followed the instruction in ([TRANSLATE.md](https://github.com/golang/tour/blob/master/TRANSLATE)).

- created a project to manage Korean go tour ([golang-ko/tour](https://github.com/golang-ko/tour))
- deployed an appenigne on [https://go-tour-ko.appspot.com](https://go-tour-ko.appspot.com)
- emailed golang-nuts@googlegroups.com

But I wasn't able to get any reply from golang-nuts@googlegroups.com so I open a new issue to ask if you can update Korea go tour url.

Can you update Korean go tour url?

**Comment by umi0410** [comment]
Hi, @ALTree It's great to finish translating go tour to Korean.

Our team did our best and the results are as the following.

Go Tour: https://go-tour-ko.appspot.com/list

Translation repository: https://github.com/golang-ko/tour

**Comment by ALTree** [comment]
Thanks. I've opened a change here: https://go-review.googlesource.com/c/tour/+/253337. It'll need to be reviewed and approved but at least another committer, so we'll have to wait for their review.

**Comment by umi0410** [comment]
I saw the commit. Thank you.

**Comment by umi0410** [comment]
@ALTree Despite of the new commit(https://github.com/golang/tour/commit/6f9d4ff994b136951d420708cd231da267653086), we cannot access the new korean go tour(https://go-tour-ko.appspot.com) through tour.golang.org. It's because tour.golang.org still redirects us to the old korean go tour(https://go-tour-kr.appspot.com).

Is it because https://github.com/golang/tour/commit/6f9d4ff994b136951d420708cd231da267653086 hasn't been deployed yet? If the answer were yes, when can the new korean go tour be on the list on tour.golang.org?

**Comment by ALTree** [comment]
@umi0410 I requested a re-deployment, should be good now.
