### ISSUE TITLE
tour: can't load korean page

### ISSUE THREAD

**Issue by agatory** [golang/tour#1032]
한글 페이지에서 고 버전이 낮아 실행할수 없다고 나옵니다 어떻게 해야 하나요?

https://go-tour-kr.appspot.com/

Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

**Comment by ALTree** [comment]
Indeed, see #1026.

**Comment by agatory** [comment]
> Indeed, see #1026.

Thank you very much...
