### ISSUE TITLE
tour: Feature Deprecations

### ISSUE THREAD

**Issue by KseniyaBialkevich** [golang/tour#1036]
Context: https://go-tour-ru-ru.appspot.com/

**Hello!
Could you restore the tour in Russian, because it is not available at the moment.

App Engine feature deprecations.
The standalone legacy SDK and appcfg tooling.
Shutdown Date: August 30, 2020

Go 1.9 is no longer available.
To continue running your apps, migrate them to the Go 1.11 standard runtime or newer runtimes.**

https://tour.golang.org/welcome/2 
Russian - Русский
https://go-tour-ru-ru.appspot.com/
https://cloud.google.com/appengine/docs/deprecations

**Comment by ALTree** [comment]
Indeed, see #1022.
