### ISSUE TITLE
When choosing a language for studying the tour, it gives an error

### ISSUE THREAD

**Issue by Shved-cmd** [golang/tour#1043]
Context: https://tour.golang.org/welcome/2

When choosing a language for studying the tour, it gives an error. For example, when I select Russian it gives the following error: Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information. When will this be fixed?

**Comment by ALTree** [comment]
Thanks for the report; but we don't control the tour translations. We only link to them.

> When will this be fixed?

When the owner of the russian translation re-deploys the tour. See #1039.

Closing here.
