### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by wednesAI** [golang/tour#1046]
Context: https://tour.golang.org/flowcontrol/2

code:

package main

import "fmt"

func main() {
	sum := 1
	for ; sum < 1000; {
		sum += sum
	}
	fmt.Println(sum)
}

why the result is 1024,firstly sum is 1,one loop sum become to 2,because condition is sum less than 1000 ,so at least 1000 loop ,and finally sum must to larger than 1024

**Comment by ALTree** [comment]
It goes 1, 2, 4, 8, .. 512, 1024, and then it stops because it's > 1000.
