### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by wednesAI** [golang/tour#1047]
Context: https://tour.golang.org/flowcontrol/7
code as following:
package main

import (
	"fmt"
	"math"
)

func pow(x, n, lim float64) float64 {
	if v := math.Pow(x, n); v < lim {
		return v
	} else {
		fmt.Printf("%g >= %g\n", v, lim)
	}
	// can't use v here, though
	return lim
}

func main() {
	fmt.Println(
		pow(3, 2, 10),
		pow(3, 3, 20),
	)
}
the offical answer is 27 >= 20 then 9 20
but i think is 9 then 27 >= 20 then 20 becase pow(3, 2, 10) return 9 ;pow(3, 3, 20) return 20 but the flow control statement if-else has to print "27>=20" before return 20

**Comment by ALTree** [comment]
That code is actually *executed*. It's not just an "official answer"; it's literally what the code prints. It can't be "wrong", the answer is what the code prints. If you don't understand why it does print that, re-read the code carefully to understand it.
