### ISSUE TITLE
tour: SPANISH -> Al acceder al Tour de Go seleccionando la opción Español, dice que no esta disponible.

### ISSUE THREAD

**Issue by Anderson-LT** [golang/tour#1049]
Context: https://tour.golang.org/welcome/2

This text is in Spanish.

Cuando trato de acceder al Tour seleccionando la opción Español, me redirección a a una pagina indicando que no esta disponible, y un enlace a Google Cloud, ahí aparece una lista en la que dice que el servicio dejo de funcionar el 20 de Junio del 2020.

Disculpas por escribirlo en Español, no se Inglés.

**Comment by ALTree** [comment]
Yep. See #1039.
