### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by imperialgg** [golang/tour#105]
Context: https://tour.golang.org/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary

When I click Run button multiple times, I see the same number.

My favorite number is 1

if I change rand.Intn(10) to other number, then it get a new number but click Run again will show that number only

**Comment by Numbluk** [comment]
Similar to https://github.com/golang/tour/issues/110 and this issue is addressed there.

**Comment by robphoenix** [comment]
Can be closed @adg @rakyll @broady @imperialgg
