### ISSUE TITLE
tour: fatal error: all goroutines are asleep - deadlock

### ISSUE THREAD

**Issue by nguyenhoai1890** [golang/tour#1052]
Context: https://tour.golang.org/concurrency/3

Not modify the code, when running it shows error:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.main()
	/tmp/sandbox915641541/prog.go:9 +0xfd
```

**Comment by ALTree** [comment]
Press the `Reset` button on the right to reset the example. Changes are cached so it's possible that someone else changed the code and you're seeing their changes.

After pressing Reset the code works for me.
