### ISSUE TITLE
tour: [Plz support traditional Chinese version]

### ISSUE THREAD

**Issue by NetLabFox** [golang/tour#1055]
Why can't the traditional Chinese version be used, but the simplified Chinese version can?
Context: https://tour.golang.org/welcome/2

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ALTree** [comment]
The tour translation are not controlled or deployed by the Go Project, we only link to them

Several translations went offline when appspot deprecated Go1.9. The maintainers of the Simplified Chinese translation re-deployed it and it went back online, while the maintainers of the Traditional Chinese translation still have to do it. 

Please see #1039. Closing here.
