### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by LeHNam** [golang/tour#1057]
Context: https://tour.golang.org/moretypes/3

Change the title above to describe your issue and add your feedback here, including code if necessary

![image](https://user-images.githubusercontent.com/38838516/96247490-66f8d900-0fd4-11eb-80ed-cfb8062324fb.png)

**Comment by ALTree** [comment]
Hi,

`v.X = 4` sets the 1st field to 4, so that result is expected.
