### ISSUE TITLE
tour: [Example Fibbonacci Closure Function Throws an exception]

### ISSUE THREAD

**Issue by keegan2149** [golang/tour#1059]
Context: https://tour.golang.org/moretypes/26

    ./prog.go:8:1: missing return at end of function

    Go build failed.

**Comment by ALTree** [comment]
That page is an exercise. The text says:

> Exercise: Fibonacci closure
>
> Implement a fibonacci function

So it's not surprising that the code won't compile until you've filled in the implementation.
