### ISSUE TITLE
Bad portuguese translation

### ISSUE THREAD

**Issue by PixetBits** [golang/tour#1060]
Context: https://tour.golang.org/welcome/2

There are many verbal and pronominal incongruities and some poorly translated texts that suggest other explanations or even do not explain. I would like to offer to improve the translation, if possible

**Comment by ALTree** [comment]
Hi, 

we don't control or deploy the translations, we only like to them. The repo of the portuguese one is here, I believe: https://github.com/dgv/go-tour-br. You'll have to contribute there. Closing here.
