### ISSUE TITLE
tour: Table of Contents scrolling with mouse wheel doesn't work in Firefox

### ISSUE THREAD

**Issue by btfenyes** [golang/tour#1063]
Context: https://tour.golang.org/list

With Firefox, when the Table of Contents doesn't fit the screen, scrolling with the mouse wheel only works if the cursor is directly above the scrollbar (or if the scrollbar is dragged). Seems to work properly with Chromium-based browsers (tried with Edge).

**Comment by ALTree** [comment]
Thanks for reporting this, see #805. Closing as a dup of that one.
