### ISSUE TITLE
tour: german tour is broken

### ISSUE THREAD

**Issue by Atomic0ne** [golang/tour#107]
Context: https://tour.golang.org/welcome/2

The german tour at 
https://go-tour-de.appspot.com/welcome/1
does not work for me.
The "runtime" always returns: "Error communicating with remote server. Program exited.".

**Comment by gregorjs** [comment]
+1

**Comment by domschrei** [comment]
+1

**Comment by fr3dm4n** [comment]
+1

**Comment by yokalona** [comment]
This issue sometimes appear on any pages, but it disappears soon or later.

**Comment by ALTree** [comment]
Works now... so I assumed the de tour maintainer fixed it. Closing here.
