### ISSUE TITLE
Tour of go on spanish is not working

### ISSUE THREAD

**Issue by agusmiani** [golang/tour#1080]
On the screen of [https://tour.golang.org/welcome/2](https://tour.golang.org/welcome/2) and select Spanish language throws this error:

![image](https://user-images.githubusercontent.com/24942640/99476952-4ce24b80-2930-11eb-93e8-51ad6e34cdec.png)
redirecting to: https://gotour-es.appspot.com/

**Comment by ALTree** [comment]
Thank you for reporting this. Please see #1039. Closing here.
