### ISSUE TITLE
compute called with incorrect parameter name 'fn' instead of 'fnfun'

### ISSUE THREAD

**Issue by tatehanawalt** [golang/tour#1081]
Context: https://tour.golang.org/moretypes/24

The code example shows 
```
func compute(fnfun func(float64, float64) float64) float64 {
	return fn(3, 4)
}
```

Notice ```return fn(3,4)```

this should be ```return fnfun(3,4)``` 

Alternatively you could change the function parameter as follows:

```
func compute(fn func(float64, float64) float64) float64 {
   ...
```

**Comment by ALTree** [comment]
Someone changed the code and the tour caches local changes. Click the `Reset` button to restore the code to its original form.

**Comment by ALTree** [comment]
> The code example shows

It doesn't for me.

Someone changed the code in that browser, and the tour caches local changes. Press the `Reset` button on the right to restore the code to its original form.
