### ISSUE TITLE
tour: missing return at end of function

### ISSUE THREAD

**Issue by gerardoangeles** [golang/tour#1082]
Context: https://tour.golang.org/moretypes/26

./prog.go:8:1: missing return at end of function

Go build failed.

package main

import "fmt"

// fibonacci is a function that returns
// a function that returns an int.
func fibonacci() func() int {
}

func main() {
	f := fibonacci()
	for i := 0; i < 10; i++ {
		fmt.Println(f())
	}
}

**Comment by ALTree** [comment]
It's an exercise (see text on the left). It won't compile until you implement the function.
