### ISSUE TITLE
tour: If interface is not nil why the value printed is <nil> for the interface

### ISSUE THREAD

**Issue by niarora** [golang/tour#1085]
Context: https://tour.golang.org/methods/12

A note in the tour says:
> Note that an interface value that holds a nil concrete value is itself non-nil.

If I run the slightly modified code from the tour:
```
var i I

var t *T
i = t
println(i == nil)
describe(i)
...
```
The output is:
```
false
(<nil>, *main.T)
...
```

As per the note, `i` is not `false`. Why is the value for `i`  printed as `<nil>` if it's not `nil`?

Thanks.

**Comment by ALTree** [comment]
Hi,

that's because `fmt.Printf` looks inside the interface. From the `https://golang.org/pkg/fmt/#hdr-Printing`:

> Regardless of the verb, if an operand is an interface value, the internal concrete value is used, not the interface itself.

So above you're testing the interface itself, but `Printf` is looking inside and printing the `Value` part.
