### ISSUE TITLE
tour: linked screencast uses old GOPATH instead of module system

### ISSUE THREAD

**Issue by jcnauta** [golang/tour#1089]
Context: https://tour.golang.org/concurrency/11

The screencast on youtube that is recommended at the end of the Tour of Go uses the old `GOPATH` to set up a project. This workflow has been superseded by modules as the preferred alternative (available since v1.11, with release notes for v1.14 stating "we encourage all users to migrate to Go modules for dependency management.")

I suggest either modifying the video to point this out or removing it (and the link to it) altogether.

**Comment by ALTree** [comment]
Yeah, that's the issue with documentation in video format, it's basically impossible to update... you can only re-shoot the video. IMO we should just remove the link to the video, and leave the link to the How to Write Go Code document.
