### ISSUE TITLE
tour: [Time and date are displayed incorrectly]

### ISSUE THREAD

**Issue by feoktist** [golang/tour#109]
Context: https://tour.golang.org/welcome/4

Hi, guys.
Today is Nov 16, 2016. I checked the code in the Go playground, pushed "Run" button and got this - 

Welcome to the playground!
The time is 2009-11-10 23:00:00 +0000 UTC

Why the date and time is displayed incorreclty?

thanks.
alex

**Comment by Numbluk** [comment]
To the left of the sandbox it gives you the answer:

> In the playground the time begins at 2009-11-10 23:00:00 UTC... This makes it easier to cache programs by giving them deterministic output.

**Comment by ALTree** [comment]
Explained on the left. Working as intended. Closing.
