### ISSUE TITLE
tour: rand.Intn(10) always returns 1 for me

### ISSUE THREAD

**Issue by kandoiNikhil** [golang/tour#110]
Context: http://127.0.0.1:3999/basics/1

Not sure, what exaclty is wrong, but it displays the same number every time I run the snipped

**Comment by Numbluk** [comment]
This is addressed to the left of the sandbox:

>Note: the environment in which these programs are executed is deterministic, so each time you run the example program **rand.Intn will return the same number**. (To see a different number, seed the number generator; see rand.Seed.)

**Comment by robphoenix** [comment]
Can be closed @adg @rakyll @broady @kandoiNikhil
