### ISSUE TITLE
tour: [Show Image example is now working properly]

### ISSUE THREAD

**Issue by sinanislekdemir** [golang/tour#1106]
Context: https://tour.golang.org/methods/25

Most likely the library behavior has changed but the given tour example is not updated accordingly;

Here is the output from the given example without any changes;
```
go: finding module for package golang.org/x/tour/pic
go: downloading golang.org/x/tour v0.0.0-20201207214521-004403599411
go: found golang.org/x/tour/pic in golang.org/x/tour v0.0.0-20201207214521-004403599411
./prog.go:9:15: cannot use m (type Image) as type image.Image in argument to pic.ShowImage:
	Image does not implement image.Image (missing At method)

Go build failed.
```

**Comment by ALTree** [comment]
As the text on the left suggest, that is an exercise: 

> Define your own Image type, implement the necessary methods, and call pic.ShowImage. 

So it's normal that the code doesn't compile as it is.

**Comment by sinanislekdemir** [comment]
Oh, this is embarrassing :sweat_smile:  Apologies and thanks for the heads up @ALTree 
My mistake
