### ISSUE TITLE
tour: Grammar Fix in Flow Control Section Page 7

### ISSUE THREAD

**Issue by Numbluk** [golang/tour#111]
Context: https://tour.golang.org/flowcontrol/7

In the second paragraph below the header, the beginning of the sentence:

>Both calls to pow are executed and **return**

Should probably be:

>Both calls to pow are executed and **returned**

**Comment by ALTree** [comment]
I think this is correct. "A call returns" is short for "returns control to the caller". It's an idiom I've seen used often. Closing here.
