### ISSUE TITLE
Concurrency - Buffered Channels

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [golang/tour#1113]
Sends to a buffered channel block only when the buffer is full. Receives block when the buffer is empty. 

Maybe it should be like this:

Sends block to a buffered channel only when the buffer is NOT full. Receives block when the buffer is NOT empty.

**Comment by ALTree** [comment]
Sorry but I really don't understand your version. You have negated the original sentence, but the original is correct, so your negation is not correct... I think this is fine as it is, so closing here.

**Comment by aleksandr-shevchenko** [comment]
Original:
Sends to a buffered channel block only when the buffer is full. Receives block when the buffer is empty.
Modify the example to overfill the buffer and see what happens.

But when we send more items than the buffer size (or in other words, when the buffer is full), we get an error (fatal error: all goroutines are asleep - deadlock!)

**Comment by ALTree** [comment]
Yes, that's right: the send blocks the sender goroutines and no-one else is reading, hence the deadlock. The deadlock error is precisely what proves that the sender is blocked on the send op.

**Comment by aleksandr-shevchenko** [comment]
Maybe write the first two sentences as:
Sending data to a buffered channel is blocked only when the buffer is full. Receiving data is blocked when the buffer is empty.
