### ISSUE TITLE
tour: The documentation for tree is not accessible

### ISSUE THREAD

**Issue by swapnens** [golang/tour#1116]
Context: https://tour.golang.org/concurrency/8

Change the title above to describe your issue and add your feedback here, including code if necessary
![image](https://user-images.githubusercontent.com/25797140/106386468-1e3a2400-63fb-11eb-828e-6cbc49846b67.png)

**Comment by ALTree** [comment]
Mmmh works for me... is this still a problem? Can you access *any* page at all on https://pkg.go.dev?
