### ISSUE TITLE
tour: Tour in spanish respond with 500 error

### ISSUE THREAD

**Issue by lucas-gio** [golang/tour#1117]
Context: https://tour.golang.org/welcome/2

When i want use spanish as language, the server throw an 500 error.
The url afected is: [https://gotour-es.appspot.com/](https://gotour-es.appspot.com/)

**Comment by lucas-gio** [comment]
Looking in issues, i was discover that this is for another languages too:
[https://github.com/golang/tour/issues/1039](https://github.com/golang/tour/issues/1039)

**Comment by ALTree** [comment]
Thanks for reporting this, closing as a dup of #1039.
