### ISSUE TITLE
tour: Run error

### ISSUE THREAD

**Issue by MasihAkbari** [golang/tour#112]
Context: https://tour.golang.org/methods/23

running this sample get the following error:

> tmp/sandbox978823585/main.go:16: cannot use &r (type *rot13Reader) as type io.Reader in argument to io.Copy:
	*rot13Reader does not implement io.Reader (missing Read method)

**Comment by Numbluk** [comment]
Note that this is an "Exercise." You are meant to fix or add something within the given code sample in order for it to run properly; it should not run with just the sample included.

**Comment by gerep** [comment]
@MasihAkbari The problem is in code, not the exercise.

The `io.Copy` expects as a second parameter a `Reader`, not a pointer to Reader.

The other point is that you are passing your struct `r` as parameter to `io.Copy`, you should pass `r.r`

=)

**Comment by MasihAkbari** [comment]
@gerep thanks for your reply
