### ISSUE TITLE
tour: 10/14 Switch evaluation order 

### ISSUE THREAD

**Issue by Philippe-s-Levi** [golang/tour#1123]
Context: https://tour.golang.org/flowcontrol/10

today we are thursday ( 02/18/2021) 

today := time.Now().Weekday()

printing "today" gives "tuesday" ! so  the program prints "Too far away" !

**Comment by ALTree** [comment]
> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader.
