### ISSUE TITLE
tour: strings.Fields return Timeout

### ISSUE THREAD

**Issue by crashburn2** [golang/tour#1127]
Context: https://tour.golang.org/moretypes/23

Change the title above to describe your issue and add your feedback here, including code if necessary

package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Printf("Fields are: %q", strings.Fields("  foo bar  baz   "))
}

function strings.Fields return timeout also in the example description
https://golang.org/pkg/strings/#Fields

**Comment by ALTree** [comment]
There was some issue with the server, should be fixed now. See golang/go#44537.
