### ISSUE TITLE
tour: The example gives timeout

### ISSUE THREAD

**Issue by pcha** [golang/tour#1129]
Context: https://tour.golang.org/concurrency/2

Wher I run the example without changes in the code, this returns time out

![Captura de Pantalla 2021-02-22 a la(s) 15 07 05](https://user-images.githubusercontent.com/10269965/108750420-bec5c480-751f-11eb-89fb-6e82115fac46.png)

**Comment by LaevusDexter** [comment]
https://github.com/golang/tour/issues/1126

**Comment by ALTree** [comment]
There was some issue with the server, should be fixed now. See golang/go#44537.
