### ISSUE TITLE
tour: having a timeout running program

### ISSUE THREAD

**Issue by cheeruption** [golang/tour#1131]
Context: https://tour.golang.org/methods/19

Hi, tried running code on both play golang and tourofgo - got a "timeout running program".

Also tried running someone's code at https://play.golang.org/p/ppPW1HJFwO, got the same mistake.

**Comment by LaevusDexter** [comment]
https://github.com/golang/tour/issues/1126

**Comment by ALTree** [comment]
There was some issue with the server, should be fixed now. See golang/go#44537.
