### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by PabloSalvatierra2020** [golang/tour#1132]
Context: https://tour.golang.org/welcome/2

Change the title above to describe your issue and add your feedback here, including code if necessary

The links that redirect you to take the tour in Russian or Spanish do not work
<img width="1005" alt="Screen Shot 2021-02-24 at 15 45 11" src="https://user-images.githubusercontent.com/60668592/109049682-4abe2480-76b7-11eb-9632-681762f19dac.png">

**Comment by ALTree** [comment]
See #1039. Closing as a dup.
