### ISSUE TITLE
tour: Interfaces code has an error in the Vertex receiver

### ISSUE THREAD

**Issue by j3fflan3** [golang/tour#1133]
Context: https://tour.golang.org/methods/9
Error:
/prog.go:22:4: cannot use v (type Vertex) as type Abser in assignment:
	Vertex does not implement Abser (Abs method has pointer receiver)
The following causes a compilation error:

```
func (v *Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}
```
Change the pointer receiver to a value receiver and it works:
```

func (v Vertex) Abs() float64 {
	return math.Sqrt(v.X*v.X + v.Y*v.Y)
}
```

**Comment by ALTree** [comment]
Text says so:

> Note: There is an error in the example code on line 22. Vertex (the value type) doesn't implement Abser because the Abs method is defined only on *Vertex (the pointer type).
