### ISSUE TITLE
tour: [Dark mode on website]

### ISSUE THREAD

**Issue by joseemelendez** [golang/tour#1134]
Context: https://tour.golang.org/basics/10

It's not about code that I want an issue to talk, it's about the website of "A Tour of Go". It could be great you can add an option on the Menu button that turns the site to dark mode, there so much brightness on the website. I hope you could improve that! Thanks :)

**Comment by ALTree** [comment]
Thanks for the request. This is a dup of #409, so I'm closing here in favour of the older thread.
