### ISSUE TITLE
tour: [tour is NOT available in this languages]

### ISSUE THREAD

**Issue by pavel5243** [golang/tour#1137]
Context: https://tour.golang.org/welcome/2
the tour is not available in these languages:
Ukrainian, Arabic, Traditional Chinese, German, Hebrew, Italian, Romanian, Russian, Spanish, Turkish, 

Text eror: 
"Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."

**Comment by ALTree** [comment]
Thanks, please see #1039.
