### ISSUE TITLE
tour: dead link to golang.org/search?q=Read#Global 

### ISSUE THREAD

**Issue by racingmojo** [golang/tour#1140]
Context: https://tour.golang.org/methods/21

Change the title above to describe your issue and add your feedback here, including code if necessary

referal to "many implementations" using this URL is a dead link

"The Go standard library contains many implementations of this interface, including files, network connections, compressors, ciphers, and others. "

**Comment by santoshkavhar** [comment]
Title: "many implementations" should point to actual interface implementations

This should include at least a few implementation links of io.Reader interface such as below:

1. In Files:
- https://golang.org/pkg/encoding/csv/#NewReader
- https://golang.org/pkg/image/#Decode
- https://golang.org/pkg/encoding/json/#NewDecoder

2. In network connections:
-  https://golang.org/pkg/net/mail/#ReadMessage
-  https://golang.org/pkg/net/http/httputil/#NewChunkedReader

3. Compressors
-  https://golang.org/pkg/compress/gzip/#NewReader
-  https://golang.org/pkg/compress/zlib/#NewReader
-  https://golang.org/pkg/archive/tar/#NewReader
-  https://golang.org/pkg/bytes/#Buffer.ReadFrom
-  https://golang.org/pkg/compress/bzip2/#NewReader
-  https://golang.org/pkg/compress/flate/#NewReader
-  https://golang.org/pkg/archive/zip/#Decompressor
-  https://golang.org/pkg/compress/lzw/#NewReader

4. Ciphers
- https://golang.org/pkg/crypto/dsa/#GenerateKey
- https://golang.org/pkg/crypto/ecdsa/#GenerateKey
- https://golang.org/pkg/crypto/ed25519/#GenerateKey
- https://golang.org/pkg/crypto/elliptic/#GenerateKey
- https://golang.org/pkg/crypto/rand/#Int
- https://golang.org/pkg/crypto/rsa/#GenerateKey
- https://golang.org/pkg/crypto/x509/#CreateCertificate

5.  Others
- https://golang.org/pkg/bufio/#NewReader
- https://golang.org/pkg/strings/#Reader

@racingmojo Please let me know if this isn't what you expect. I'm new to open-source contribution.

**Comment by leeyspaul** [comment]
Hey @santoshkavhar you can probably just remove the dead link instead of trying to find a replacement link. And in the future if the community wants a link can be added or the content can be expanded.

**Comment by M4THYOU** [comment]
How about just linking to this issue? The next exercise wants us to implement a reader and I think having examples like these is crucial to solving this well.

**Comment by leeyspaul** [comment]
I haven't seen actual GitHub issues linked before in documentation as issues are meant to be closed in a repo. Perhaps this link as an alternative and change the wording to emphasize that there are many other examples?

https://golang.org/pkg/io/#Reader

**Comment by ALTree** [comment]
I guess we could change the link to [this](https://cs.opensource.google/search?q=Read%5C(%5Ba-z%5D*%5Cs%5C%5B%5C%5Dbyte%5C)&ss=go%2Fgo)? Seems to be the target in spirit closest to the current wording.

**Comment by leeyspaul** [comment]
Agreed with the closest in spirit!
