### ISSUE TITLE
tour: Change this line of script instead of just displaying v

### ISSUE THREAD

**Issue by githubjo1** [golang/tour#1146]
Context: https://tour.golang.org/basics/14

Code in GoTour: 
line 7: 	fmt.Printf("v is of type %T\n", v)  

O/P:         v is of type int

Change Request:
line 7: 	fmt.Printf("If v is %v, then v is of type %T\n",v,v)

O/P:        If v is 42, then v is of type int

**Comment by ALTree** [comment]
I don't think the text you suggest is better than what we have now; the new phrasing reads as if `v` is of type `int` *because* it's `42`...(?). "If v is 42" etc. I think the current text is both shorter and clearer.
