### ISSUE TITLE
tour: appending to slice increasing capacity one more spot than needed only in a few cases

### ISSUE THREAD

**Issue by khanogalvan** [golang/tour#1148]
Context: https://tour.golang.org/moretypes/15

Change the title above to describe your issue and add your feedback here, including code if necessary. When running the default sample code the output is this:

```
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]
```

It may seem that when adding a single element the capacity and length are increasing just enough to add the new element (just one more spot). However, when adding more than 1 elements it behaves differently:
- If the number of elements added is even, then the capacity and length match (just as with a single element addition), but
- if the number of elements added is odd, then the capacity is increased one more spot than needed, (e.g. above len=5, cap=6).

Is this by design or a bug in the implementation?

**Comment by ALTree** [comment]
This is an internal implementation detail of slices, which is done for performance reasons, and allowed by the Go Specification.
