### ISSUE TITLE
tour: Error while building exercise-slice.go

### ISSUE THREAD

**Issue by ksivvi0** [golang/tour#1149]
Context: https://tour.golang.org/moretypes/18

go: downloading golang.org/x/tour v0.0.0-20201207214521-004403599411
# example
./prog.go:6:1: missing return at end of function

**Comment by ksivvi0** [comment]
exercise-slices.go

**Comment by ALTree** [comment]
It's an exercise:

> Implement Pic.

so it won't compile until you finish the implementation.

**Comment by ksivvi0** [comment]
sorry, iam fool...
