### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by feoktist** [golang/tour#115]
if I write this code:
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	fmt.Println("My favorite number is", rand.Intn(10))
	fmt.Println("My lucky number is ", rand.Intn(100))
	fmt.Println("Random subtraction number of the two is: ", rand.Intn(100) - rand.Intn(10))
}
------------------------------------------------------------------------------------------------------------
The output is:
My favorite number is 1
My lucky number is  87
Random subtraction number of the two is:  38
-----------------------------------------------------------------------------------------------------------
Question: why it is 38 ?  (not 86?)

**Comment by budkin** [comment]
because you call rand.Intn() four times, every time it returns a different number, this would do what you expect
`func main() {
    i := rand.Intn(10)
    j := rand.Intn(100)
    fmt.Println("My favorite number is", i)
    fmt.Println("My lucky number is ", j)
    fmt.Println("Random subtraction number of the two is: ", i - j)
}`

**Comment by robphoenix** [comment]
@budkin's comment is right, you need to store the result of calling `rand.Intn()` in a variable. Does this answer your question @feoktist? If it does would you consider closing this issue? Thanks!

Can probably be closed @adg @rakyll @broady

**Comment by feoktist** [comment]
thanks everyone!
