### ISSUE TITLE
tour: Introduce skipped assignment (_) earlier 

### ISSUE THREAD

**Issue by mattt** [golang/tour#1153]
Context: https://tour.golang.org/moretypes/17

The concept of skipped / omitted assignment (`_`) is introduced in a discussion about `range`:

> You can skip the index or value by assigning to `_`.
>
>```go
>
>for i, _ := range pow
>for _, value := range pow
>```

Given how frequently `_` is used in Go for error handling, I might have expected it to be introduced earlier in a different context. For instance, perhaps on ["Multiple results"](https://tour.golang.org/basics/6) or in a new slide after.

**Comment by ALTree** [comment]
> Given how frequently _ is used in Go for error handling

Yeah, but... I don't think we want to encourage people to do that, errors should not be ignored. The most kosher use of the `_` is exactly for ignoring values or indices in `range`, so it seems reasonable to introduce it there.
