### ISSUE TITLE
tour: Guidance on making content/curriculum edits

### ISSUE THREAD

**Issue by leeyspaul** [golang/tour#1155]
I couldn't find a guide on making curriculum edits based on suggestions. Do we just ship these PRs and it pends approval? It would be great if there was some curriculum guidance on making changes or triaging of sorts.

**Comment by ALTree** [comment]
As noted in the README (https://github.com/golang/tour#contributing) the procedure is essentially the same as the one described in https://golang.org/doc/contribute.html; so that page is mandatory reading to understand how to send changes.
