### ISSUE TITLE
Why is it not possible for send function to send 46 to channel ch2

### ISSUE THREAD

**Issue by Sanketwable** [golang/tour#1157]
Context: https://tour.golang.org/concurrency/3

code is :
<img width="707" alt="Screenshot 2021-03-29 at 9 32 04 AM" src="https://user-images.githubusercontent.com/43716242/112785471-b35f3f00-9071-11eb-8a05-5e2efb991be8.png">
output is :
<img width="373" alt="Screenshot 2021-03-29 at 9 32 11 AM" src="https://user-images.githubusercontent.com/43716242/112785482-b78b5c80-9071-11eb-8ab3-22f984ff1d51.png">

**Comment by ALTree** [comment]
We don't use the issue tracker for questions, it's only to report issues.
