### ISSUE TITLE
tour: [Link to "many implementations" is broken]

### ISSUE THREAD

**Issue by ramesh-km** [golang/tour#1158]
Context: https://tour.golang.org/methods/21

https://golang.org/search?q=Read#Global is displaying this.
![image](https://user-images.githubusercontent.com/58159495/112819951-b9b9df00-90a2-11eb-8166-a400fae71425.png)

**Comment by alexandear** [comment]
Duplicates #1140

**Comment by ALTree** [comment]
Thanks for reporting this; closing as a dup of #1140.
