### ISSUE TITLE
tour: /list route is deeply hided

### ISSUE THREAD

**Issue by Volosatiyslon** [golang/tour#1165]
Context: https://tour.golang.org/list

Hi. Link to list must be placed to first page or included to footer/header of each page. Otherwise it can't be found anywhere. (url tour.golang.org automaticly forward to welcome/1)

**Comment by ALTree** [comment]
There's a better Table of Contents on the right if you click the hamburger menu, I don't think we need to link that page in every lesson.

**Comment by Volosatiyslon** [comment]
May be move "hamburger" to up-left corner?
