### ISSUE TITLE
tour: The link on this page is broken

### ISSUE THREAD

**Issue by ayush268** [golang/tour#1169]
Context: https://tour.golang.org/methods/21

The Go standard library contains [many implementations](https://golang.org/search?q=Read#Global) of this interface, including files, network connections, compressors, ciphers, and others.

The link in the above line is broken and needs to be updated.

**Comment by alexandear** [comment]
Duplicates #1140

**Comment by ALTree** [comment]
Thanks for reporting this; closing as a dup of #1140.
