### ISSUE TITLE
tour: Broken Link

### ISSUE THREAD

**Issue by mclaughlin** [golang/tour#1173]
Context: https://tour.golang.org/methods/21

**Issue:**
Link on [this page](https://tour.golang.org/methods/21) to "[many implementations](https://golang.org/search?q=Read#Global)" takes me to a page that says "open REDACTED: file does not exist"

**What did you do?**
From [this page](https://tour.golang.org/methods/21) I clicked on the link titled "[many implementations](https://golang.org/search?q=Read#Global)".

**What did you expect to see?**
A page that shows the many implementations of the [io.Reader](https://golang.org/pkg/io/#Reader) interface.

**What did you see instead?**
[This page](https://golang.org/search?q=Read#Global), which says "open REDACTED: file does not exist"

**Comment by alexandear** [comment]
Duplicates #1140

**Comment by ALTree** [comment]
Thanks for reporting this; closing as a dup of #1140.
