### ISSUE TITLE
tour: invalid "many implementations" link on /methods/21 page

### ISSUE THREAD

**Issue by echarland** [golang/tour#1175]
Context: [https://tour.golang.org/methods/21](https://tour.golang.org/methods/21)

The "[many implementations](https://golang.org/search?q=Read#Global)" link on the page uses a "/search?" functionality that doesn't seem to exist.

![method_21_screenshot](https://user-images.githubusercontent.com/77163943/116728747-48788f00-a9b4-11eb-932f-4fdb4cc184a5.png)

**Comment by ALTree** [comment]
Thanks for reporting this; closing as a dup of #1140.
