### ISSUE TITLE
tour: [dense example code]

### ISSUE THREAD

**Issue by nishadhsingh** [golang/tour#1185]
Context: https://tour.golang.org/moretypes/9

the example code is very unapproachable to me as beginner, for instance 
s := []struct {
		i int
		b bool
	}{
		{2, true},
		{3, false},
		{5, true},
		{7, true},
		{11, false},
		{13, true},
	}
it would be nice if the example code only uses the syntax that's been already demonstrated on previous lessons, thanks

**Comment by crossphoton** [comment]
The struct implementation can be separated but generally this is a practice many developers follow so this informs the reader that there is no need to separatly define the struct always and you can define the struct there only without any name.

I think about it this way.
Do you have any suggestions?

**Comment by nishadhsingh** [comment]
> 
> 
> The struct implementation can be separated but generally this is a practice many developers follow so this informs the reader that there is no need to separatly define the struct always and you can define the struct there only without any name.
> 
> I think about it this way.
> Do you have any suggestions?

i think think this adds unnecessary complexity , it would be nice if there were comments explaining the syntax
