### ISSUE TITLE
tour: Wrong order of output displayed by Println as per the function call

### ISSUE THREAD

**Issue by Kaps1195** [golang/tour#1191]
Context: https://tour.golang.org/flowcontrol/7

Hello, I was just going through the "Tour of Go" tutorial and I couldn't help but notice on page 7, on the main function, the order of function call is such -> 
1) Call pow(3, 2, 10) first
2) Call pow(3, 3, 20) second

But when I execute the program, I get the output in this format ->
27 >= 20
9 20

Shouldn't the order of the output be like this as per the function call sequentially ->
9 20
27 >= 20

Please excuse me if I'm wrong anywhere as this is my first time exploring the Go Language. I'd be happy to get some clarity on this. Thanks.

**Comment by ALTree** [comment]
Note how the text says:

> Both calls to pow return their results before the call to fmt.Println in main begins.

In other terms, the *both* `pow` calls are evaluated before calling Printf. Since once of the pow calls prints something, that's the first thing you'll see.
