### ISSUE TITLE
tour: Broken link in Methods-21

### ISSUE THREAD

**Issue by ECoulter** [golang/tour#1207]
Context: https://tour.golang.org/methods/21

The file search link pointing to https://golang.org/search?q=Read#Global with text "many implementations"
results in an error page reading "open REDACTED: file does not exist". 

See screenshot:
![go-methods-21-err](https://user-images.githubusercontent.com/3245990/121172567-d81c2380-c825-11eb-82ba-990c7f1ed586.png)

**Comment by ALTree** [comment]
See #1140, closing here as a dup.
