### ISSUE TITLE
Go tour instruction not working

### ISSUE THREAD

**Issue by Zedonboy** [golang/tour#1211]
I am a new golang dev.

`go get golang.org/x/tour` is not working.

I checked my bin folder in GOPATH, no tour binary is there.

I checked my pkg folder, i can see tour packages.

How do i solve this. tour not working.

Iam using Go 1.16.5 amd linux

**Comment by Zedonboy** [comment]
Guys tour is broken.

Use  `go install golang.org/x/website/tour@latest`

**Comment by slimlime** [comment]
Was this fixed before closing? 

Or were you intending to merge issue tracking into #761 into https://github.com/golang/tour/issues/761#issuecomment-865073593

---

Also - alternatives workaround attempts do not work

such as changing env vars

attempting to run go install, go build, go run in the supposed sources directly. "no go files"

**Comment by Zedonboy** [comment]
> Was this fixed before closing?
> 
> Or were you intending to merge issue tracking into #761 into [#761 (comment)](https://github.com/golang/tour/issues/761#issuecomment-865073593)
> 
> Also - alternatives workaround attempts do not work
> 
> such as changing env vars
> 
> attempting to run go install, go build, go run in the supposed sources directly. "no go files"

I do not understand.
