### ISSUE TITLE
tour: For local installation of tour add a note about methods that will fail

### ISSUE THREAD

**Issue by alirezaghey** [golang/tour#1215]
Context: https://tour.golang.org/welcome/3

On Ubuntu focal, I installed Golang from Ubuntu's repositories, which has Go version 1.13. The subsequent `go get golang.org/x/tour` command on the page did not succeed.

I assume this is by design and people are expected to install the latest version linked as advertised on the page for this to work. But considering that we are beginners :sweat_smile:, it would be reasonable to add a note/warning about this. Like saying, "only this methods works", or, "this version and above"...

Thanks!

**Comment by slimlime** [comment]
#1218 #1203 `go get golang.org/x/website/tour `

Part of the challenge is that source contributions are moved off GitHub

**Comment by ALTree** [comment]
Closing as a dup of #1203.

Also source contribution never moved off github: the github repository has always been a mirror. The canonical source is on https://go.googlesource.com/ and the canonical way to send changes is trough gerrit.
