### ISSUE TITLE
tour: typo in description text at "Choosing a value or pointer receiver"

### ISSUE THREAD

**Issue by tkhalifeh** [golang/tour#1224]
Context: https://tour.golang.org/methods/8

typo in description text, incomplete sentence

> In general, all methods on a given type should have either value or pointer receivers, but not a mixture of both. (We'll see why over the next few pages.)

edit suggestion
> In general, all methods on a given type should have either value or pointer receivers, but not **use** a mixture of both. (We'll see why over the next few pages.)

**Comment by ALTree** [comment]
I don't think that's a typo; the sentence structure is:

> All types should have *A*, but not *B*.

*not* refers to the verb *have* that precedes it.
