### ISSUE TITLE
tour: Disable run button till the time request is complete

### ISSUE THREAD

**Issue by sahildua2305** [golang/tour#123]
Context: https://tour.golang.org/concurrency/10

Right now, I can run as many parallel requests to the server as many I want. I can even write a couple of lines of JS code to click the `Run` button multiple times. (or just press and hold `Shift + Enter` for a while)

Ideally, we should disable the `Run` button once it's clicked, till the time we get the response back. I'd like to fix this once confirmed! 😄

**Comment by ALTree** [comment]
When the snippet is running, `Run` is replaced by a `Kill` button, so I believe this is fixed. Comment here if I misunderstood your report. Closing.
