### ISSUE TITLE
tour: [Wrong example of map]

### ISSUE THREAD

**Issue by YakouK** [golang/tour#1232]
Context: https://tour.golang.org/moretypes/21
Here's the example provided and it's not about maps
```
func main() {
	string_b := "Toto\r\n"
	sp := strings.Fields(string_b)
	
	//string_b = strings.TrimRight(string_b, "\r\n")
	string_b = strings.Replace(string_b, "\r", "", -1)

	fmt.Print(len(sp))
	fmt.Print(sp)
	
}
```

**Comment by ALTree** [comment]
Click the reset button, the actual code at that page is not that one. Someone edited, changes are cached locally in your browser.
