### ISSUE TITLE
tour: There is a logic problem in using slices

### ISSUE THREAD

**Issue by mstgnz** [golang/tour#1235]
Context: https://tour.golang.org/moretypes/8

`
    
    package main

    import "fmt"

    func main() {
        names := [4]string{
	    "John", 	    // 0
	    "Paul", 	    // 1
	    "George",    // 2
	    "Ringo", 	    // 3
        }

        a := names[3:4] // is not there a problem? because max inis number 3 not 4
	
        fmt.Println(a)

        fmt.Println(names[3]) // last element indis number 3, its true code
	
        // fmt.Println(names[4]) // invalid array index 4

        // if we are acting with the logic that the counting number starts from 1. there is a problem again
	
        fmt.Println(names[3:4]) // If it gives "Ringo" value.
        fmt.Println(names[1:2]) // It should return the value of "John", not the value of "Paul".
	
        /*
	    According to this sequence, the slice operation must end at 3 if it starts at 0. If it ends at 4 then it must start from 1. only then will it make sense.
        */

    }

`

**Comment by mstgnz** [comment]
yes, it makes more sense to have it that way since the counting starts at one, so it's not problem. thank you.

**Comment by ALTree** [comment]
In `a[x:y]` it's x included, y excluded. It's an half open interval, so it's working as intended.
