### ISSUE TITLE
tour: On mobile the code is invalid

### ISSUE THREAD

**Issue by warvariuc** [golang/tour#1237]
Context: https://tour.golang.org/moretypes/26

![Screenshot_20210830-084300-193](https://user-images.githubusercontent.com/1035452/131291004-2972d816-c888-4496-af70-517b8fd47d22.png)

On desktop it works well.

**Comment by ALTree** [comment]
It's an exercise, so you'll need to write the function to make it compile. On desktop it's the same, but if it was solved previously the solution will persist.
