### ISSUE TITLE
tour: concurrency-8 point 4 is not correct

### ISSUE THREAD

**Issue by tito10047** [golang/tour#124]
Context: https://tour.golang.org/concurrency/8

```
func Same(t1, t2 *tree.Tree) bool{
	return t1.Value==t2.Value
}

func main() {
	fmt.Println(tree.New(1))
	fmt.Println(tree.New(1))
	fmt.Println(tree.New(1).Value)
	fmt.Println(tree.New(1).Value)
	if Same(tree.New(1), tree.New(1))==false {
		fmt.Println("bad 1")
	}
	if Same(tree.New(1), tree.New(2)){
		fmt.Println("bad 2")
	}
}

```
In console I have:
```
((((1 (2)) 3 (4)) 5 ((6) 7 ((8) 9))) 10)
((((1) 2 (3)) 4 (5 (6))) 7 ((8) 9 (10)))
8
7
bad 1
```

But in tour is writen:

> 4. Test the Same function.
> Same(tree.New(1), tree.New(1)) should return true

**Comment by ALTree** [comment]
> Same(tree.New(1), tree.New(1)) should return true

What it means is: "if your implementation of Same is correct, it'll return true on `Same(tree.New(1), tree.New(1))`". Your implementation is not correct (you need to walk the tree), so it's not returning true.

Closing here, since this is working as expected.
