### ISSUE TITLE
[Need help] tour: Unable to handle multiple arguments passed to method

### ISSUE THREAD

**Issue by afzal442** [golang/tour#1241]
Context: https://tour.golang.org/methods/

```
package main

import "fmt"

type I interface {
	M()
}
type F int

func (f, j F) M() {
}

func main() {
	var i I
	i = F(42.6, 67.6)
	describe(i)
	i.M()
}

func describe(i I) {
	fmt.Printf("(%v, %T)\n", i, i)
}

```

Error: 
./prog.go:10:15: method has multiple receivers
./prog.go:15:7: too many arguments to conversion to F: F(42, 67)

Is there any way to pass multiple arguments? 
Desired: It should handle multiple receivers;

**Comment by ALTree** [comment]
Nope, they need to be passed as additional args.
