### ISSUE TITLE
tour: Enter tour with `PageDown`

### ISSUE THREAD

**Issue by minhqdao** [golang/tour#1264]
Context: https://tour.golang.org/list

Being able to navigate the tour with `PageUp` and `PageDown` arrows is a great convenience. Unfortunately, the user is stuck once "the [ top](https://tour.golang.org/list)" is reached. It would be great if one could (re-)enter the tour via a `PageDown`, ensuring seamless navigation between the list and the individual chapters. There would be no conflicts with other key bindings, either.

**Comment by ALTree** [comment]
I agree it's unfortunate but in the lessons PageUp and PageDown trigger the back / forward arrows, I think it would be counter-intuitive to have that on the tour/list page, since it doesn't have the arrows.

**Comment by minhqdao** [comment]
Maybe we could add an arrow that says "Begin tour -->" then 😄
