### ISSUE TITLE
tour: Typo in tutorial

### ISSUE THREAD

**Issue by LarsHadidi** [golang/tour#1268]
Context: https://tour.golang.org/basics/3

"To fix the error, rename math.pi to math.Pi and try it again."
LINE 9: fmt.Println(math.Pi)

Already capitalized.

**Comment by ALTree** [comment]
It's locally cached from the browser (someone using the same pc changed it in the past). Press the Reset button to restore the snippet to its original form.

**Comment by LarsHadidi** [comment]
True. That's weird. I'm the only user of the computer and I haven't changed it.
