### ISSUE TITLE
tour: Error communicating with remote server

### ISSUE THREAD

**Issue by n8jhj** [golang/tour#1269]
Context: https://go.dev/tour/welcome/1

Running any part of the Tour of Go, I get "Error communicating with remote server."

![image](https://user-images.githubusercontent.com/21087278/142918802-df2bd90f-763d-4800-b0ad-be8f0e2d2348.png)

I noticed [#18322](https://github.com/golang/go/issues/18322); this does not seem to be related, since the [link posted there](https://play.golang.org/p/ZRfp3kn9HA) works fine, as does any other usage of the Go Playground.

**Comment by ALTree** [comment]
I think they broke during the recent move to the playground to go.dev (happened a few years ago).

cc @rsc

**Comment by jccatrinck** [comment]
Same here 
# [HTTP Archive: go.dev.har.gz](https://github.com/golang/tour/files/7585119/go.dev.har.gz)
![image](https://user-images.githubusercontent.com/7607939/142952654-05674e04-34d5-48fc-972b-e545c0f74f6b.png)

**Comment by juliustayl** [comment]
This is an issue for me as well
![A-Tour-of-Go](https://user-images.githubusercontent.com/2043842/142960372-e7784ac3-b8c7-473a-aa67-1a1a52b088a3.png)
.

**Comment by emmohac** [comment]
This also happens to me.

<img width="724" alt="Screen Shot 2021-11-22 at 8 57 13 PM" src="https://user-images.githubusercontent.com/29102852/142973306-81436b09-6619-4067-b6f6-54cb590f8bf8.png">

**Comment by ALTree** [comment]
Should be fixed now (see #1272), delete the browser cache if you're still seeing this. Closing here.

**Comment by imylyanyk** [comment]
Unfortunately, this still seems to be a problem, even after I cleared the cache (in firefox).
The server returns error code 500 with Internal Server Error, not very descriptive.

Am I missing something?
