### ISSUE TITLE
tour: "does what you'd expect" is not helpful

### ISSUE THREAD

**Issue by eythian** [golang/tour#127]
Context: https://tour.golang.org/moretypes/2

The description is:

    A struct is a collection of fields.
    
    (And a type declaration does what you'd expect.) 

I think that having "does what you'd expect" in a tutorial isn't wise, given you don't know what people expect, or what their experience of a C-like language is. I think it should be replaced with something that explains what it actually does.

**Comment by michaelorr** [comment]
This is noted as a confusing point for people new to Go or to statically typed languages. https://twitter.com/polotek/status/827570862819725313
I think we can do better.

**Comment by zombiezen** [comment]
@broady This is a dupe of #121

**Comment by ALTree** [comment]
Closing as a dup of #121
