### ISSUE TITLE
tour: Error communicating with remote server.

### ISSUE THREAD

**Issue by zbhuiyan** [golang/tour#1272]
Context: https://go.dev/tour/methods/21
Running the examples is giving me the error "Error communicating with remote server".

**Comment by andreea1110** [comment]
I am experiencing the same issue with all the examples I've tried to run in the Tour of Go [](https://go.dev/tour/) .

**Comment by ALTree** [comment]
This should be now fixed server side, try to delete the browser cache for the tour pages.

**Comment by andreea1110** [comment]
Indeed, the examples are working now, after deleting the browser cache. Thank you!

**Comment by ALTree** [comment]
Thanks for confirming. Closing here

**Comment by dan-ih** [comment]
I am having this same issue

**Comment by michaelskyba** [comment]
I'm having the same issue on https://go.dev/tour/basics/3, trying to run the default code

Both qutebrowser and Brave have the same message, and using a private window, which shouldn't have any cache, doesn't fix it

**Comment by stonecharioteer** [comment]
+1 on google chrome, both in incognito and normal, with the very first exercise.

**Comment by michaelskyba** [comment]
It works now for me, not sure what changed
