### ISSUE TITLE
tour: Broken modules list links

### ISSUE THREAD

**Issue by meznak** [golang/tour#1275]
Context: https://go.dev/tour/flowcontrol/14
https://go.dev/tour/basics/17
presumably other "congratulations!" pages

The link to return to the modules list is broken.
https://go.dev/list is 404. The list is actually at https://go.dev/tour/list

**Comment by meznak** [comment]
Same problem with the https://go.dev/flowcontrol/8 link on https://go.dev/tour/flowcontrol/8

**Comment by ALTree** [comment]
Fixed in [CL 367336](https://go-review.googlesource.com/c/website/+/367336), closing.
