### ISSUE TITLE
Error communicating with remote server.

### ISSUE THREAD

**Issue by Chriztiaan** [golang/tour#1281]
Not sure why I am getting this issue? I've tried clearing my browser's cache, and I've tried other browsers as well.

**Comment by waliag87** [comment]
Also having this issue.

**Comment by Sergey01** [comment]
Getting the same error. Console output on a Chromium-based browser is this:

`Failed to load resource: the server responded with a status of 500 ()`
`POST https://go.dev/_/compile?backend=undefined 500`

**Comment by ALTree** [comment]
Mmh, looks like this is back (it was working the other day).

**Comment by wab3463** [comment]
Also having this same issue. Every tour exercise fails with 500, while playground works fine.

Tour:
![image](https://user-images.githubusercontent.com/78984598/144430013-b68d971d-87e8-4c22-898e-a64752cfc0f2.png)

Playground:
![image](https://user-images.githubusercontent.com/78984598/144429896-4d3cdfe7-0ff4-4082-a65b-90783410bdf7.png)

I've tried clearing the browser cache, and trying different browsers, to no avail.

**Comment by Sergey01** [comment]
Yeah, it looks like `compile?backend=undefined` is causing it. So the fix would be to either change the frontend code to never pass undefined params as strings to the compile API call or to modify the server API to safely handle an _undefined_ (and maybe _null_) "backend" param.
