### ISSUE TITLE
tour: Internal Server Error when attempting to run code

### ISSUE THREAD

**Issue by austin-c-thomas** [golang/tour#1288]
Context: https://go.dev/tour/welcome/1

Getting a 500 throughout the tour when trying to run code. Request posting to https://go.dev/_/compile?backend=undefined

**Comment by Notalifeform** [comment]
the playground does work, it refers to `https://go.dev/_/compile?backend=`

**Comment by ALTree** [comment]
I believe this was fixed by https://go-review.googlesource.com/c/website/+/368914, but it hasn't been deployed yet.

**Comment by ALTree** [comment]
Fix should be deployed, closing here.
