### ISSUE TITLE
tour: "Error Communicating with Server" caused by js issue

### ISSUE THREAD

**Issue by stsully** [golang/tour#1291]
Context: https://go.dev/tour/moretypes/7

Happens on my Mac, Big Sur 11.6.1
Both Firefox and Safari browsers

Every time I click run on any of the go tour Playground code samples, I get "Error communicating with server." I expected to get a response of 200, and show the output of my code sample instead. 

This error is a 500 response to my post request to this URL:
'https://go.dev/_/compile?backend=undefined'

I observed that if I try the same thing on https://go.dev/play, the URL is:
'https://go.dev/_/compile?backend='

and sure enough, if I modify the URL I can get it to respond with a 200 (but the output is binary)
![Screen Shot 2021-12-05 at 9 50 26 AM](https://user-images.githubusercontent.com/37844120/144755606-b1f5f662-f30c-4ae6-b7d7-98e6f3ed7990.png)
.

**Comment by ALTree** [comment]
Thanks for reporting this. See #1288. Closing in favour of the older thread.
