### ISSUE TITLE
tour: Formatted output for the empty string

### ISSUE THREAD

**Issue by romanegunkov** [golang/tour#1297]
Context: https://go.dev/tour/basics/12

I think it will be more appropriate to use "%#v" for all values, than "%q" for the empty string. 
`
fmt.Printf("%#v %#v %#v %#v\n", i, f, b, s)
`
instead of
`
fmt.Printf("%v %v %v %q\n", i, f, b, s)
`

**Comment by ALTree** [comment]
`%q` will show `""` for the empty string, with `%v` you would see nothing. I think `%q` is a better choice here.

**Comment by romanegunkov** [comment]
I proposed `%#v`, not `%v`. It also show `""`.

![image](https://user-images.githubusercontent.com/9414908/147545588-15ff70f6-f17d-4839-8acd-df4c98473034.png)

**Comment by ALTree** [comment]
Ah, right. That's a modifier, thought, a little more complicated the the simple verbs.
