### ISSUE TITLE
Broken link under Methods module Readers page 21/26

### ISSUE THREAD

**Issue by hmatny** [golang/tour#1299]
The link to the implementation of the io reader interface is broken 
https://cs.opensource.google/search?q=Read%5C(%5Cw%2B%5Cs%5C%5B%5C%5Dbyte%5C)&ss=go%2Fgo

**Comment by ALTree** [comment]
Works for me. Maybe a temporary server issue?

**Comment by hmatny** [comment]
I think you're right. Seems to be working now. Sorry!
