### ISSUE TITLE
tour: Issues when using append

### ISSUE THREAD

**Issue by FlyWings** [golang/tour#13]
Hello expert:
  When go through the golang tour, I encounter an issue that confused me, could you please help to explain?
The scenarios could be: I have a original array (names), and copy partial data to slice  (a), then I add additional data to slice (a), then the original array is affected. Please note that I use additional value to append to splice, I wonder why the original array are affected, many thanks for your answer!

Best Regards   
Chengchang

Context: https://tour.golang.org/moretypes/8

```javascript
package main
import "fmt"
func main() {
	names := [4]string{
		"John",
		"Paul",
		"George",
		"Ringo",
	}
	fmt.Println(names)

	a := names[0:3]
	fmt.Println(a)
	
	add := "xxxx"
	a = append(a, add)
	
	fmt.Println(a)
	fmt.Println(names)
}
```

**Comment by adg** [comment]
It's because `a` is not a copy of `names`, it is a slice that refers to `names`. So when you `append` to it it overwrites the last element of the slice.

See https://blog.golang.org/slices
