### ISSUE TITLE
tour: [typo in the problem set]

### ISSUE THREAD

**Issue by DeviRule** [golang/tour#1304]
Context: https://go.dev/tour/moretypes/18

In the first sentence, it should be "each element of which is a slice of length dx" rather than "each element of which is a slice of dx"

**Comment by ALTree** [comment]
Should be read as:

> dx 8-bit unsigned integers

e.g.: "a slice of 19 8-bit unsigned integers", so it's "19 integers" and "8-bit" and "unsigned" are adjectives qualifying the noun "integers".
