### ISSUE TITLE
tour: incorrect weekday in web tour

### ISSUE THREAD

**Issue by Eleyvie** [golang/tour#131]
Context: https://tour.golang.org/flowcontrol/10

It is Friday today, but the script insists it's Tuesday and the Saturday is therefore "too far away". When moved to local machine the script works correctly.

**Comment by gerep** [comment]
> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader.

=)

**Comment by Eleyvie** [comment]
Erm... I would expect that someone who's going through "Tour of Go" exercises is probably more concerned with the fact that his script doesn't work, rather than with the hidden significance of some date.

**Comment by ALTree** [comment]
> Erm... I would expect that someone who's going through "Tour of Go" exercises is probably more concerned with the fact that his script doesn't work, rather than with the hidden significance of some date.

I agree. We may want to change the example to stop using time. It's just for a switch. We could find a better example. I wrote this on #91, closing here as a dup.
