### ISSUE TITLE
tour: [sandbox.go welcome/4 time.Now() return static value.]

### ISSUE THREAD

**Issue by kandas22** [golang/tour#1320]
Context: https://go.dev/tour/welcome/4

welcome/4 time.Now() return static value.
Code line : fmt.Println("The time is", time.Now())

Output: 
The time is 2009-11-10 23:00:00 +0000 UTC m=+0.000000001

![Screen Shot 2022-02-21 at 10 13 59 AM](https://user-images.githubusercontent.com/53490853/154890678-429dd810-f590-4e28-8d08-e00aa66d367b.png)

**Comment by ALTree** [comment]
It explains why in the text: 


>  In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.
> 
>   There are also limits on execution time and on CPU and memory usage, and the program cannot access external network hosts.
