### ISSUE TITLE
tour: Build failed for Go Playground

### ISSUE THREAD

**Issue by kimprice** [golang/tour#1326]
Context: https://go.dev/tour/basics/11

![image](https://user-images.githubusercontent.com/15070078/158597548-27aa02ee-0e13-4a2a-a798-e6ddd340d7be.png)

**Comment by kimprice** [comment]
It seems to be failing on all the pages. So far none of them have built successfully. It was working a few days ago. Looks like the Go Playground itself is also failing. Maybe this has to do with the 1.18 release?

**Comment by kimprice** [comment]
It's running now! :)

**Comment by dmitshur** [comment]
Thanks, I'll close this as a duplicate of golang/go#51708.
