### ISSUE TITLE
Generic Types has a spelling mistake

### ISSUE THREAD

**Issue by prb112** [golang/tour#1327]
Generic Types has a spelling mistake
https://go.dev/tour/generics/2

> In addition to generic functions, Go also supports generic types. A type can be parameterized with a type paremeter, which could be useful for implementing generic data structures. 

It should be updated to:

In addition to generic functions, Go also supports generic types. A type can be parameterized with a type *parameter*, which could be useful for implementing generic data structures.

**Comment by ianlancetaylor** [comment]
Thanks.  If you are going to send a pull request for a simple change like this, no need to also open an issue.

**Comment by ianlancetaylor** [comment]
Fixed by https://go.dev/cl/394314.
