### ISSUE TITLE
tour: Tutorial on the left does not reflect the code content

### ISSUE THREAD

**Issue by OfoeApronti** [golang/tour#1334]
Context: https://go.dev/tour/methods/4

The code on the right has no pointers however the accompanying tutorial makes extensive reference to pointers. For instance, I quote a section 
"
Try removing the * from the declaration of the Scale function on line 16 and observe how the program's behavior changes.
"
Line 16 instead has this code `fmt.Println(b)`

**Comment by eugenesimakin** [comment]
At the moment of adding this comment, the code on line 16 is:
```
func (v Vertex) Scale(f float64) {
```

The issue still persists because there is no `*` (asterisk character) on this line.
Since I'm new to the Go lang, I'm not sure where the compiler implicitly puts it.

**Comment by ALTree** [comment]
You or someone else using the same browser probably edited the code and changes are remembered. The original code follows the text.
