### ISSUE TITLE
tour: ScaleFunc in the playground code takes two args; only one given in the prose

### ISSUE THREAD

**Issue by glenntrewitt** [golang/tour#134]
Context: https://tour.golang.org/methods/6

var v Vertex
ScaleFunc(v)  // Compile error!
ScaleFunc(&v) // OK

**Comment by JESii** [comment]
Looks like this has been corrected.

**Comment by glenntrewitt** [comment]
Thanks for letting me know.
I wonder why I didn't see a notification from the bug.
​    - Glenn

**Comment by ALTree** [comment]
Yep, this is fixed. Closing.
