### ISSUE TITLE
tour: no output in example 16

### ISSUE THREAD

**Issue by PabloGancharov** [golang/tour#137]
Context: https://tour.golang.org/moretypes/16

when running the example 16, there is no output of the example, 

that is caused by a typo in the line:

`fmt.Printf("2**%d = %d\n", i, v)`

it's missing a space before the return "\n"

`		fmt.Printf("2**%d = %d \n", i, v)`

**Comment by JESii** [comment]
Actually, there must be some other problem - the page works fine for me.

And on the face of it, there is no problem with a space before the `\n` in that statement - I use fmt.Printf with things like `%d\n` all the time.

**Comment by robphoenix** [comment]
Can confirm the page works as expected for me also.

I believe @JESii has answered this issue. @PabloGancharov would you mind closing this if you feel it has been addressed, thanks!

**Comment by tauki** [comment]
Hi, the page works fine as the previous two comments mentioned. And "/n" in this context means it will print a new line right after where it's put but if you put a space before /n that will simply print a blank space before going to the new line. @PabloGancharov if you could kindly close the issue that would be nice.

**Comment by ALTree** [comment]
Seems invalid. Closing.
