### ISSUE TITLE
tour: Slices starts from 0 through 3

### ISSUE THREAD

**Issue by bml0aGlu** [golang/tour#1373]
Context: https://go.dev/tour/moretypes/7

Change the title above to describe your issue and add your feedback here, including code if necessary

```
The following expression creates a slice which includes elements 1 through 3 of a:
```
The above line should be changed to: `The following expression creates a slice which includes elements 0 through 3 of a:`

**Comment by crisman** [comment]
It does not contain element `0` as the low bound of the slice expression `a[1:4]` starts at element `1`, skipping `0`.
