### ISSUE TITLE
No append() example in the code

### ISSUE THREAD

**Issue by MELI-dinak** [golang/tour#1377]
Context: https://go.dev/tour/moretypes/15

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by crisman** [comment]
`append.go` uses `append()` on lines 10, 14, & 18.

You may be viewing a local edit, please click the `Reset` button at the bottom of the code window.

Your browser will remember any edits that were done in a previous session.
    
Do you still not see any `append()` after pressing `Reset`?
