### ISSUE TITLE
tour: no unit in the example

### ISSUE THREAD

**Issue by rtrzebinski-usc** [golang/tour#1391]
Context: https://go.dev/tour/basics/13

```
Try removing the float64 or uint conversions in the example and see what happens.
```

there is no `uint` in the example code snippet

**Comment by crisman** [comment]
In `type-conversions.go` see line 11:

>         var z uint = uint(f)

You may have a local edit, please click the `Reset` button at the bottom of the code window.

Your browser will remember any edits that were done in a previous session.
