### ISSUE TITLE
tour: New array? What about garbage collection?

### ISSUE THREAD

**Issue by kris-nova** [golang/tour#14]
Context: https://tour.golang.org/moretypes/15

> If the backing array of s is too small to fit all the given values a bigger array will be allocated. The returned slice will point to the newly allocated array.

It would be useful to understand at what **cost** this newly created array would be. How does Go handle garbage collection is situations like this? What happens to the old array?

This might be outside of the scope of a tutorial, but I would find a sentence or two on what happens to the old array useful.

Cheers!

**Comment by ALTree** [comment]
Thanks for the report.

> This might be outside of the scope of a tutorial,

I also think it is. The tour is a very lightweight introduction to the language. AFAIK nowhere in the whole tour we venture in discussions on low-level details about memory-management, or the way runtime and the garbage collector work.

For this reason I'm going to close this issue, as I think what you ask is out of scope for the tour.
