### ISSUE TITLE
tour: first snippet of the tour won't format

### ISSUE THREAD

**Issue by Skaifai** [golang/tour#1424]
1. What version of Go are you using (go version)?
    Context: https://go.dev/tour/welcome/1
2. What operating system and processor architecture are you using?
    OS: Windows 10 (64-bit), version 21H2, build 19044.2364
    Browser: Version 108.0.5359.125 (Official Build) (64-bit)
    Processor: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
3. What did you do?
    I pressed the "Format" button on the website, trying to format this code.
   ```
   package main

   import "fmt"

   func main() {

	   fmt.Println
	   ("Hello, 世界")
   }
   ```
4. What did you expect to see?
   ```
   package main

   import "fmt"

   func main() {

   	   fmt.Println("Hello, 世界")
   }
   ```
5. What did you see?
    Nothing changed. The code stayed the same.

**Comment by ALTree** [comment]
Maybe a temporary failure? The format button works now.
