### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Reddadmed** [golang/tour#1427]
Hi guys please im facing a little problem here can anyone help me!
![WhatsApp Image 2022-12-25 at 03 42 09](https://user-images.githubusercontent.com/56980984/209456372-d2123975-1cee-47a5-9d45-61e6423ef53b.jpeg)
![WhatsApp Image 2022-12-25 at 03 42 10](https://user-images.githubusercontent.com/56980984/209456374-1506d45e-933f-4574-b5a2-780a5f71a411.jpeg)

**Comment by PragyaJaiswal** [comment]
You should have the `else if` right next to the closing curly braces for the if. 
```
if x < 10 {
      fmt.Println(x)
} else if x > 9 {
      fmt.Println("more than 9")
}
```
<img width="563" alt="Screenshot 2023-03-03 at 11 24 59 AM" src="https://user-images.githubusercontent.com/8311521/222708429-b50b46a9-ad26-4b58-9135-004ee9ee80b3.png">
