### ISSUE TITLE
tour: A note about Loops and Functions...

### ISSUE THREAD

**Issue by modulok** [golang/tour#144]
Context: https://tour.golang.org/flowcontrol/8

Just as a courtesy it might be worth mentioning on this page that Go uses math.Pow() instead of a power operator. It tripped me up at first. Coming from Python I instinctively tried to use ** to do exponentiation. I got, a now obvious, "invalid indirect" error from the compiler that took some head scratching. Just a thought. If not, that's fine too. Rookie mistake!

**Comment by JESii** [comment]
I had the same problem, also trying the ^ operator. I learned that there is no power operator in Go.... you just have to use math.Pow. So it helpful to be explicit about that on this page.

**Comment by modulok** [comment]
Cool. That's two drops in the ocean, lol.

**Comment by ALTree** [comment]
This was changed to show that what you do is `z*z` (there's not longer a `z²`), so I think it's fine not to make the explanation even more verbose by mentioning `Pow`, that you should *not* use to solve that exercise. Closing here.
