### ISSUE TITLE
tour: please use better variable names

### ISSUE THREAD

**Issue by Corbie-42** [golang/tour#1447]
Variable names are an important part of clean code.

Let's have a look at the example in https://go.dev/tour/concurrency/2:
```go
package main

import "fmt"

func sum(s []int, c chan int) {
	sum := 0
	for _, v := range s {
		sum += v
	}
	c <- sum // send sum to c
}

func main() {
	s := []int{7, 2, 8, -9, 4, 0}

	c := make(chan int)
	go sum(s[:len(s)/2], c)
	go sum(s[len(s)/2:], c)
	x, y := <-c, <-c // receive from c

	fmt.Println(x, y, x+y)
}
```

This is not only a bad example for junior developers, who might see this as a "good code" example, but it's also confusing.
What does `c` mean?
Does it have to be named `c` both functions?

(And: Why `x+y`? Why define a single `s` and split it?)

Have a look at this example:
```go
package main

import "fmt"

func sum(summands []int, outputChannel chan int) {
	sum := 0
	for _, value := range summands {
		sum += value 
	}
	outputChannel <- sum // send sum to the channel
}

func main() {
	channel := make(chan int)

	a := []int{7, 2, 8}
	b := []int{-9, 4, 0}

	go sum(a, channel)
	go sum(b, channel)

	x, y := <-channel, <-channel // receive from the channel

	fmt.Println(x, y)
}
```

Is this more complex because of the "long" variable names?

Variables like `a`, `b`, `x` and `y` are known in a mathematical context, so I find them okay-ish in an example.

**Comment by ALTree** [comment]
Single letter variable names are idiomatic in Go (and in C) for these kinds of short functions. The longer names you suggest are not often seen in Go for small snippets.
