### ISSUE TITLE
tour: not deterministic rand number as noted in the tour description

### ISSUE THREAD

**Issue by fanxia** [golang/tour#1448]
Context: https://go.dev/tour/basics/1

In the section `package`, there is `Note: The environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number.` in the description. However, I got different numbers run the example program every time.

**Comment by crisman** [comment]
I think this is the 1.20 change that "automatically seeds the global random number generator"
https://go.dev/doc/go1.20#math/rand

Probably just remove the last two paragraphs on that page, "Note: ..." and the parenthetical after that.
