### ISSUE TITLE
tour: Exercise: Readers

### ISSUE THREAD

**Issue by htolic** [golang/tour#145]
Context: https://tour.golang.org/methods/22

If you implement a `Reader` like this:
```
func (mr MyReader) Read(p []byte) (int, error) {
	return copy(p, []byte{'A'}), nil
}
```
and run the code you get success:
```
got byte 41 at offset 0
OK!
```
The implementation of `Reader` is obviously wrong, it is not an infinite stream, yet we get `reader.Validate()` to pass the tests. I think `reader.Validate()` in package `golang.org/x/tour/reader` needs revision. Sorry but I have not examined the code enough and still not skilled enough in Golang. I'm interested in the code commit that will fix `Validate()`.

**Comment by htolic** [comment]
As a note, I got that output by playing around with `main()`, it looks like this - similar to `Validate()` from `golang.org/x/tour/reader`:
```
func main() {
	b := make([]byte, 1024, 2048)
	r := MyReader{}
	n, _ := r.Read(b)
	for i, v := range b[:n] {
		fmt.Printf("got byte %x at offset %v\n", v, i)
	}
	
	reader.Validate(MyReader{})
}
```

**Comment by asyncanup** [comment]
It is an infinite stream because repeated calls to .Read() will keep returning new bytes (all equal to `[]byte("A")`)
