### ISSUE TITLE
tour: typo in Printf format string

### ISSUE THREAD

**Issue by xdavidliu** [golang/tour#1451]
Context: https://go.dev/tour/basics/4

currently, it says fmt.Printf("foo %i\n", add(2, 4))

Running it prints `foo %!i(int=6)`

it should be %d, not %i.

The discrepancy does not seem deliberate because the prose text on the left half of the slide doesn't mention any mistakes we are supposed to be fixing.

**Comment by crisman** [comment]
That's a local edit, please click the `Reset` button at the bottom of the code window.

Your browsers will remember any edits that were done in a previous session.
