### ISSUE TITLE
tour: Minor type (extra "after")

### ISSUE THREAD

**Issue by sergiofgonzalez** [golang/tour#1453]
Context: https://go.dev/tour/concurrency/4

Hi!

There seems to be an extra "after" right at the end of the first paragraph.

Receivers can test whether a channel has been closed by assigning a second parameter to the receive expression: ~~after~~

Kind regards,
Sergio

**Comment by crisman** [comment]
It reads "after `v, ok := <-ch` `ok` is `false` if there are no more values to receive and the channel is closed."  It is a bit hard to see with the code block in the middle, but is needed.

**Comment by sergiofgonzalez** [comment]
You're completely right - apologies.

Probably an extra newline after the color would help interpreting it:

parameter to the receive expression: ~~after~~

after

```go
v, ok := <-ch
```
ok is false if there...
