### ISSUE TITLE
Update codemirror (editor) and enable some features

### ISSUE THREAD

**Issue by spf13** [golang/tour#146]
Go tour already uses http://codemirror.net/. It could benefit from an update as the version used is out of date.

It would also be nice to enable features like bracket (paran) matching. 

Autocomplete support would be a very nice to have as would linting. codemirror supports both but not sure how hard the integration would be with go-code.

**Comment by shurcooL** [comment]
I've created CL https://golang.org/cl/41207 that updates CodeMirror editor to latest version, which helps this issue. (It seems @gopherbot doesn't do mentions for this repo.)

**Comment by shurcooL** [comment]
The "update to latest version of CodeMirror" part of this issue has been done in the aforementioned CL. That leaves the "would also be nice to enable features" part.

I want to ask for more information about that. What exactly do we want to enable, and how do we know it's going to be an improvement to the tour editor?

My concern is that different people have opposing desires for the editor. Some prefer to have fewer features, with minimal or no syntax highlighting, etc. Others prefer as many features as possible. How can we decide what features to enable without making the experience worse for some people?

Another factor is that I've seen in the history that features like paren matching were previously in the codebase, but later removed. E.g., see [CL 114480043](https://golang.org/cl/114480043) titled "go-tour: remove brace matching addon and unused trailing space addon" (created by @campoy, reviewed by @adg). It's a CL from 2014 and there's not much context in the commit message or the review, but any information on that would be helpful to make progress here. Thanks!

**Comment by campoy** [comment]
This was discussed long time ago, and many found the autocomplete and bracket match too distracting, that's why it was removed.

**Comment by shurcooL** [comment]
I see, thanks. That makes sense to me.

To keep the open issues here more actionable, I'll consider this issue resolved by [CL 41207](https://golang.org/cl/41207) (since the bracket matching/autocomplete were optional parts).

If there's more concrete information about additional features we want to turn on, with a good plan for how to ensure it doesn't detract from the Go tour experience, a new specific issue can be opened for that (or feel free to re-open this one).
