### ISSUE TITLE
tour: wrong package name

### ISSUE THREAD

**Issue by autthapone** [golang/tour#1460]
Context: https://go.dev/tour/basics/16

Please fix wrong package name from `numpackage main` to `package main`

**Comment by crisman** [comment]
That's probably a local edit, please click the `Reset` button at the bottom of the code window.

Your browser will remember any edits that were done in a previous session.

Do you still see the typo after pressing `Reset`?

**Comment by autthapone** [comment]
I misunderstood the local edit. Thank you for your explanation. It works
after Reset.

**Comment by crisman** [comment]
If you have a moment, please close this issue.  Thanks.
