### ISSUE TITLE
Type inference : Unexpected Error

### ISSUE THREAD

**Issue by d-athan** [golang/tour#1469]
Context: https://go.dev/tour/basics/14

I changed the body of func main() as follows : 

```go
func main() {
	var v complex128 = 487587657865785758765867576828576576576576657466 // change me!
	z := 487587657865785758765867576828576576576576657466
	fmt.Printf("v is of type %T\n", v)
}
``` 
and I got the following error on line 7 which is the assignment of variable "z" :
./prog.go:7:7: cannot use 487587657865785758765867576828576576576576657466 (untyped int constant) as int value in assignment (overflows)

On the left side of the page it reads that "But when the right hand side contains an untyped numeric constant, the new variable may be an int, float64, or complex128 depending on the precision of the constant". I would expect that variable "z" after the assignment would get the type of complex128 like variable "v" in the line above. What am I missing?

**Comment by crisman** [comment]
> depending on the precision of the constant

If there is an imaginary part it could be complex128, as there is no imaginary part nor is there a decimal part (which could make it float) the constant expression (long number on the right) is parsed (as the error says) as a "untyped int constant" which happens to be larger than int can hold, thus the error.

If you want to store a very large integer in a constant you can, but that would be `const z = 487...` as is shown on the next slide of the tour.
https://go.dev/tour/basics/15

See also: https://go.dev/ref/spec#Constants

> An untyped constant has a default type which is the type to which the constant is implicitly converted in contexts where a typed value is required, for instance, in a [short variable declaration](https://go.dev/ref/spec#Short_variable_declarations) such as i := 0 where there is no explicit type. The default type of an untyped constant is bool, rune, int, float64, complex128 or string respectively, depending on whether it is a boolean, rune, integer, floating-point, complex, or string constant.

**Comment by d-athan** [comment]
Thank you
