### ISSUE TITLE
tour: math module does not contain lowercase pi

### ISSUE THREAD

**Issue by dc-avasilev** [golang/tour#1472]
Context: https://go.dev/tour/basics/3

math module does not contain lowercase pi constant, only capitalized pi constant in golang version 1.20

![image](https://user-images.githubusercontent.com/17141669/230770138-9a609d6e-618b-44d7-8a97-06f98abcec90.png)

![image](https://user-images.githubusercontent.com/17141669/230770203-fb181a41-d30e-44a6-96af-59c108e7782f.png)

**Comment by crisman** [comment]
Yes, that is the point of the exercise. To see the error when you run it with the lower case version and then see the correct running when changed to upper case.

> To fix the error, rename math.pi to math.Pi and try it again.

**Comment by dc-avasilev** [comment]
oops, didn't read the description of the tour, copy-pasted and dealt with code examples on my own, my fault, sorry.
That's why I thought there was a mistake
