### ISSUE TITLE
exported-names.go does not compile in https://tour.golang.org/basics/3 - pi should be Pi

### ISSUE THREAD

**Issue by obriensystems** [golang/tour#149]
https://tour.golang.org/basics/3

exported-names.go
does not compile because pi should be case-sensitive Pi
The code is a year old in 
https://github.com/golang/tour/blob/master/content/basics/exported-names.go

```
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.pi)
}

```

tmp/sandbox738342399/main.go:9: cannot refer to unexported name math.pi
tmp/sandbox738342399/main.go:9: undefined: math.pi

**Comment by obriensystems** [comment]
My mistake, read further - the error is a teaching exercise - sorry

**Comment by obriensystems** [comment]
This is the fastest turnaround I have ever seen on an open source project (literally seconds)

**Comment by adg** [comment]
We try. :-)
