### ISSUE TITLE
tour: confusing typo

### ISSUE THREAD

**Issue by David-Essaadi** [golang/tour#1492]
Context: https://go.dev/tour/basics/7

**Naked return statements** should be used only in short functions, as with the example shown here. They can harm readability in longer functions. 

I believe this should be **Named return statements** instead. Currently it seems confusing to me (are named parameters good or bad in longer functions)

**Comment by crisman** [comment]
Two different items, **named return values** allow for **naked return statements**, but does not require it.

At the top of `split2` are the **named return values** `ones_digit, high_digits int`.

The **naked return statement** is just `return`. It would return the same values if written in a non-naked form:

        return ones_digit, high_digits

In the slide text, the first two paragraphs say **named return values** are good and should be used.

The second two paragraphs say **naked return statements** are available and may cause confusion if the function is long enough that is not easy to see both the top and bottom of the function at the same time.

I think the text is correct as it is.

**Comment by David-Essaadi** [comment]
I see, thanks for clearing that up. I see the text now explains what "naked" return statements are.
