### ISSUE TITLE
tour: Slices: slicing a particular range of an array does not work

### ISSUE THREAD

**Issue by peterwhy** [golang/tour#150]
Context: https://tour.golang.org/moretypes/7

Code: https://play.golang.org/p/wdLUlXigcv
Expected: [3, 5, 7, 11, 13]

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by zakora** [comment]
Your code run as expected if I run it.

That is
```go
package main

import "fmt"

func main() {
	primes := [6]int{2, 3, 5, 7, 11, 13}

	var s []int = primes[1:6]
	fmt.Println(s)
}
```
outputs
```
[3 5 7 11 13]
```
