### ISSUE TITLE
tour: [typo in paragraph]

### ISSUE THREAD

**Issue by litmanhuang** [golang/tour#1510]
Context: https://go.dev/tour/moretypes/1

in the paragraph, 

i := 42
p = &i

There seems to be a missing ":" before the second "=". To verify it, I tried to ommit the semicolon and run the programme. It gave syntax error on line 8: "undefined p". So it seems that it should be 

i := 42
p := &i

**Comment by crisman** [comment]
It works correctly, but the first code block on the screen:

```go
var p *int
```

is required for the second to work:

```go
i := 42
p = &i
```

you will then need something that uses `p`, simple example:

```go
fmt.Println(p)
```

Running example: https://go.dev/play/p/3dBSlhvcGpM

**Comment by litmanhuang** [comment]
Thank you for the correction! I shouldn't read the first and second blocks seperately. 
I am closing the issue now.
