### ISSUE TITLE
tour: "go tool tour" doesn't seem to work now?

### ISSUE THREAD

**Issue by seebs-markley** [golang/tour#153]
Context: https://tour.golang.org/welcome/3

$ go version
go version go1.7.4 darwin/amd64
$ go tool tour
go tool: no such tool "tour"

**Comment by subbu05** [comment]
go version
go version go1.7.5 darwin/amd64
go tool tour
go tool: no such tool "tour"

**Comment by alebaffa** [comment]
`go too tour` is now available in go1.8. This issue can be closed.

**Comment by lengocgiang** [comment]
Just try
`gotour`

**Comment by bgadrian** [comment]
Go tour install issues, duplicate of #8, probably [this comment](https://github.com/golang/tour/issues/8#issuecomment-306527940) is what are you looking for.

**Comment by ALTree** [comment]
Closing as a dup of #8.
