### ISSUE TITLE
tour: guide indicates that error should be present in code, but code is correct

### ISSUE THREAD

**Issue by jonbrenner** [golang/tour#154]
Context: https://tour.golang.org/basics/3

> Run the code. Notice the error message.

> To fix the error, rename math.pi to math.Pi and try it again.

Pre-populated code window contains the correct usage of math.Pi:
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.Pi)
}
```

**Comment by zakora** [comment]
The pre-populated code window contains the erroneous code for me.

It looks like the Go Tour keeps the changes done locally, so you might have the correct code from a previous edit.

**Comment by jonbrenner** [comment]
> It looks like the Go Tour keeps the changes done locally, so you might have the correct code from a previous edit.

You are correct. I confirmed that it is consistent with the directions in an incognito tab. Closing.
