### ISSUE TITLE
tour: [Provide explicit description for how ranges work]

### ISSUE THREAD

**Issue by JESii** [golang/tour#155]
Context: https://tour.golang.org/moretypes/7

Unlike some other languages, the go-lang range for slices includes the starting point but excludes the ending point. For example, ruby has a range type which, in the usual case [1..4] includes both endpoints; to exclude the right endpoint, it's written as [1...4]. It would be good to explicitly call this out... especially for novice users.

And now I see from the blog entry that you call this a 'half-open' range; at least now defined. I think this should be in the lesson.

**Comment by ALTree** [comment]
This is the slide now:

> This selects a half-open range which includes the first element, but excludes the last one. 

So this is fixed, I believe. Closing here.
