### ISSUE TITLE
tour: [time on remote server is wrong (Tuesday instead Saturday)]

### ISSUE THREAD

**Issue by akhasano** [golang/tour#1555]
Context: https://go.dev/tour/flowcontrol/10

Change the title above to describe your issue and add your feedback here, including code if necessary

I run it in Saturday, (i made `fmt.Println(today)` after "When's Saturday?")
---
When's Saturday?
Tuesday
Too far away.
---
It looks like wrong time in server.

**Comment by ALTree** [comment]
As explained in the notes:

>  Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader.
