### ISSUE TITLE
No example code in go tour page.

### ISSUE THREAD

**Issue by ingram10** [golang/tour#1560]
Context: https://go-tour-ua-translation.lm.r.appspot.com/methods/2

There is no example code there.
![image](https://github.com/golang/tour/assets/8005125/044ed47b-e49b-4a46-b73f-61429384c0ae)

**Comment by ALTree** [comment]
The translations are not maintained or controlled by the Go Project, please report the issue to the ua tour translator. Closing here since we cannot change externally hosted translations.
