### ISSUE TITLE
tour: [Wrong example for explanation]

### ISSUE THREAD

**Issue by Kachyr** [golang/tour#1564]
Context: https://go-tour-ua-translation.lm.r.appspot.com/basics/3

In Ukrainian version of "Tour of Go" explanation doesnt fit example.
In eng version everithing is OK

UA:
![image](https://github.com/golang/tour/assets/56648514/4948ac45-5817-4b77-9ebf-12ec3188301d)
ENG:
![image](https://github.com/golang/tour/assets/56648514/445cf588-cb1f-4db1-9a4a-8f52648269b2)

**Comment by ALTree** [comment]
The translations are not maintained or controlled by the Go Project, please report the issue to the ua tour translator. Closing here since we cannot change externally hosted translations.
