### ISSUE TITLE
tour: Compilation doesn't produce the expected output

### ISSUE THREAD

**Issue by orussmann** [golang/tour#1577]
Context: https://go.dev/tour/basics/6

When pressing ctrl + enter, the text "Wating for remote server..." appears briefly (for less than a second) where the expected output of (in this step) "world hello" should be.

This doesn't only happen at this step/ exercise.

Browser: Chrome Version 120.0.6099.225 (Official Build) (64-Bit)

**Comment by ALTree** [comment]
Probably a temporary issue, it's working now.
