### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by denys-badass** [golang/tour#1583]
Context: https://go-tour-ua-translation.lm.r.appspot.com/flowcontrol/1

"У мові є Go тільки одна конструкція циклу - for."
This is not quite the right sentence
It would be more correct to say:
"У мові GO є ..."

**Comment by ALTree** [comment]
The tour translations are not maintained by the Go Project, please report the issue to the ua translation. Closing here since we can't fix this.
