### ISSUE TITLE
tour: typo in code snippet

### ISSUE THREAD

**Issue by RasulIslyamgali** [golang/tour#1594]
Context: https://go.dev/tour/list

into page https://go.dev/tour/moretypes/15 
there are below code snippet:
```go
func append(s []T, vs ...T) []T
```

i want to propose below code snippet, in which used "elems" instead "vs"
```go
func append(s []T, elems ...T) []T
```

**Comment by ALTree** [comment]
I think `vs` in fine, the point is just to show the signature of the function.
