### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by dmytroiva** [golang/tour#1603]
Context: https://go-tour-ua-translation.lm.r.appspot.com/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary
Maybe accidentally added the links for code snippets `rand. Seed` and `time. Now`. I think there shoudln't be links 
Щоб побачити інші числа, потрібно встановити сид для генерації (дивіться [rand.Seed](https://go-tour-ua-translation.lm.r.appspot.com/basics/pkg/math/rand/#Seed)). В цьому середовищі час не змінюється, тому для встановлення сиду вам потрібно використовувати щось інше замість [time.Now](https://go-tour-ua-translation.lm.r.appspot.com/basics/pkg/time#Now).

**Comment by ALTree** [comment]
The tour translations are not maintained by the Go Project, please report the issue to the ua translation. Closing here since we can't fix this.
