### ISSUE TITLE
tour: could you have possibly used the wrong formula?

### ISSUE THREAD

**Issue by noambenyo** [golang/tour#161]
Context: http://127.0.0.1:3999/flowcontrol/8

Change the title above to describe your issue and add your feedback here, including code if necessary

I think the formula is sqrt(N) ≈ ½(N/A + A), so 

Zn+1=½(X/Zn +Zn)
See http://www.school-for-champions.com/algebra/square_root_approx.htm#.WJiO-Y9OKUk

**Comment by ALTree** [comment]
General form of newton is `x_{n+1} = x_n - ( f(x_n) / f'(x_n) )`, which is closely mirrored in the tour exercise. It can be re-ordered to look different, but the tour's version is still correct. Closing here.
