### ISSUE TITLE
tour: rand.Seed produces error.

### ISSUE THREAD

**Issue by rmustard** [golang/tour#163]
Context: https://tour.golang.org/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary

It's unclear how to use rand.Seed to generate a truly random number. 
rand.Seed(10) -> error
rand.Intn(rand.Seed) -> error
rand.Seed -> produces a hex value

**Comment by crisman** [comment]
`rand.Seed(10)` works for me and updates the favorite number from 1 to 4. You need to seed the rand system before you call rand.Intn:
`func main() {
    rand.Seed(10)
    fmt.Println("My favorite number is", rand.Intn(10))
}
`

**Comment by robphoenix** [comment]
I believe @crisman has answered this. If this is no longer an issue would you consider closing it @rmustard? Thanks!

**Comment by robphoenix** [comment]
@adg I believe this issue can be closed.

**Comment by rooton** [comment]
It totally frustrating.

rand.Seed(10)
    fmt.Println("My favorite number is", rand.Intn(10))

Shows the number every time I run app.
What I do wrong?

**Comment by adg** [comment]
@rooton if you give a random number generator the same seed then it will always give you the same number. Change the seed and you get a different number.

**Comment by phffmn** [comment]
So to use rand.Seed to get a random number in rand Intn you have to provide rand.Seed with a random number?

Who thought this example would be a good first start in the tour?
