### ISSUE TITLE
tour: printing the output in a confusing order

### ISSUE THREAD

**Issue by anilgkurian** [golang/tour#164]
Context: https://tour.golang.org/moretypes/5

In this sample program the variables are declared in following order - v1,v2,v3 and then p
	v1 = Vertex{1, 2}  // has type Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
	p  = &Vertex{1, 2} // has type *Vertex

But output is printed in a different order, causing a confusion - v1, p , v2 and then v3.
	fmt.Println(v1, p, v2, v3)

**Comment by robphoenix** [comment]
I would guess that they are printed to stdout this way to highlight the comparison between the struct `Vertex` and the pointer to the struct `*Vertex`.

**Comment by adg** [comment]
Correct. Thanks @robphoenix
