### ISSUE TITLE
tour: golang tour is not installed by default

### ISSUE THREAD

**Issue by onnimonni** [golang/tour#165]
Context: https://tour.golang.org/welcome/3

It should note that if the local version doesn't work running these commands will help:
```
$ go get golang.org/x/tour/gotour
$ gotour
```

**version:**
```
$ go version
go version go1.7.4 darwin/amd64
```

**Comment by robphoenix** [comment]
This is a duplicate of https://github.com/golang/tour/issues/8

If you feel your issue is addressed there please consider closing this, thanks!

**Comment by onnimonni** [comment]
Thanks!
