### ISSUE TITLE
tour: markup problem, and wrong link to open issue.

### ISSUE THREAD

**Issue by Grogdunn** [golang/tour#167]
context: https://go-tour-ita.appspot.com/methods/14

in italian version ```_interfaccia vuota_``` is not interpreted as " interfaccia vuota"

and the "buglink" on top of the page lead to golang/go insted of golang/tour.

**Comment by ALTree** [comment]
We don't control, write, or deploy the tour translation; you should write to the author of the italian version for this. Closing here.
