### ISSUE TITLE
tour: The description for "Test the same function" is false or my Walk is wrong?

### ISSUE THREAD

**Issue by nothize** [golang/tour#172]
Context: https://tour.golang.org/concurrency/8

If tree.New(1) is random, "Same(tree.New(1), tree.New(1)) should return true" should be false unless both trees are identical by probability. However, I'm not sure is that my implementation of Walk is wrong or the description is wrong.

Original statement:

> 4. Test the Same function.
> 
> Same(tree.New(1), tree.New(1)) should return true, and Same(tree.New(1), tree.New(2)) should return false.

Code that dumps the comparison of two tree.New(1):

`package main

import (
	"golang.org/x/tour/tree"
	"fmt"
)

// Walk walks the tree t sending all values
// from the tree to the channel ch.
func Walk(t *tree.Tree, ch chan int) {
	ch <- t.Value
	if t.Left != nil {
		Walk(t.Left, ch)
	}
	if t.Right != nil {
		Walk(t.Right, ch)
	}
}

// Same determines whether the trees
// t1 and t2 contain the same values.
func Same(t1, t2 *tree.Tree) bool {
	c1 := make(chan int)
	c2 := make(chan int)
	go Walk(t1, c1)
	go Walk(t2, c2)
	match := true
	for i := 0; i < 10; i++ {
		if a,b:=<-c1,<-c2; a != b {
			fmt.Printf("a:%d b:%d\n", a, b)
			match = false
		} else {
			fmt.Printf("a:%d b:%d\n", a, b)
		}
	}
	return match
}

func main() {
	t1 := tree.New(1)
	t2 := tree.New(1)
/*
	ch := make(chan int)
	go Walk(t1, ch)
	fmt.Printf("%d\n", <-ch)
*/
	fmt.Println(Same(t1, t2))
}
`
Output:

a:10 b:7
a:5 b:4
a:3 b:2
a:1 b:1
a:2 b:3
a:4 b:5
a:7 b:6
a:6 b:9
a:9 b:8
a:8 b:10
false

**Comment by ALTree** [comment]
"The same" means that they are binary tree with the same elements in it. They may be in different nodes, but if both the trees have the numbers from 1 to 10 they are equal. This is working as intended.
