### ISSUE TITLE
tour: broken code execution

### ISSUE THREAD

**Issue by apotheon** [golang/tour#176]
Context: http://127.0.0.1:3999/flowcontrol/1

I installed the Go tour with "go get".  On this page, which should produce "10" as outpout, it instead procudes "45".

**Comment by andrewchambers** [comment]
https://play.golang.org/p/nL6x3HqjAd

**Comment by andrewchambers** [comment]
I think you misread, its += i, not += 1

**Comment by apotheon** [comment]
Oops.  My mistake.  Sorry about that.
