### ISSUE TITLE
tour: Exported names

### ISSUE THREAD

**Issue by asgs** [golang/tour#178]
Context: https://tour.golang.org/basics/3

The example says that lower-cased names are not exported, so it asks to try importing math.pi instead of math.Pi to see the compiler error.

But for the beginner to grasp this further, you should ask to try them import something that actually exists which is not exported. E.g. in math, there's no "pi", only "Pi". If we could add an example, where there are lowered-case names, it would make even more sense to understand "exports".

**Comment by ahartoto** [comment]
Didn't check when the page was last updated, but I noticed that the page now says:
```
Run the code. Notice the error message.
```

But the page didn't have any error (since it's already using `math.Pi`). So, I think that's something that we need to update.

**Comment by asgs** [comment]
@ahartot IIRC, the page does show the lowercase `pi`. maybe you already corrected it to `Pi` and reopened the page. Browser storage *might* be in play here

**Comment by bgadrian** [comment]
> you should ask to try them import something that actually exists which is not exported.
It would be problematic for more reasons I think
* the internal/private structure of a library can change at any time, so the reference may not be valid
* in order for the user to see that it exists we have to send them to an external page, that involves golang sources, which will lead to a lot of info to handle for a rookie.

**Comment by ALTree** [comment]
> in  order for the user to see that it exists we have to send them to an  external page, that involves golang sources, which will lead to a lot of  info to handle for a rookie.

I agree that we shouldn't depend on unexported but existent names in the standard library in a simple tour lesson.

I believe this is sufficiently clear, and that it would be hard to make it clearer without complicating it, so I'm closing this issue.
