### ISSUE TITLE
tour: fmt.Println(math.pi) should be fmt.Println(math.Pi)

### ISSUE THREAD

**Issue by revant** [golang/tour#188]
Context: https://tour.golang.org/basics/3

```
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.pi)
}
```
To be changed to 
```
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.Pi)
}
```

**Comment by robphoenix** [comment]
This is deliberate. It illustrates the difference between exported and unexported names. The idea is to get an error as `pi` is not exported, and when changed to `Pi`, which is exported, the error goes away.

From the page you link to:
> To fix the error, rename math.pi to math.Pi and try it again.

Hope this helps with your issue @revant. If it does, please consider closing this, thanks!
