### ISSUE TITLE
User is able to reassign constant. 

### ISSUE THREAD

**Issue by bernstein7** [golang/tour#190]
Context: https://tour.golang.org/basics/15
```
package main

import "fmt"

const Pi = 3.14

func main() {
	const World = "世界"
	fmt.Println("Hello", World)
	Pi := 2.3
	fmt.Println("Happy", Pi, "Day")

	const Truth = true
	fmt.Println("Go rules?", Truth)
}
```

```
Hello 世界
Happy 2.3 Day
Go rules? true
```

Is it ok?

**Comment by bgadrian** [comment]
I think the text is misleading, but you are not re declaring the constant Pi at the package level, 
you are creating a new variable, with the same name but with a different scope (main function). 

`
	func() {
		Pi := 5
		fmt.Println("Happy", Pi, "Day")
	}()
`
You can add this snippet inside the main function and it will create another Pi variable, but in another scope.

**Comment by ALTree** [comment]
Yep, this is how the language works. Closing here.
