### ISSUE TITLE
Fibonacci doesn't start with 0

### ISSUE THREAD

**Issue by changyuheng** [golang/tour#205]
Created a PR [here](https://go-review.googlesource.com/c/41496/).

**Comment by NathanZook** [comment]
https://www.mathsisfun.com/numbers/fibonacci-sequence.html
https://en.wikipedia.org/wiki/Fibonacci_number
Note that in wikipedia, the 0-start sequence is referred to as modern.  Think of the 1-start sequence as COBOL, and the 0-start as C.

Please withdraw issue & pr.

**Comment by changyuheng** [comment]
Hi @NathanZook, it doesn't matter which sequence is more modern and which one is also acceptable.

So this is the original exercise:

> Implement a fibonacci function that returns a function (a closure) that returns successive fibonacci numbers (0, 1, 1, 2, 3, 5, ...).

As the question is already indicating which kind of sequence the answer should be, the current answer is just not 100% correct.
