### ISSUE TITLE
tour: [ERSETZE MIT EIGENER BESCHREIBUNG]

### ISSUE THREAD

**Issue by MattiSchnurbusch** [golang/tour#206]
Kontext: https://go-tour-de.appspot.com/flowcontrol/1

Typo in the explanation:
Merke: Anders als in C, Java **der** Javascript gibt es keine runden Klammern um die drei oben genannten Komponenten, dafür müssen die { } zwingend gesetzt werden.

-> the der should be oder

**Comment by michivo** [comment]
fixed in go-tour-de, der is now oder.

**Comment by ALTree** [comment]
Fixed, so I'm closing here.
