### ISSUE TITLE
tour: tree.New(1) called twice produces two different trees

### ISSUE THREAD

**Issue by lwhalen** [golang/tour#208]
Context: https://tour.golang.org/concurrency/8

When attempting this exercise, I was unable to get the trees to compare as identical when calling Same(tree.New(1), tree.New(1))

The code for Tree, even when called with the same parameters, uses rand.Perm(10), which produces two different trees when called in succession.

To get my trees to compare I needed to use the following code

func main() {
	tree1 := tree.New(1)
	//tree2 := tree.New(2)
	
	if (Same(tree1, tree1)) {
		fmt.Println("The trees are the same!")
	} else {
		fmt.Println("The trees are different.")
	}
	
}

Not a very enlightening test, but I am not sure how long it would take generating random trees until I got two identical trees.

To illustrate this point, the code below evaluates as different trees, even though tree1 and tree2 are generated using the same parameter.

func main() {
	tree1 := tree.New(1)
	tree2 := tree.New(1)
	
	if (Same(tree1, tree2)) {
		fmt.Println("The trees are the same!")
	} else {
		fmt.Println("The trees are different.")
	}
	
}

**Comment by NathanZook** [comment]
Works as intended.

**Comment by pavlodvornikov** [comment]
@NathanZook can you please explain your point of view ? Because I am also confused about this exercise.

It says that:
**Same(tree.New(1), tree.New(1)) should return true, and Same(tree.New(1), tree.New(2)) should return false.**
But following example shows that two trees generated in the proposed method are not the same:
```
package main

import (
	"fmt"

	"golang.org/x/tour/tree"
)

func Same(t1, t2 *tree.Tree) bool {
	fmt.Println(t1.Value, t2.Value)
	return t1.Value == t2.Value
	
}

func main() {
	fmt.Println(Same(tree.New(1), tree.New(1)))
}
```
The result is:
```
10 7
false
```
Does not matter if I run it on localhost or on https://tour.golang.org

**Comment by ALTree** [comment]
It's a binary tree. The value at the root can be different even if the tree contains the same values. For example, take this two binary tree with values 1, 2, 3 in them:

```
    2
  /   \
 1     3
```
```
3
  \
    2
     \
      1
```

If you implement `Same` by looking at the root, they looks different. But the goal of the exercise is to decide whether the trees *contains the same values*. You'll need to walk them to find out.
