### ISSUE TITLE
tour: Better explanation of "high-precision values"

### ISSUE THREAD

**Issue by Uplink03** [golang/tour#210]
Context: https://tour.golang.org/basics/16

The sample code shows two constants and explains that Small should be 2 - and that makes sense from a math point of view. Yet, when the code runs it gets really weird fast:

```
needInt(Small) == 21
needFloat(Small) == 0.2
```

Why do these numbers come up?

**Comment by NathanZook** [comment]
Because of that `needInt` and `needFloat` do.  Please close.

**Comment by Uplink03** [comment]
Oh man... This is embarassing. I didn't have enough attention span to notice that those two functions were operating on the value.
