### ISSUE TITLE
tour: [typo in description]

### ISSUE THREAD

**Issue by adam-szczombrowski** [golang/tour#215]
Context: https://tour.golang.org/basics/11

The last statements is: When you need an integer value you should use int unless you have a specific reason to use a `sized` or unsigned integer type. Should be `signed` instead of `sized`.

**Comment by robphoenix** [comment]
This is a duplicate of https://github.com/golang/tour/issues/62
@adam-szczombrowski Would you mind closing this if you feel your issue is covered there? Thanks!

**Comment by adam-szczombrowski** [comment]
@robphoenix yeah sure @robphoenix
