### ISSUE TITLE
tour: code/description mismatch

### ISSUE THREAD

**Issue by code-complete** [golang/tour#217]
Context: https://tour.golang.org/basics/4
"In this example, add takes two parameters of type int"
code
https://yadi.sk/i/yWMoqpvK3HmrAp

**Comment by robphoenix** [comment]
Could you expand on you issue? In the linked code it appears your calling a recursive function an infinite number of times?
What happens, and what do you expect to happen?
Thanks.

**Comment by ALTree** [comment]
Old issue, no answer from OP for >1year, closing here.
