### ISSUE TITLE
tour: Wording may be wrong for number advice

### ISSUE THREAD

**Issue by irazorx1** [golang/tour#219]
Context: http://127.0.0.1:3999/basics/11

This might just be me not understanding the language but shouldn't the following be "..a SIGNED or unsigned.." or is it correct as it is?

"When you need an integer value you should use int unless you have a specific reason to use a sized or unsigned integer type.

**Comment by quentinmit** [comment]
It's correct as is. A sized type would be `int64`, and an unsigned type would be `uint`.
