### ISSUE TITLE
tour: slice of slices

### ISSUE THREAD

**Issue by CostaOnGit** [golang/tour#22]
Context: https://tour.golang.org/moretypes/15 about slice of slices

Samples do not compile (it is maybe the exercise ?)
Slice of slices are authorized by specifications but are more complex to initialize.
Append does not work on an empty slice of slice.
If init is set with 1 element like board := [1][]int then append will work on board[0]
Another solution is to add slice notation to the added element and not the basic type element (0).

In example 15, printSlice cannot work if argument is not set to (s [][]int).

Could you confirm that slice of slices is supported ?
If yes, sample should look like this unless errors are the exercise.
`package main

import "fmt"

func main() {
	var s [][]int
	printSlice(s)

	// append works on nil slices.
	s = append(s, []int{0,})
	printSlice(s)

	// The slice grows as needed.
	s[0] = append(s[0], 1)
	printSlice(s)

	// We can add more than one element at a time.
	s[0] = append(s[0], 2, 3, 4)
	s = append(s,  []int{2, 3, 4,}) //or add a separate slice
	printSlice(s)
}

func printSlice(s [][]int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}`

**Comment by adg** [comment]
This is a language question, not an issue with the tour. Please read golang.org/wiki/Questions
