### ISSUE TITLE
tour: Wrong german translation

### ISSUE THREAD

**Issue by FabianWilms** [golang/tour#220]
Kontext: https://go-tour-de.appspot.com/basics/13

The german translation is wrong in the last line:
`Versuche, das float64 oder das int im Beispiel zu entfernen und den Code auszuführen.`

In the original text it says to remove the `uint` which, of course, is the only useful change here ;-)

**Comment by kytrinyx** [comment]
Thanks @FabianWilms. Would you please report this to the translator at https://github.com/michivo/go-tour-de/issues?

**Comment by michivo** [comment]
I fixed this in go-tour-de, feel free to close this issue.
