### ISSUE TITLE
tour: import "math/cmplx" not needed

### ISSUE THREAD

**Issue by ronaldpetty** [golang/tour#222]
Context: https://tour.golang.org/basics/11

Hi, I am running the example locally and it doesn't seem to need "math/complx".  

```
user@ubuntu:~/go/src/lab01$ cat lab01.go 
package main

import (
  "fmt"
)

var (
  ok bool = false
  maxInt uint64 = 1<<64 - 1
  z complex128 = complex(.5, 14.13)
)

func main() {
  fmt.Printf("Type: %T Value: %v\n", ok, ok)
  fmt.Printf("Type: %T Value: %v\n", maxInt, maxInt)
  fmt.Printf("Type: %T Value: %v\n", z, z)
}
user@ubuntu:~/go/src/lab01$ go run lab01.go 
Type: bool Value: false
Type: uint64 Value: 18446744073709551615
Type: complex128 Value: (0.5+14.13i)
user@ubuntu:~/go/src/lab01$
```

But does in the playground for some reason.

**Comment by robphoenix** [comment]
On line 11 of https://tour.golang.org/basics/11 the `cmplx.Sqrt()` function from the `math/complx` package is being used (https://golang.org/pkg/math/cmplx/#Sqrt) so this package is being imported.

In the code you've pasted above this line has been replaced with `z complex128 = complex(.5, 14.13)` which uses the builtin `complex` function; https://golang.org/pkg/builtin/#complex 
As it is a builtin function nothing needs to be imported to use it.

Hope this helps explain the discrepancy? If it does, would you consider closing the issue? Thanks!

**Comment by ronaldpetty** [comment]
Thanks @robphoenix , not sure why that wasn't clear to me before.
