### ISSUE TITLE
tour: Typo

### ISSUE THREAD

**Issue by azatmurtazin** [golang/tour#223]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

> срез в элементами

**Comment by fouxer** [comment]
'primes' is array
's' is slice of 'primes' array

**Comment by azatmurtazin** [comment]
Я имею ввиду что используется не тот предлог. Вместо "срез в элементами" должно быть "срез с элементами", что соответствует дословному переводу английской версии "slice with elements".

**Comment by fouxer** [comment]
А, ясно. Надо написать, что опечатка )

**Comment by fouxer** [comment]
увидел в заголовке )

**Comment by ALTree** [comment]
We don't maintain or deploy the tour translation, you'll have to report this to the ru tour owner.
