### ISSUE TITLE
Empty/stale issues

### ISSUE THREAD

**Issue by robphoenix** [golang/tour#232]
It's easy for people going through the tour to submit an issue on this repo, which is great. This doesn't however take into consideration people's experience or lack of it, with Github, which it shouldn't. This results in a lot of empty issues on this repo, see https://github.com/golang/tour/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%5BREPLACE%20WITH%20SHORT%20DESCRIPTION%5D
Is there a way @gopherbot can deal with these? Adding a note along the lines of `@<op> can you please update title and description? Thanks`, and adding a label, and then closing after a certain amount of time, indicating the issue is stale? 
We started using https://github.com/probot/stale over at https://github.com/exercism

**Comment by robphoenix** [comment]
p.s. apologies if `@` maintainers is not the best way to go about closing these issues, is there a preferred way to communicate stale issues?

**Comment by adg** [comment]
Thank you so much for doing so much weeding in the issue tracker. :-)

To make it easier, maybe I could just give you access to edit/close issues?

> Is there a way @gopherbot can deal with these? 

Perhaps even preferable would be for the tour page to provide its own issue report form, and have it not file issues when the report is empty.

cc @campoy @broady

**Comment by robphoenix** [comment]
No worries, more than happy to help.

> To make it easier, maybe I could just give you access to edit/close issues?

Sure, :+1:

**Comment by adg** [comment]
@robphoenix I think I've done this now. Let me know if it didn't work.

**Comment by robphoenix** [comment]
@adg Thanks. As far as I can see I don't have any permissions on this repo, it looks like I have some *pull* permissions on the main `go` repo, though no access to edit/close issues.

**Comment by robphoenix** [comment]
Closing this issue, as the main point has been addressed by @kytrinyx  in https://github.com/golang/tour/issues/235
