### ISSUE TITLE
At least mention goimports with gofmt

### ISSUE THREAD

**Issue by NathanZook** [golang/tour#234]
https://github.com/golang/go/wiki/CodeReviewComments#imports mentions goimports as an alternative.  But I am assured that "everyone" is using it.  As the tour is explicitly aimed at newbies, this feels like a big deal.

**Comment by ALTree** [comment]
The tour is focused on the core language itself, I don't think it would be terribly useful to mention developer tools. There are other documents that explain how to setup a Go programming environment. Closing here.
