### ISSUE TITLE
Autoclose issues containing boilerplate?

### ISSUE THREAD

**Issue by kytrinyx** [golang/tour#235]
@adg @broady @campoy I wrote a small bot that would add a comment and automatically close [the issues][boilerplate-issues] where people have left the default values from https://github.com/golang/tour/blob/master/static/js/values.js#L53-L54 in place.

Here's an example https://github.com/kytrinyx/banana-cream-pie/issues/3

Would you be interested in running the bot on this repo? If so, we would need to update the canned reply (I'm not great at diplomatically closing things) and get the bot deployed somewhere (presumably Heroku—since that's straight forward and I know how).

[boilerplate-issues]: https://github.com/golang/tour/issues?q=is%3Aissue+in%3Atitle+%5BREPLACE+WITH+SHORT+DESCRIPTION%5D

**Comment by adg** [comment]
That sounds good to me. What's required on our end, besides amending the close message? Some permissions I assume.

I think the message is fine, but I'd add to the beginning:

> Thanks for your issue report, but unfortunately you haven't told us what the problem was.

**Comment by kytrinyx** [comment]
Cool, thanks, I'll update the text.

I need to deploy this somewhere (Heroku, presumably), then I'll give you a link to install the bot on the repo. When installing you will have to agree to the permissions, which in this case are read/write on issues.

**Comment by adg** [comment]
Sounds good, thanks Katrina! :-)

**Comment by kytrinyx** [comment]
@adg it's deployed and can be installed from https://github.com/apps/tourbo-gopher

**Comment by adg** [comment]
Sweet, it works! Thanks @kytrinyx!

https://github.com/golang/tour/issues/236#issuecomment-310264101

**Comment by broady** [comment]
super nice! @kytrinyx - how do you create installable bots like that?

**Comment by kytrinyx** [comment]
@broady Yepp—this is the new "GitHub App" thing. They have been available in beta for about 8 months now, and were just officially released last month.

**Comment by robphoenix** [comment]
There appears to be a bug with the bot https://github.com/golang/tour/issues/240
