### ISSUE TITLE
wrong day 

### ISSUE THREAD

**Issue by haggucan** [golang/tour#237]
Context: https://tour.golang.org/flowcontrol/10

The day that I ran the code was Friday but code block shows as Tuesday. Wrong server time  ?

**Comment by robphoenix** [comment]
Sorry @haggucan This issue was closed due to a bug in the tourbo-gopherbot.

The issue you're seeing is due to how the tour is run, I don't know the details but the environment in which these programs are executed is deterministic, so it's always Tuesday in the tour. :smile:

**Comment by haggucan** [comment]
@robphoenix 
Thanks for the reply mate :)
