### ISSUE TITLE
tour: math.pi is undefined

### ISSUE THREAD

**Issue by tamakiii** [golang/tour#238]
Context: https://tour.golang.org/basics/3

~~~sh
❯ go version
go version go1.8.3 darwin/amd64

❯ go run exported-names.go
# command-line-arguments
./exported-names.go:9: cannot refer to unexported name math.pi
./exported-names.go:9: undefined: math.pi

❯ cat exported-names.go
package main

import (
  "fmt"
  "math"
)

func main() {
  fmt.Println(math.pi)
}
~~~
~~~diff
-   fmt.Println(math.pi)
+   fmt.Println(math.Pi)
~~~

**Comment by robphoenix** [comment]
Sorry @tamakiii This issue was closed due to a bug in the tourbo-gopherbot.

I believe though that the issue you're seeing is because `math.pi` should be `math.Pi` (note the capitalisation of Pi). This is a deliberate error to highlight the difference between exported and unexported names.

**Comment by tamakiii** [comment]
@robphoenix Thank you for your reply, and sorry about that I gave up issuing (for keep learning go forward).

> I believe though that the issue you're seeing is because math.pi should be math.Pi

Exactly. And I've got that this is a deliberate error. Thank you!
