### ISSUE TITLE
tour: calling rand.Intn without seeding the generator results in a non random number

### ISSUE THREAD

**Issue by pappes** [golang/tour#239]
Context: https://tour.golang.org/basics/1

I know this make the example more complex but it allows the user to run the example multiple times and get a differnt number each time..

func init() {
	rand.Seed(time.Now().UTC().UnixNano())
}

func main() {
	fmt.Println("My favorite number is", rand.Intn(20))
}

**Comment by pappes** [comment]
How do I reopen this issue?

**Comment by robphoenix** [comment]
@pappes When you comment there should be a white `reopen issue` button next to the green `comment` button.

Though I think this issue is addressed by https://github.com/golang/tour/commit/d844dc7a157c5d2e92bccc9732530c37bc7ef33b
