### ISSUE TITLE
Just checking this is working properly

### ISSUE THREAD

**Issue by robphoenix** [golang/tour#240]
Context: https://tour.golang.org/welcome/1

I've seen a couple of issues closed by the tourbo-gopher that I'm not sure should have been, so I'm just checking my suspicion....

https://github.com/golang/tour/issues/238
https://github.com/golang/tour/issues/239
https://github.com/golang/tour/issues/237

**Comment by robphoenix** [comment]
@kytrinyx @adg This issue was never actually opened, tourbo-gopherbot appears to be closing all issues automatically. I'm also not able to re-open it.

**Comment by kytrinyx** [comment]
Ouch! I'll take the bot offline right now.

**Comment by kytrinyx** [comment]
It should be turned off now.

**Comment by robphoenix** [comment]
Fixed https://github.com/kytrinyx/golang-tour-boilerplate-responder/commit/5e5c1fec2c1c654456b1a9d29803c54c19dd99ea
