### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by VascudoCrisis** [golang/tour#241]
Context: https://tour.golang.org/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary

output rnd is always 1

**Comment by VascudoCrisis** [comment]
rand.Intn(10) always returns 1

**Comment by robphoenix** [comment]
from the page you link to:

> Note: the environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed.)
