### ISSUE TITLE
tour: Error comunication

### ISSUE THREAD

**Issue by maxtar** [golang/tour#242]
Context: https://tour.golang.org/flowcontrol/8

Change the title above to describe your issue and add your feedback here, including code if necessary
I try execute the following code:
```golang
package main

import (
	"fmt"
	"math"
)

func Sqrt(x float64) float64 {
	//z := 1.0
	/*for i := 0; i < 10; i++ {
		z = z - ((z*z - x) / 2 * z)
	}*/
	return 2
}

func main() {
	//fmt.Println(Sqrt(2))
	fmt.Println(math.Sqrt(2))
}
And got 
```
Error communicating with remote server.
Program exited.
```
```

**Comment by robphoenix** [comment]
This will have been a network error of some sort. This happens sometimes with the go tour, and the go playground as well. It's not an issue with the sites themselves, rather a temporary communication error between the tour and the server running the Go environment.
Your code runs fine on the tour, if you keep trying it should run. 

If this resolves your issue, please consider closing it, thanks! @maxtar @adg

**Comment by maxtar** [comment]
@robphoenix Ok, thanx. It works for now. I've tried yesterday some code but only this has getted error. :)
