### ISSUE TITLE
tour: foreign versions broken or unavailable

### ISSUE THREAD

**Issue by molivier** [golang/tour#25]
I notice the french version of Golang Tour returns empty response when executing code. I try [other languages](https://tour.golang.org/welcome/2) and found other "broken" versions:

### What did you do?

Run Hello.go

### What did you expect to see?

A correct output :

````
Hello, 世界

Program exited.
````
### What did you see instead?

An empty response:

````
Program exited.
````

### Summary

| Language        | Code execution | Available |
| ------------- |:-------------:| :-----:|
|Brazilian Portuguese — Português do Brasil|ok |ok |
|Catalan — Català|	ok| ok|
|German — Deutsch| **FAIL**| ok|
|Spanish — Español|ok |ok |
|French — Français| **FAIL**| ok|
|Indonesia — Bahasa|ok |ok |
|Italian — Italiano|ok |ok |
|Hebrew — עִבְרִית|ok |ok |
|Japanese — 日本語|ok |ok |
|Korean — 한국어|ok |ok |
|Romanian — Română|ok |ok |
|Simplified Chinese — 中文（简体）|ok |ok |
|Traditional Chinese — 中文（繁體）|ok |ok |
|Ukrainian — Українська| **FAIL**| ok |
|Uzbek — Ўзбекча|**FAIL** |ok |
|Turkish - Türkçe|**FAIL** | **FAIL**|

The turkish domain isn't resolving.

**Comment by adg** [comment]
This is a dupe of #15693
