### ISSUE TITLE
tour: nonchalant reference to `type` keyword that was not mentioned before

### ISSUE THREAD

**Issue by Habbie** [golang/tour#252]
Context: https://tour.golang.org/moretypes/2

This page says "(And a `type` declaration does what you'd expect.)" but as far as I can see the `type` keyword was mentioned zero times before this in the tour.

On rereading a few times maybe this was not meant as a reference to earlier mentions of `type` but I feel "what you'd expect" is optimistic here. I certainly was confused for a while, and I doubt that's the goal of the tour.

**Comment by ALTree** [comment]
Yep, but this is #121. Closing this as a dup.
