### ISSUE TITLE
tour: wrong result in Appending to a slice example

### ISSUE THREAD

**Issue by iamelru** [golang/tour#258]
Context: https://tour.golang.org/moretypes/15

line 11 returns (and this breaks our brains)
`len=1 cap=2 [0]`
but it actually returns 
`len=1 cap=1 [0]`
if you run example code locally

**Comment by ALTree** [comment]
This is an implementation detail. The result is different because the playground environment is 32 bit while your system is likely 64 bits. Closing here since it's working as intended.
