### ISSUE TITLE
tour:  weird order of results 

### ISSUE THREAD

**Issue by iamelru** [golang/tour#259]
Context: https://tour.golang.org/methods/18

Somehow we are getting random order of result lines,
its either google and then loopback or loopback and then google. 

If we run code locally, its all good and loopback is always a first line.

**Comment by ChristianWitts** [comment]
> [Docs](https://golang.org/ref/spec#RangeClause) - The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next. If map entries that have not yet been reached are removed during iteration, the corresponding iteration values will not be produced. If map entries are created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next. If the map is nil, the number of iterations is 0. 

Maps are not guaranteed to be ordered, and [Hash Function Randomisation](https://github.com/golang/go/issues/2630) was also introduced for security.

**Comment by iamelru** [comment]
So its a pure luck that result was always the same in browser, and same but opposite when running locally. Okay, thank you, Christian!

**Comment by robphoenix** [comment]
@iamelru if @ChristianWitts answer has dealt with your issue, please consider closing, thanks!

**Comment by iamelru** [comment]
I was pretty sure i did close it. Sorry, and thank you!
