### ISSUE TITLE
tour: output shows Google first and Bell Labs second

### ISSUE THREAD

**Issue by dwightlinwrite** [golang/tour#26]
Context: https://tour.golang.org/moretypes/21

Change the title above to describe your issue and add your feedback here, including code if necessary

Hi, why does the output of the map-literals-continued.go show "Google" is the first element, and "Bell Labs" the second?

map[Google:{37.42202 -122.08408} Bell Labs:{40.68433 -74.39967}]
with Vertex the type omitted.

It's different from my laptop, which shows:
map[Bell Labs:{40.68433 -74.39967} Google:{37.42202 -122.08408}]

In map-literals.go, your code shows
map[Bell Labs:{40.68433 -74.39967} Google:{37.42202 -122.08408}]
with Vertex as the type shown in the code.

Dwight

**Comment by adg** [comment]
Because map iteration order is random.
