### ISSUE TITLE
tour: correctly verbalise the sentence

### ISSUE THREAD

**Issue by sahajRe** [golang/tour#262]
Context: https://tour.golang.org/flowcontrol/5

The description on the above tour page

> Go's if statements are like its for loops; the expression need not be surrounded by parentheses ( ) but the braces { } are required.

The current sentence looks confusing due to reference to `for` loop. It can be better verbalised without any reference to it. For example,

Go's if statement expression need not be surrounded by parentheses `( )` but the braces `{ }` are required.

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by robphoenix** [comment]
Sorry @sahajRe this was closed accidentally. Thanks for your suggestion.
