### ISSUE TITLE
tour: confusing verbalisation in if description

### ISSUE THREAD

**Issue by sahajRe** [golang/tour#263]
I am using online go tour on MacOS. Context: https://tour.golang.org/flowcontrol/5. I would like to suggest improvement in the description on this page.

The description on the above tour page is

> Go's if statements are like its for loops; the expression need not be surrounded by parentheses ( ) but the braces { } are required.

The current sentence looks confusing due to reference to `for` loop. It can be better verbalised without any reference to it. For example,

Go's if statement expression need not be surrounded by parentheses `( )` but the braces `{ }` are required.

Can you please re-verbalise the if description?

**Comment by ALTree** [comment]
I think it's fine. It references the `for` loops because they were the topic of the previous slide. Closing here.
