### ISSUE TITLE
tour: Slice defaults

### ISSUE THREAD

**Issue by llousada** [golang/tour#265]
Context: http://127.0.0.1:3999/moretypes/10

func main() {
	s := []int{2, 3, 5, 7, 11, 13}

	s = s[1:4]
	fmt.Println(s)

	s = s[0:3]
	fmt.Println(s)

RESULT IS GIVING 
[3 5 7]
[3 5 7]

WAT ???
SOULD BE
3 5 6 
2 3 5

WOOOOOOOOOO
FORGET THATTTTT
THAT GUY JUST UPDATED THE S 
WOOOOOOOOOOO

When you lose  the last ones is not LOST
but when you lose the first ones.. its lost..
	s := []int{2, 3, 5, 7, 11, 13}

	s = s[0:1]
	fmt.Println(s)

	s = s[1:2]
	fmt.Println(s)

	s = s[0:5]
	fmt.Println(s)
		s = s[:]
	fmt.Println(s)

​
RunFormatReset
[2]
[3]
[3 5 7 11 13]
[3 5 7 11 13]

ow.. an THIS is how its supposed to work.. ..ok..

**Comment by ALTree** [comment]
Unclear if you are reporting a tour bug... but reading the issue it seems like you solved your doubts yourself so I'm closing here.
