### ISSUE TITLE
tour: The random number is always generating same the number!

### ISSUE THREAD

**Issue by accessgopal** [golang/tour#267]
Context: http://127.0.0.1:3999/basics/1

package main

import (
	"fmt"
	"math/rand"
)

func main() {
	fmt.Println("My favorite number is ", ~~rand.Intn(10)~~)
}

## Something is wrong with the randIntn(10)

Either it is with the import or with the package. I have work on both online and offline version and results are the same.

**Comment by alebaffa** [comment]
It's normal. It's written in the note in the same page:

> **Note**: the environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed.)

**Comment by accessgopal** [comment]
But changing it so rand.Seed is throwing error! 

> tmp/sandbox907070895/main.go:9: rand.Seed(10) used as value

What am I doing wrong here?

**Comment by alebaffa** [comment]
I think [this other issue](https://github.com/golang/tour/issues/163) answers your question.

**Comment by tdondich** [comment]
@alebaffa I just did the tour online as well as local tour and the page that shows this code snippet does not show the text that you mention.  So for a newcomer, I almost thought something was wrong.  I had to dive into the math.rand package docs to see the notes you are talking about.

**Comment by ALTree** [comment]
Maybe we should stop using rand as the first example, but it won't be easy. I elaborated on this in  #408. I'll close here as a dup.
