### ISSUE TITLE
tour:packages.go bug in code

### ISSUE THREAD

**Issue by pmoh** [golang/tour#268]
This line of code is missing the param in the print statment. It does not print correctly when I tried it locally.
  fmt.Println("My favorite number is", rand.Intn(10))
It should be 
  fmt.Printf("My favorite number is %d\n", rand.Intn(10))

**Comment by robphoenix** [comment]
I think there's a slight confusion between `fmt.Println` & `fmt.Printf`. `Println` doesn't require the `%d` verb:

> Spaces are always added between operands and a newline is appended.

from the [docs](https://golang.org/pkg/fmt/#Println)

So in `fmt.Println("My favorite number is", rand.Intn(10))`, a space will be added between the string `"My favorite number is"` and the result of `rand.Intn(10)` and then appended with a newline and printed out.

The line of code above works fine in the [Go Playground](https://play.golang.org/p/GkSTC3sede)

I believe this issue can be closed @pmoh @adg

**Comment by pmoh** [comment]
Thanks I was still using the Printf from hello world program. Thanks.
