### ISSUE TITLE
Deploying to Google App Engine

### ISSUE THREAD

**Issue by ibrasho** [golang/tour#269]
Is there are any specific step to deploy a translation of the tour to GAE?

I'm assuming the recent changes to GAE and `appengine` package require some changes to `golang.org/x/tour` and `golang.org/x/playground` to allow the tour to be deployed.

**Comment by alebaffa** [comment]
I am the maintainer of the Italian tour, so I would be curious to know what are the changes on GAE that you are mentioning? If it's something considerable it would be useful to have this question also on the mailing-list (golang-nuts) to make the other maintainers aware of this. What do you think?

**Comment by ibrasho** [comment]
Can you deploy the latest commit of the tour to GAE with no issues?

**Comment by alebaffa** [comment]
I have to admit I have to update the Italian tour with the last 6 months commits. What issue are you having? Maybe someone here could give you a help if you post it.

**Comment by ibrasho** [comment]
I'm basically not able to deploy using the Google Cloud SDK (`gcloud`). The `App Engine SDK for Go` still works though.

I'm not sure what the changes were specifically, but I noticed the introduction of "Flexible environment" for example.

**Comment by ALTree** [comment]
This is >1year old so I'm closing here. If this is still an issue I suggest asking for guidance in the golang-dev mailing list.
