### ISSUE TITLE
tour: [Clarify that the trees are sorted]

### ISSUE THREAD

**Issue by MichaelSheely** [golang/tour#270]
Context: https://tour.golang.org/concurrency/8

When working through this example with a large number of students, about a third interpreted the directions:
> The function `tree.New(k)` constructs a randomly-structured binary tree holding the values `k, 2k, 3k, ..., 10k`.

to mean that the trees were not even sorted, but simply trees with random structures and the listed values. Consequently students felt they needed to perform more complicated logic to determine whether or not the trees contained the same set of values.

Since the trees returned by `tree.New()` are in fact sorted, a simple recursive in order traversal will do, regardless of the structure of the trees.

Would it be possible to change the quoted line to the following?
> The function `tree.New(k)` constructs a sorted (but randomly-structured) binary tree holding the values `k, 2k, 3k, ..., 10k`.

Or something along those lines?

**Comment by ALTree** [comment]
In the context of CS and data structures, the term "binary tree" is almost always used for the "binary-tree data structure", which is sorted by definition, and not the (more general) notion of "tree with two children".

In any case it's a two word change, so it may be worth it. I'll send a change.

**Comment by ALTree** [comment]
https://golang.org/cl/56171

**Comment by MichaelSheely** [comment]
Thanks for taking the time to make the change! Hopefully it helps more students avoid confusion if they're not super familiar with the standard context of trees in most data structures classes.
