### ISSUE TITLE
tour: instruction unclear for Reader with infinite stream

### ISSUE THREAD

**Issue by adderek** [golang/tour#274]
Context: https://tour.golang.org/methods/22

The instruction is unclear as it tells about "infinite stream" while expected is a Reader implementation that reads 'A' characters continuously.
Difference is like between infinite set of values and infinite recurrent function.

**Comment by ALTree** [comment]
I think it's correct. The exercise wants you to implement a Read method that emits an arbitrary large number of `A`; i.e. you call 'Read([]byte)` with a 1MB slice, it'll return 1MB of `A`, you call it with a `10MB` slice, it'll fill it with 10MB of `A`. "infinite stream" is an accurate description of this.

**Comment by TestItOnlyOnce** [comment]
I would agree with the previous commenter. The description **is** precise but the task one needs to accomplish is confusing as ~f~... Need to remind users that input to `Read` is externally defined slice of a unknown fixed length. Plus add the variable name to the comment  `// TODO: Add a Read(b []byte)` so one can type less. In any case (after looking at the solution) how come we are populating external slice that wasn't even passed by reference?! Needs a describing too.

Also next task with ROT 13. How am I supposed to know Go allows following comparison `'a' <= b //b is byte type` when it wasn't covered previously and people may not even know about ASCII character codes? In JS you need to do `ord('a')` in this case, for example.

**Comment by ALTree** [comment]
I think this is clear enough, closing here.
