### ISSUE TITLE
tour: russian translation

### ISSUE THREAD

**Issue by zhanbaur** [golang/tour#275]
Context: I'd like to translate the tour into the Russian language. 

Hello, I have just started my way to "go" programming. For the practice, I'd like to translate the tour into the Russian language. Is it possible, and if yes, what is the procedure of translation acceptance? Thanks.

**Comment by oshliaer** [comment]
@zhanbaur look at https://github.com/golang/tour/blob/master/TRANSLATE for the rules.

The Russian translate is here https://go-tour-ru-ru.appspot.com

It seems it was reviewed https://github.com/golang/tour/commit/cd978b761ea990975ef36825a6a1831b0c2f29c1


*The issue should be closed*.

**Comment by zhanbaur** [comment]
Thanx a lot.

**Comment by AlekSi** [comment]
There is also another translation: https://go-tour-russian.appspot.com/, source: https://github.com/golang-ru/tour-ru.

**Comment by oshliaer** [comment]
@AlekSi , It seems that the title of this translation doesn't correspond the requirements https://github.com/golang/tour/blob/master/TRANSLATE
>  Sign up to App Engine and create an app named go-tour-LL

**Comment by AlekSi** [comment]
`go-tour-ru` was squatted years ago. `go-tour-ru-ru` does not match that naming scheme too. :)
