### ISSUE TITLE
tour: use print() in sections on interfaces

### ISSUE THREAD

**Issue by heyoni** [golang/tour#280]
Context: https://tour.golang.org/methods/15
https://play.golang.org/p/ofPUaxb9sL

I was thinking that interfaces were somehow the same as types due to the way they're both displayed when using `fmt.Println()` and the fact that you can interact with the two in very similar ways. In my head, they were both just tuples of concrete values and types.

Then I got to the part about Type Assertions and realized they were actually quite different, but it didn't become clear to me until I used `print(i)` to display an interfaces' value and compared it to another variable. This may be a naive thing to get stuck on but I thought it would be a good place to use `print()` instead of `fmt.Println()` for the examples given. The raw output gave me a much clearer way of thinking about the different types being used.

**Comment by ALTree** [comment]
Suggesting the use of `print/println` in the tour is a bad idea. They shouldn't be used, they're in the language for bootstrapping/debugging reasons.

Also what you saw when you started using `print` on interfaces is actually already explained in the tour, at `tour.golang.org/methods/11`, where it says:

>  Under the covers, interface values can be thought of as a tuple of a value and a concrete type:
>
> (value, type)

this should already make quite clear that interfaces and types are different things.

**Comment by ALTree** [comment]
I believe this is WAI, closing here.
