### ISSUE TITLE
tour: Get different result when running on my laptop

### ISSUE THREAD

**Issue by navidpaya** [golang/tour#281]
Context: http://127.0.0.1:3999/basics/11

Change the title above to describe your issue and add your feedback here, including code if necessary. When I run the code on my laptop, running Arch Linux with go1.8.3, this is the result I get. I copied and pasted so don't think I've made a typo or such.

Press ENTER or type command to continue
Type: %T Value: %v
 false false
Type: %T Value: %v
 18446744073709551615 18446744073709551615
Type: %T Value: %v
 (2+3i) (2+3i)

This is what the tour gives me:

Type: bool Value: false
Type: uint64 Value: 18446744073709551615
Type: complex128 Value: (2+3i)

**Comment by ALTree** [comment]
I don't understand what code you are running. I copied the code here: 

https://tour.golang.org/basics/11

on my machine and the output is 

```
Type: bool Value: false
Type: uint64 Value: 18446744073709551615
Type: complex128 Value: (2+3i)
```

which is correct. What's the code you're running on you machine that gives you this output:

```
Press ENTER or type command to continue
Type: %T Value: %v
false false
Type: %T Value: %v
18446744073709551615 18446744073709551615
Type: %T Value: %v
(2+3i) (2+3i)
```
?

**Comment by navidpaya** [comment]
You're right. I was copying the wrong code, using Println instead of Printf. Sorry for that.
