### ISSUE TITLE
tour: rand.Intn() function returns always same value

### ISSUE THREAD

**Issue by vmironichev** [golang/tour#284]
Code:
``` go
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	fmt.Println("My favorite number is", rand.Intn(100))
}
```
Always prints output:

My favorite number is 81

**Comment by ALTree** [comment]
The text on that page explains this:

> Note: the environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed.)

**Comment by vmironichev** [comment]
Thanks!
