### ISSUE TITLE
Reverse floating point code samples to match text

### ISSUE THREAD

**Issue by filoxo** [golang/tour#286]
I'll admit that I stared at the FlowControls samples too long before realizing they're reversed in relation to the text before it. Reversing them to match the text would be great! ([example](https://github.com/golang/tour/pull/285/commits/12d1c551955211eb73a6004b0debf772d8a2b9af)) Thanks!

**Comment by ALTree** [comment]
Sounds reasonable. Do you want to send a change (on gerrit, the project does not use/support github pulls) or are you just suggesting that someone else does?

**Comment by filoxo** [comment]
I'm not very motivated to join the Gerrit system because I'm still just learning Go for my own edification and wouldn't be of much value just for a swapping out a couple of lines. If someone else can take care of it, that'd be great. Thanks!

**Comment by ALTree** [comment]
Sure. I sent http://golang.org/cl/56350
