### ISSUE TITLE
tour: Error `cannot use m (type Image) as type image.Image in argument to pic.ShowImage`

### ISSUE THREAD

**Issue by p-i-** [golang/tour#289]
https://tour.golang.org/methods/25

```
package main

import "golang.org/x/tour/pic"

type Image struct{}

func main() {
	m := Image{}
	pic.ShowImage(m)   <-- ERROR HERE
}
```

Error is:

> tmp/sandbox817364027/main.go:9: cannot use m (type Image) as type image.Image in argument to pic.ShowImage:
>	Image does not implement image.Image (missing At method)

**Comment by bgadrian** [comment]
Read the notes please, it is an exercise 
> Define your own Image type, implement the necessary methods, and call pic.ShowImage.
