### ISSUE TITLE
tour: German tour examples do not work. Error "Waiting for remote-server"

### ISSUE THREAD

**Issue by talon-vonneudeck** [golang/tour#29]
Context: https://go-tour-de.appspot.com/welcome/

If one uses the German tour, the examples do not work. Clicking on "Run" just produces a quickly disappearing "Warte auf den Remoteserver …" (Engl.: Waiting for remote server).

Using Chromium 50.0.2661.102
The English tour works fine.

**Comment by adg** [comment]
Duplicate of golang/go#15693
