### ISSUE TITLE
tour: [small issue in the Struct Literals within the Golang tour]

### ISSUE THREAD

**Issue by jfiamor** [golang/tour#290]
Context: http://127.0.0.1:3999/moretypes/5

**THIS:**
```
type Vertex struct {
	X, Y int
}

var (
	v1 = Vertex{1, 2}  // has type Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
	p  = &Vertex{1, 2} // has type *Vertex
)

func main() {
	fmt.Println(v1, p, v2, v3)
}
```

**OUTPUTS**
`{1 2} &{1 2} {1 0} {0 0}`

I don't think the & in the output was intended

**Comment by tophertimzen** [comment]
The `&` in the output is intended and is noted in the tour. This tells you that you are printing a pointer to a struct value.

The special prefix & returns a pointer to the struct value.

# CODE

```
package main

import "fmt"

type Vertex struct {
	X, Y int
}

var (
	a = &Vertex{5, 10}
)

func main() {
	fmt.Println(a)
}
```
# OUTPUTS

`&{5 10}`

**Comment by ALTree** [comment]
As explained, this is WAI. Closing.
