### ISSUE TITLE
Broken chapter concurrency/7

### ISSUE THREAD

**Issue by clamiax** [golang/tour#294]
Hi,

I've just noticed a JS error[0] which prevents the code editor to be properly loaded. It only happen on this[1] page.

EDIT: I think the editor has been hidden deliberately since the excercise description continue to the next page so I assume the JS error is not related; you may want to fix that though. I've also noticed that the editor gets drawn for a little while before it disappear.

[0] script.js:507 TypeError: Cannot read property 'Hash' of undefined
[1] https://tour.golang.org/concurrency/7

**Comment by jshrt** [comment]
:+1: 

After opening up the console, the error seems to be coming from the `file` function, precisely the following statement:
```
storage.set(file().Hash, val) // val comes from the angular watcher
```

The `file` function returns undefined, which in return makes it impossible to retrieve the hash which is used as the key to retrieve the code editor's content from the localStorage.

**Comment by ALTree** [comment]
I don't see any warning at the moment. Guess it was fixed by a later deployment? Closing.
