### ISSUE TITLE
tour: bug in "run" result

### ISSUE THREAD

**Issue by phil2k** [golang/tour#297]
Context: https://tour.golang.org/concurrency/2

Hi,
The result shouldn't be "-5 17 12", but "17 -5 12" (run on x86_64) ?
The channels flow-work should be like FIFO ?
But the run-result on the tour web-page looks like on LIFO.

**Comment by shurcooL** [comment]
Both results are possible, and that is working as intended. The two `sum` goroutines run at the same time and either one of them may end up sending a value to `c` channel first.

**Comment by shurcooL** [comment]
This is working as intended, there's no bug in tour, so there's no need to track it in the issue tracker.

If you have more questions about this, please see https://golang.org/wiki/Questions.
