### ISSUE TITLE
Error when running code on method 9

### ISSUE THREAD

**Issue by pavitarsaini** [golang/tour#298]
Context: https://tour.golang.org/methods/9

Error:
tmp/sandbox743643020/main.go:22:4: cannot use v (type Vertex) as type Abser in assignment:
	Vertex does not implement Abser (Abs method has pointer receiver)

**Comment by bgadrian** [comment]
Please read the notes, you must fix the code

> Note: There is an error in the example code on line 22. Vertex (the value type) doesn't implement Abser because the Abs method is defined only on *Vertex (the pointer type).
