### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by maxim-niko** [golang/tour#306]
Context: https://go-tour-ru-ru.appspot.com/methods/16
1. 
"Switch с типами это конструкция, которая позволяет несколько операций приведения типа подряд."

will be

"Switch с типами это конструкция, которая производит несколько операций приведения типа подряд."

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by ALTree** [comment]
We don't control or deploy the tour translation. I suggest you report this to the ru translator. Closing here.
