### ISSUE TITLE
tour: Can we not call implementing a square root function simple?

### ISSUE THREAD

**Issue by ericandrewlewis** [golang/tour#312]
Context: https://tour.golang.org/flowcontrol/8

The article reads

> As a simple way to play with functions and loops, implement the square root function using Newton's method.

might be nice to remove the simple here to avoid setting expectations for new golang users. The sentence reads nicely without it

> As a way to play with functions and loops, implement the square root function using Newton's method.

**Comment by tauki** [comment]
It's been changed @ericandrewlewis you can close the issue.

**Comment by ericandrewlewis** [comment]
❤️
