### ISSUE TITLE
tour: Line numbers overlaying code

### ISSUE THREAD

**Issue by shashankchaudhry** [golang/tour#320]
Context: https://tour.golang.org/welcome/1

I'm seeing the line numbers overlaying the code in the "tour of go". See attached screenshot.
<img width="961" alt="screen shot 2017-10-20 at 9 15 02 pm" src="https://user-images.githubusercontent.com/11810633/31847965-cf626b88-b5db-11e7-8985-c978ef3f8e96.png">

**Comment by resurtm** [comment]
I have the same issue (tested on Chrome Stable Latest & Firefox ESR).

**Comment by Baxxu** [comment]
![Imgur](https://i.imgur.com/YnGsEnp.png)

**Comment by jeffallen** [comment]
Dup of #323.
