### ISSUE TITLE
tour: LINE NUMER IS OFF and SHORTCUTS DON'T WORK

### ISSUE THREAD

**Issue by lantran** [golang/tour#322]
![screenshot-2017-10-22 a tour of go](https://user-images.githubusercontent.com/2984245/31857037-eeff9006-b68f-11e7-9406-1c845c03e062.png)
Context: https://tour.golang.org/welcome/1

1. Line number mixes with text in the editor.
2. Shortcuts for Run and Format don't work

I use Firefox 56.0 (64-bit)

**Comment by jeffallen** [comment]
Line numbers are a dup of #323.

**Comment by shurcooL** [comment]
Closing as duplicate. If the run/format shortcuts don't work, please file a separate issue just for that.
