### ISSUE TITLE
tour: [line numbers overlap the code]

### ISSUE THREAD

**Issue by Hubert1965** [golang/tour#328]
Context: https://tour.golang.org/welcome/1

There is a css bug in your tour. See: [screenshot on imgur](https://imgur.com/a/xuDdl). I think the line numbers should be placed in the column left of the grey line, but they appear in the same column as the code, overlapping it.

I can see this in Safari, Google Chrome, Opera and Firefox on my iMac (Mac OS X) and it appears on ever single page of your tour.

**Comment by jeffallen** [comment]
Dup of #320.
