### ISSUE TITLE
tour: code overlaps with line numbers

### ISSUE THREAD

**Issue by elbandito** [golang/tour#330]
Context: https://tour.golang.org

I've tested on Chrome and Safari, and still the code is overlapping with the code exercises.  

<img width="371" alt="screen shot 2017-10-25 at 10 49 41 pm" src="https://user-images.githubusercontent.com/1181106/32035481-d763e3e4-b9d6-11e7-86fb-248e90416bc1.png">

**Comment by jeffallen** [comment]
Dup of #323.
