### ISSUE TITLE
tour: Missing Return

### ISSUE THREAD

**Issue by lhodeniz** [golang/tour#337]
Context: https://tour.golang.org/moretypes/18
after run this error appear:
tmp/sandbox056513425/main.go:6:1: missing return at end of function
if I run it in offline tour that package is not found error appears.

**Comment by bgadrian** [comment]
It is an exercise, please read the notes. You must make it work by writing code.

**Comment by ALTree** [comment]
Yep, must be fixed, as requested by the text. Closing here.
