### ISSUE TITLE
tour: result runing in my computer is different

### ISSUE THREAD

**Issue by zyf0330** [golang/tour#342]
Context: https://tour.golang.org/concurrency/9

When I remove `fmt.Println(c.Value("somekey"))` in `main`, result in tour is always 0, but in my computer, it is random from 900 - 1000. And the last result is what I think is correct.

**Comment by bgadrian** [comment]
How do you see the 900-1000 values if you comment the line that prints the result? I do not understand.

**Comment by zyf0330** [comment]
Original sleep code is `time.Sleep(time.Microsecond)`.

**Comment by zyf0330** [comment]
Sorry, I have forgot original code. Maybe it was changed.
