### ISSUE TITLE
tour: Range и Close

### ISSUE THREAD

**Issue by Notevill** [golang/tour#363]
Context: https://go-tour-ru-ru.appspot.com/concurrency/4

Если закоментировать строки  27-29, то вывод строк 12, 18-20 не работает. Почему так происходит? Я пытался организовать вывод значений из канала параллельно с заполнением канала.

**Comment by Notevill** [comment]
Еще такой момент. В конспекте сказано, что _i:=range c_  получает значения из канала, до тех пор пока канал не закрыт. Но судя по выводу, чтение осуществляется не параллельно, а последовательно. т.е. _i:=range_ не работает пока не канал не закрыт (_close(c)_)
Вывод программы:
   eee
eee
eee
eee
eee
eee
eee
eee
eee
eee
1 вот 
1 вот 
2 вот 
3 вот 
5 вот 
8 вот 
13 вот 
21 вот 
34 вот 
0
Все!

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
