### ISSUE TITLE
tour: typo in russian version

### ISSUE THREAD

**Issue by twentyeighth** [golang/tour#365]
Context: https://go-tour-ru-ru.appspot.com/moretypes/1

"Тип *T is это указатель на значение T. Его нулевое значение nil."
Думаю, что "is" тут лишнее.
![image](https://user-images.githubusercontent.com/34363764/34025236-697e290e-e157-11e7-9a2f-8376a64501a8.png)

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
