### ISSUE TITLE
tour: typo in russian version

### ISSUE THREAD

**Issue by Shamann1101** [golang/tour#366]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

"Результатом append является **слез**, который содержит все элементы оригинального среза, а также новые значения." => "Результатом append является **срез**, который содержит все элементы оригинального среза, а также новые значения."

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
