### ISSUE TITLE
tour: go get instructions not working

### ISSUE THREAD

**Issue by mattcary** [golang/tour#371]
Context: https://tour.golang.org/welcome/3

I don't have gotour in my go installation. When I run the go get command to fetch the tour:
go get golang.org/x/tour/gotour
I receive the following error:
package golang.org/x/tool/gotour: unrecognized import path "golang.org/x/tool/gotour" (parse https://golang.org/x/tool/gotour?go-get=1: no go-import meta tags ())

This happens on multiple machines with the identical error, one ubuntu and the other termux on an android tablet.

Going to https://golang.org/x/tools/gotour redirects to godoc.org, and then can't find gotour; navigating to the x/tools directory on godoc.org suggests that gotour no longer exists?

Thanks for your help.

**Comment by alebaffa** [comment]
I didn't have the go tour in one of my laptops, but I just run `go get golang.org/x/tour/gotour` and it worked correctly. Which version of Go do you have? Did you set up the GOPATH, maybe?

**Comment by mattcary** [comment]
User error: I mistyped "/tool/" instead of "/tour/" :/

After growing in my go knowledge, I've learned since that that "unrecognized import path" error happens when the get target doesn't exist. The error message is cryptic, but at least it's consistent...

Thanks for looking!
