### ISSUE TITLE
tour: Comment says one thing, code does another

### ISSUE THREAD

**Issue by renatoathaydes** [golang/tour#373]
Context: https://tour.golang.org/moretypes/11

The last 2 examples are currently:

```go
	// Drop its first two values.
	s = s[2:]
	printSlice(s)

        // Drop its first two values.
	s = s[:2]
	printSlice(s)
```

Notice how the comment above the first slice matches the code: to drop the first 2 values, we do `s[2:]`... but the next example does `s[:2]` instead, but the comment is still the same.

The comment on the last example should say `Keep its first two values.`.

**Comment by ALTree** [comment]
> The last 2 examples are currently

I don't see that. What I see is:

```
func main() {
	s := []int{2, 3, 5, 7, 11, 13}
	printSlice(s)

	// Slice the slice to give it zero length.
	s = s[:0]
	printSlice(s)

	// Extend its length.
	s = s[:4]
	printSlice(s)

	// Drop its first two values.
	s = s[2:]
	printSlice(s)
}
```

I think you changed the code by copy-pasting the last example and then forgot about it. Nothing to do here, closing.
