### ISSUE TITLE
tour: [Error in Russian version]

### ISSUE THREAD

**Issue by yurikulaz** [golang/tour#374]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

The original article

> Результатом append является **слез**, который содержит все элементы оригинального среза, а также новые значения.

should be replaced with

> Результатом append является **срез**, который содержит все элементы оригинального среза, а также новые значения.

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
