### ISSUE TITLE
tour: wrong translation

### ISSUE THREAD

**Issue by Dumkin** [golang/tour#376]
Context: https://go-tour-ru-ru.appspot.com/moretypes/1

> Тип *T _**is**_ это указатель на значение T. Его нулевое значение nil.

Replace to
> Тип *T это указатель на значение T. Его нулевое значение nil.

"is" equivalent "это"

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
