### ISSUE TITLE
tour: Inconsistent pattern in mutex unlocking

### ISSUE THREAD

**Issue by dirkharrington** [golang/tour#383]
Context: https://tour.golang.org/concurrency/9

The .Value() function defers the mutex unlocking while .Inc(key) does it the end of the method. Is there a reason for the difference in idioms? On the surface it seems the example should be consistent in its approach to teaching .Unlock() - preferably via defer (imo).

**Comment by ALTree** [comment]
> Is there a reason for the difference in idioms?

Probably to show that you can do both. Which I think it's a good idea. We wouldn't want to give the idea that lock *must* be unlocked with deferes or that they are special in any way (locking/unlocking is a call like any other). 

I believe this should stay as it is. Closing here.
