### ISSUE TITLE
tour: Add keyboard navigation

### ISSUE THREAD

**Issue by Prinzhorn** [golang/tour#386]
Context: https://tour.golang.org/methods/3

It would be sick if I could skim through the pages using Left/Right keys on my keyboard instead of clicking the tiny arrows. I took a look at the Angular source, but I don't know the correct place to add it (since navigating inside the code editor should of course not trigger a `prevPage` / `nextPage`)

**Comment by ALTree** [comment]
You can use `Page{Up,Down}` for this. Binding the arrows to `NextPage` is not a good idea because it may inadvertitely trigger when editing the code. Closing here.

**Comment by Prinzhorn** [comment]
@ALTree thank you very much, that's all I needed! Where is this documented? Maybe add a `title` attribute to the previous/next arrows.

**Comment by ALTree** [comment]
>  Where is this documented?

First page (https://tour.golang.org/welcome/1):

> Throughout the tour you will find a series of slides and exercises for you to complete. You can navigate through them using
> 
> "previous" or `PageUp` to go to the previous page,
> "next" or `PageDown` to go to the next page.

---

> Maybe add a title attribute to the previous/next arrows.

IMHO it would be annoying to have a tooltip with a key-shortcut come up every time you hover the mouse on the arrows.
