### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by dlarchikov** [golang/tour#387]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

Change the title above to describe your issue and add your feedback here, including code if necessary

`является слез` replace to `является срез`

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
