### ISSUE TITLE
tour: "Error communicating with remote server" when using Gorutines or Channels

### ISSUE THREAD

**Issue by piraces** [golang/tour#390]
Context: https://tour.golang.org/concurrency/2

Following "A tour of Go", in the Concurrency section several errors of `Error communicating with remote server.` happen when trying to run the examples provided for Gorutines, Channels and Buffered Channels. 

I think this could be a non-reproducible bug. Currently is happening with provided example code (without changes), about 3 out of 10 times.

**Comment by WheeskyJack** [comment]
Hi,
is the issue still seen ?
BR.

**Comment by ALTree** [comment]
Likely a one-off error. Closing here since it has been a while.
