### ISSUE TITLE
tour: <tab>fmt.Println("Hello, foo.") causes 'process took too long'

### ISSUE THREAD

**Issue by carloseberhardt** [golang/tour#393]
Context: https://tour.golang.org/welcome/1

This specific code causes a process took too long error.
```
package main

import "fmt"

func main() {
	fmt.Println("Hello, foo.")
}
```

indent must be a tab, msg must be "Hello, foo."  I haven't bothered trying all other combinations, but altering the string or indenting with spaces does not cause the error.

**Comment by WheeskyJack** [comment]
Hi,
is the issue still seen ?
BR.
