### ISSUE TITLE
tour: [OPTION TO SHARE TRANSLATION IN OTHER LANGUAGE]

### ISSUE THREAD

**Issue by oswee** [golang/tour#395]
Context: https://tour.golang.org/basics/8

Hi, Is there a way to share translation in other language. I think I could make one in Latvian (small European lang). What is the steps to do this?

**Comment by ALTree** [comment]
Hi, the steps are documented here: https://github.com/golang/tour/blob/master/TRANSLATE

I believe this answers your question, so I'm closing this issue.
