### ISSUE TITLE
tour: command didn't work

### ISSUE THREAD

**Issue by danaconda** [golang/tour#396]
Context: https://go-tour-ru-ru.appspot.com/welcome/3

$go tool tour # didn't work for me 

go version go1.9.2 linux/amd64
kali linux 
what dependencies i need to install?

**Comment by bgadrian** [comment]
None, it should work, but you can install it manually see the notes

> To run the tour locally first download and install Go then start the tour from the command line:
> go tool tour
Or, you can install and run this tour manually if you have any trouble running the above command:
go get golang.org/x/tour/gotour
gotour

Duplicate of #8 I think

**Comment by ALTree** [comment]
Closing as a dup of #8.
