### ISSUE TITLE
tour: [Typo]

### ISSUE THREAD

**Issue by trigun117** [golang/tour#397]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

"Результатом append является **слез**, который содержит все элементы оригинального среза, а также новые значения."

**Correct:**

"Результатом append является **срез**, который содержит все элементы оригинального среза, а также новые значения."

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
