### ISSUE TITLE
tour: [Exercise: Equivalent Binary Trees]  I think it's better to call binary search trees

### ISSUE THREAD

**Issue by muzea** [golang/tour#403]
Context: https://tour.golang.org/concurrency/8

There are many kinds of binary trees, but here is a binary search tree.
Perhaps the name of the exercise into 'Equivalent Binary Search Trees' will be better.
At the beginning I wondered how to sort :(

**Comment by ALTree** [comment]
Thanks for the report.

I think "sorted binary tree" is more common. But the current wording is:

> randomly-structured (but always sorted) binary tree 

this seems clear enough to me.

We could change the name of the exercise, but it's just a title, it should be too verbose just to be 100% accurate. 

Overall, I think the wording is clear enough. Closing here.
