### ISSUE TITLE
tour: incorrect language name/translation

### ISSUE THREAD

**Issue by nanaya** [golang/tour#406]
Context: https://tour.golang.org/welcome/2

> "Indonesia — Bahasa"

"Indonesia" is the country, "Indonesia*n* (language)" is the language.

"Bahasa" means "language". "Bahasa Indonesia" means "Indonesian" (or literally "Indonesia(n)'s Language").

**Comment by ALTree** [comment]
Thanks for the report. I sent https://golang.org/cl/93236
