### ISSUE TITLE
tour: Strange re-ordering

### ISSUE THREAD

**Issue by lugray** [golang/tour#411]
Context: http://127.0.0.1:3999/moretypes/5

```go
var (
	v1 = Vertex{1, 2}  // has type Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
	p  = &Vertex{1, 2} // has type *Vertex
)

func main() {
	fmt.Println(v1, p, v2, v3)
}
```

In the above, i see no advantage to the existing order `fmt.Println(v1, p, v2, v3)` over `fmt.Println(v1, v2, v3, p)` which would be more expected and understandable from the definition above.

**Comment by tophertimzen** [comment]
I agree and I was about to open the same issue. The `fmt.Println` should be in the same order as the declared variables with `fmt.Println(v1, v2, v3, p)`.

**Comment by tophertimzen** [comment]
Apparently this is known and this is the intended `fmt.Println` order, https://github.com/golang/tour/issues/164.

**Comment by lugray** [comment]
What about this then?

```go
var (
	v1 = Vertex{1, 2}  // has type Vertex
	p  = &Vertex{1, 2} // has type *Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
)

func main() {
	fmt.Println(v1, p, v2, v3)
}
```

**Comment by ALTree** [comment]
Thanks for the report.

> What about this then?

```go
var (
	v1 = Vertex{1, 2}  // has type Vertex
	p  = &Vertex{1, 2} // has type *Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
)

func main() {
	fmt.Println(v1, p, v2, v3)
}
 ```

The "value - value - value - pointer" order mirrors the order of explanation in the text on the left:

>  A struct literal denotes a newly allocated struct value by listing the values of its fields.

> You can list just a subset of fields by using the Name: syntax. (And the order of named fields is irrelevant.)

> The special prefix & returns a pointer to the struct value. 

Which is a good thing: first explain the values, then introduce the idea of a pointer. 

I don't think the printing order is terribly confusing. The names of the variables are clearly different (`v` vs `p`), if you look at the code carefully you won't be confused by the order.

I think this is clear enough, so I'll close this issue.
