### ISSUE TITLE
tour: Russian localization issue

### ISSUE THREAD

**Issue by sergiev** [golang/tour#413]
Context: https://go-tour-ru-ru.appspot.com/basics/15

There is a grammatical mistake in "Константы не могут быть объявленные с помощью синтаксиса"
Correct version is "Константы не могут быть объявлены с помощью синтаксиса"

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
