### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by mchardalas** [golang/tour#417]
Context: https://tour.golang.org/concurrency/1

Part of the error message: 

> runtime/cgo: pthread_create failed: Resource temporarily unavailable
> SIGABRT: abort
> PC=0x7f7a7ad8f067 m=0 sigcode=18446744073709551610
> 

How to reproduce: Click "Run"

The strange thing is, whether is, as I am quite new to Go, that when I change one of the strings in the main goroutine it runs. For instance, replace "hello" with "a" or "world" with "a" and it runs. Note that it runs also when you tweak the time in "Sleep".

```
func main() {
	go say("a")
	say("hello")
}

```

**Comment by ALTree** [comment]
Likely a temporary issue, now fixed. Closing.
