### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by woto** [golang/tour#419]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

Тип []T обозначает срез в элементами типа T.

срез **c** элементами?

**Comment by killrazor** [comment]
Translated from Google.

"Misprint # 419

Context: https://go-tour-ru-ru.appspot.com/moretypes/7

Type [] T denotes a slice in elements of type T.

slice with elements?"

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
Looks fixed in the last version: https://go-tour-ru-ru.appspot.com/moretypes/7. Closing here.
