### ISSUE TITLE
tour: why do we need an array size

### ISSUE THREAD

**Issue by literadix** [golang/tour#42]
Context: https://tour.golang.org/moretypes/7

Hi,

following is also possible: []int{2, 3, 5, 7, 11, 13}

Why do you use the array size[6}. Is there any advanzage to use it ?

**Comment by adg** [comment]
Hi there. Thanks for taking the tour.

This is the issue tracker for reporting problems with the tour. If you want to ask general questions about Go, please ask in [one of the Go discussion forums](https://github.com/golang/go/wiki/Questions).

Thanks.
