### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by ymolodyukov** [golang/tour#426]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

Change the title above to describe your issue and add your feedback here, including code if necessary

there is
> Результатом append является **слез**, который содержит ...

should be
Результатом append является **срез**, который содержит ...

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
