### ISSUE TITLE
Test fails / maybe part of the exercise

### ISSUE THREAD

**Issue by spossner** [golang/tour#429]
Context: https://tour.golang.org/moretypes/23

Testcase „I am learning Go!“ seems to have wrong assertion with an expected length of 1 for the wird „am“

**Comment by WheeskyJack** [comment]
Hi, 
The test exercise is meant to be run after the full implementation of the exercise (which is implementation of func WordCount()). The initial setup only provides the basic function signature and not the actual implementation.
I guess you are running the code as it is provided. 
BR.

**Comment by ALTree** [comment]
Yep, this is an exercise. You'll need to implement the requested code to see it pass. Closing.
