### ISSUE TITLE
tour: [misprint in translation]

### ISSUE THREAD

**Issue by reducio** [golang/tour#431]
Context: https://go-tour-ru-ru.appspot.com/moretypes/1

"Тип *T is это указатель на значение T. Его нулевое значение nil." - wrong
"Тип *T это указатель на значение T. Его нулевое значение nil." - correctly

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
