### ISSUE TITLE
Error in output

### ISSUE THREAD

**Issue by tejbari99** [golang/tour#437]
Context: https://tour.golang.org/moretypes/15

your output:
len=0 cap=0 []
len=1 cap=2 [0]
len=2 cap=2 [0 1]
len=5 cap=8 [0 1 2 3 4]

to be:
len=0 cap=0 []
len=1 cap=1 [0]
len=2 cap=2 [0 1]
len=5 cap=6 [0 1 2 3 4]

Please check.

**Comment by bgadrian** [comment]
What is the error? I think the capacity 8 is correct, from what I know the default behavior is to have capacities as powers of 2.

**Comment by ALTree** [comment]
OP is confused about the `cap` values being different on their machine (likely a 64 bits system). This is normal. The playground environment is 32bits and the runtime grows the slice's backing array differently. This is an internal implementation detail, so there's no bug. Closing here.
