### ISSUE TITLE
tour: Fix a typo in the Russian translation

### ISSUE THREAD

**Issue by andrewbo** [golang/tour#438]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

There's a typo in the following sentence: "Тип []T обозначает срез в элементами типа T."
" в " should be replaced with " с ". The fixed version: "Тип []T обозначает срез с элементами типа T."

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
Looks fixed in the last version: https://go-tour-ru-ru.appspot.com/moretypes/7. Closing here.
