### ISSUE TITLE
tour: Replace "Under the covers"

### ISSUE THREAD

**Issue by jrbalsano** [golang/tour#445]
Context: https://tour.golang.org/methods/11

On this page of the tour, the page reads "Under the covers, interface values can be thought of as a tuple of a value and a concrete type". The expression "under the covers" can be construed as unnecessarily sexual and could be confusing for non-native English speakers.

I propose either replacing the wording here with "Under the hood", or just remove the phrasing entirely. I also considered "Internally" instead but that made me realize that the phrasing here is just a little bit strange to begin with.

I'm happy to submit the change myself, just want to obtain approval before I go opening a Pull Request. 😄

**Comment by ALTree** [comment]
I think "under the hood" is what is usually used when talking about internal implementation details of programming languages or libraries. So I think it would be ok to fix this by simply replacing "Under the covers" with "Under the hood".

You are welcom to send a change.

**Comment by jrbalsano** [comment]
Thanks for fixing this @bgadrian and @ALTree and sorry I didn't get to it sooner!

**Comment by bgadrian** [comment]
I don't think the reasoning (sexual) is valid, but I agree with the change because of the popularity of the expression, "under the hood", after a simple google search, is roughly 20xtimes more used in the "software" context, then "under the covers".
