### ISSUE TITLE
tour: goroutine possible typo

### ISSUE THREAD

**Issue by cameoh** [golang/tour#447]
Context: https://tour.golang.org/concurrency/1

go f(x, y, z)
The evaluation of f, x, y, and z happens in the current goroutine and the execution of f happens in the new goroutine.

Is there a typo here? Should it be "The evaluation of x, y, and z happens in the current goroutine"? What does it mean the _evaluation_ of f? The _execution_ of f happens in the new goroutine, of course, as the sentence later says.

**Comment by xltan** [comment]
f may be an anonymous function

**Comment by ALTree** [comment]
> f may be an anonymous function

^this. The spec says

> The function value and parameters are evaluated as usual in the calling goroutine

since `f` is a value as everything else, it may need to be evaluated. Closing here.
