### ISSUE TITLE
tour: Slice defaults, typo slice -> array?

### ISSUE THREAD

**Issue by vabr-g** [golang/tour#449]
Context: https://tour.golang.org/moretypes/10

When the text says: "The default [slice bound] is [...] the length of the _slice_ for the high bound," should it say "the length of the _array_" instead? It is not clear what a length of a slice is.

**Comment by bgadrian** [comment]
The sentence "The default is zero for the low bound and the length of the slice for the high bound." is also discussed/duplicate of https://github.com/golang/tour/issues/182

**Comment by ALTree** [comment]
Closing here as a dup of #182. Let's keep the discussion there.
