### ISSUE TITLE
tour: [Typo]

### ISSUE THREAD

**Issue by trigun117** [golang/tour#455]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

`Тип []T обозначает срез в элементами типа T.` - should be `Тип []T обозначает срез с элементами типа T.`

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
Looks fixed in the last version: https://go-tour-ru-ru.appspot.com/moretypes/7. Closing here.
