### ISSUE TITLE
tour: grammatical mistake in 'if and else'

### ISSUE THREAD

**Issue by anandhkrishnan** [golang/tour#460]
Context: https://tour.golang.org/flowcontrol/7

Shouldn't "Both calls to pow are executed and return..."
be
"Both calls to pow are executed and returned..."

Also, somehow "Both" does not seem to be the right word to use. Maybe "The two calls..." is a worthy replacement?

**Comment by ALTree** [comment]
The text now says "Both calls to pow return" which seems clearer. Closing here.
