### ISSUE TITLE
Description syntax misspell

### ISSUE THREAD

**Issue by ghost** [golang/tour#464]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15
Instead of "слез" in sentence "Результатом append является слез" should be "срез".

**Comment by justkexit** [comment]
Uh oh, merge with github.com/golang/tour/issues/457 please

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
