### ISSUE TITLE
tour: "random favorite number" is always 1

### ISSUE THREAD

**Issue by rcoscali** [golang/tour#468]
Context: https://tour.golang.org/basics/1

In the tour basic 1 lesson, I imagine returned number should be between 1 and 10, but result is always 1, on golang servers or on my own host.

fmt.Println("My favorite number is", rand.Intn(10)) always returns 1

**Comment by davidak** [comment]
From the lessons description:

**Note**: the environment in which these programs are executed is deterministic, so each time you run the example program `rand.Intn` will return the same number. (To see a different number, seed the number generator; see `rand.Seed`. Time is constant in the playground, so you will need to use something else as the seed.)

**Comment by ALTree** [comment]
Closing as a dup of #408.

**Comment by kristianjaeger** [comment]
Here's a simple way to 'fix' it:
`package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	rand.Seed(time.Now().UTC().UnixNano())
	test()
	test()
}

func test() {
	fmt.Println("My favorite number is", rand.Intn(10))
}`
Cheers.
