### ISSUE TITLE
tour: [Error without obvious reasons]

### ISSUE THREAD

**Issue by li-jie-li** [golang/tour#47]
Context: https://tour.golang.org/moretypes/23

I am getting below error messages but not sure what went wrong:

FAIL
 f("I am learning Go!") =
  map[string]int{"I":1, "am":1, "learning":1, "GO":1}
 want:
  map[string]int{"I":1, "am":1, "learning":1, "Go!":1}
Program exited.

**Comment by solojavier** [comment]
`"GO":1` is not equal to `"Go!":1`

**Comment by ALTree** [comment]
Yep, they're different. Closing here, since it's not a bug.
