### ISSUE TITLE
tour: [Typo in Russian tutorial, moretypes/7]

### ISSUE THREAD

**Issue by MEZk** [golang/tour#474]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

"Тип []T обозначает срез в элементами типа T." should be "Тип []T обозначает срез с элементами типа T."

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
Looks fixed in the last version: https://go-tour-ru-ru.appspot.com/moretypes/7. Closing here.
