### ISSUE TITLE
tour: Russian tutorial differs from english for moretypes/7

### ISSUE THREAD

**Issue by tarpaha** [golang/tour#478]
Context: https://go-tour-ru-ru.appspot.com/moretypes/7

Compare https://tour.golang.org/moretypes/7 and https://go-tour-ru-ru.appspot.com/moretypes/7
Russian version have no description for [low : high] indices. 

> A slice is formed by specifying two indices, a low and high bound, separated by a colon:
> a[low : high]
> This selects a half-open range which includes the first element, but excludes the last one.

Can be translated as

> Срез создаётся указанием двух индексов - нижней и верхней границы, разделённых двоеточием:
> a[low : high]
> Это выражение создаёт срез, включающий элементы начиная с первого до, но не включая, последнего.

**Comment by shuLhan** [comment]
CC @kalimatas

**Comment by ALTree** [comment]
We don't control or deploy the tour translation, this issue should be reported to the russian translation owner at https://github.com/kalimatas/go-tour-ru. Closing here.
