### ISSUE TITLE
tour: finded typo

### ISSUE THREAD

**Issue by Dementir** [golang/tour#480]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

Finded typo in ru version tour
![2018-05-14_163008](https://user-images.githubusercontent.com/20162872/40000346-462f9132-5794-11e8-8a37-096008163275.png)

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
