### ISSUE TITLE
tour: Output is always "My favorite number is 1"

### ISSUE THREAD

**Issue by vijaysg** [golang/tour#49]
Hi,
  I am a newbie to GO.

Context: https://tour.golang.org/basics/1

When I try executing the sample code the output is always **My favorite number is 1**, shouldn't it randomize the number?

Confirmed the same by executing the tour in another machine locally (go tools tour).

**Comment by mauri870** [comment]
Have a look at the note on description
```
Note: the environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed.)
```
