### ISSUE TITLE
tour: Missing semicolons in this example of `for` loop

### ISSUE THREAD

**Issue by tapank** [golang/tour#495]
Context: https://tour.golang.org/flowcontrol/2

In line 7: `for sum < 1000 {` , given the purpose of the slide, `;`s should not be omitted. Hence, line 7 should be: `for ; sum < 1000; {`. The purpose of this slide is to show that the init and post statements are optional (without dropping the semicolons yet, because that is what the next slide talks about).

The next slide then says "At that point you can drop the semicolons", where `for sum < 1000 {` is appropriate.

**Comment by bgadrian** [comment]
I think it's an user error, it was fixed since 4yrs ago 
https://github.com/golang/tour/commit/07a2ce422150cc825eb857921608183d61aa917f

I think you pressed the "Format" button, and the fmt will remove the semi colons because they are unnecessary.

**Comment by ALTree** [comment]
Yep, the semicolons are there, they go away if you format the code. Closing.
