### ISSUE TITLE
tprog.go:22:4: cannot use v (type Vertex) as type Abser in assignment: 	Vertex does not implement Abser (Abs method has pointer receiver)

### ISSUE THREAD

**Issue by ChandimaGa** [golang/tour#509]
Context: https://tour.golang.org/methods/9

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by bgadrian** [comment]
The error is the purpose of the lesson, see the comment and description:

> Note: There is an error in the example code on line 22. Vertex (the value type) doesn't implement Abser because the Abs method is defined only on *Vertex (the pointer type).

> // In the following line, v is a Vertex (not *Vertex)
	// and does NOT implement Abser.

**Comment by ALTree** [comment]
As said above, this is expected. Closing.
