### ISSUE TITLE
Last line says - a sized or unsigned integer type.

### ISSUE THREAD

**Issue by grushler** [golang/tour#51]
Context: http://127.0.0.1:3999/basics/11

Should it be saying `signed or unsigned interger` instead?

**Comment by hkra** [comment]
I believe that the wording is correct as is. `int` is a signed type, so what it is saying, in slightly more verbose language, is: 

Use `int` unless you need to use a different size integer (8-, 16-, 32- or 64-bit--depending on your system) or you need an unsigned integer.

**Comment by grushler** [comment]
Thanks @hkra. Closing the issue.
