### ISSUE TITLE
Russian lang syntax error

### ISSUE THREAD

**Issue by achatina** [golang/tour#513]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

Орфорграфическая ошбика в 3 абзаце в слове срез:

> Результатом append является **слез**

**Comment by shuLhan** [comment]
CC @kalimatas .

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
