### ISSUE TITLE
tour: Cannot allocate memory

### ISSUE THREAD

**Issue by kamynina** [golang/tour#514]
Context: https://go-tour-ru-ru.appspot.com/concurrency/4

I run a programme and see an error 
`/usr/local/go/src/sync/pool.go:9:2: read /usr/local/go/src/runtime/symtab_test.go: read /usr/local/go/src/runtime/symtab_test.go: cannot allocate memory`

**Comment by bgadrian** [comment]
It seems duplicate https://github.com/golang/tour/issues/512

**Comment by kamynina** [comment]
Ok, i'll close it
