### ISSUE TITLE
tour: typo in the Russian version (in chapter about Mutex)

### ISSUE THREAD

**Issue by kamynina** [golang/tour#518]
Context: https://go-tour-ru-ru.appspot.com/concurrency/9

Typo in word `эта`. It should be `это`

`Эта концепция известна как взаимное исключение, и общепринятым названием для структуры данных, которая эта позволяет, является мьютекс (mutex).`

should be 

`Эта концепция известна как взаимное исключение, и общепринятым названием для структуры данных, которая это позволяет, является мьютекс (mutex).`

**Comment by shuLhan** [comment]
CC @kalimatas .

**Comment by ALTree** [comment]
See #550 for how to report translation errors (we don't control the russian tour, only link to it). Thanks. Closing here.
