### ISSUE TITLE
tour: Out of memory returned from server

### ISSUE THREAD

**Issue by nickshanks** [golang/tour#522]
Context: https://tour.golang.org/flowcontrol/5

Result: "fatal error: runtime: out of memory"
When running code:

```go
package main

import (
	"fmt"
	"math"
)

func sqrt(x float64) string {
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
}
```

Removing the minus sign from the `main()` function's call to `sqrt(-4)` fixes it

**Comment by bgadrian** [comment]
Duplicate of https://github.com/golang/tour/issues/521

**Comment by ALTree** [comment]
Closing as a dup of  #541
