### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by sushemsu** [golang/tour#523]
Context: http://10.0.0.83/basics/1

Change the title above to describe your issue and add your feedback here, including code if necessary
Demo for a Tour of go
Source: 
_EOF_
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	fmt.Println("My favorite number is", rand.Intn(10))
}
_EOF_
Only returns to web interface 'My favorite number is 1

Program exited.'
100% of the time
Env
[root@go bin]# cat /etc/*release*
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
Go Version 
Dist pkg: go 2:1.10.3-1
webserver instance installed via with
go get golang.org/x/tour/gotour
Webserver launched as ./gotour --http <ip>:80
Webclient info: 

Google Chrome | 67.0.3396.87 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 878cd31214ac27a3996927cd5c9c138b10c9fc8d-refs/branch-heads/3396@{#771}
OS | Windows
JavaScript | V8 6.7.288.46
Flash | 30.0.0.113 C:\Users\sushe\AppData\Local\Google\Chrome\User Data\PepperFlash\30.0.0.113\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end

**Comment by sushemsu** [comment]
2018/06/15 21:45:36 running snippet from: 10.0.0.100:61834
No strace attached or gdb to actually eval : (

**Comment by bgadrian** [comment]
Yes it's meant to be like that, please read the description

> Note: the environment in which these programs are executed is **deterministic**, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed. Time is constant in the playground, so you will need to use something else as the seed.)

**Comment by ALTree** [comment]
The playground environment is deterministic, so this is expected. It's documented in the text on the left. Closing here.
