### ISSUE TITLE
tour: [cannot allocate memory error]

### ISSUE THREAD

**Issue by johnbalvin** [golang/tour#528]
Context: https://tour.golang.org/concurrency/4

When running on the web page I get this error:
 /usr/local/go/src/sync/pool.go:9:2: read /usr/local/go/src/runtime/symtab_test.go: read /usr/local/go/src/runtime/symtab_test.go: cannot allocate memory

**Comment by bgadrian** [comment]
I think is a duplicate of https://github.com/golang/tour/issues/512

**Comment by ALTree** [comment]
Closing as a dup of  #541
