### ISSUE TITLE
word abuse

### ISSUE THREAD

**Issue by apple2apple** [golang/tour#529]
Context: https://go-tour-ru-ru.appspot.com/basics/3
pidor is a faggot in russian

func main() {
    var pi int = 10
	const pidor = math.Pi
	fmt.Println(pi)
	fmt.Println(**pidor**)
}

**Comment by bgadrian** [comment]
Where did you get that code from? The code found on the page you linked is 

```go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.pi)
}
```

**Comment by ALTree** [comment]
Yes, I think someone else using that machine may have tiped that... the browser remembers modifications to the tour programs until you clean the cache. Closing here
