### ISSUE TITLE
tour: Unspecified Infinite loop in out of the box code

### ISSUE THREAD

**Issue by filipbarak** [golang/tour#531]
Context: https://tour.golang.org/flowcontrol/5

```
package main

import (
	"fmt"
	"math"
)

func sqrt(x float64) string {
	if x < 0 {
		return sqrt(-x) + "i"
	}
	return fmt.Sprint(math.Sqrt(x))
}

func main() {
	fmt.Println(sqrt(2), sqrt(-4))
}
```

I'm guessing it enters some infinite recursion if you put a negative int as an argument (sqrt(-4)). It throws an out of memory exception. 

> 
> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x5fda69, 0x16)
> 	/usr/local/go/src/runtime/panic.go:616 +0x81
> runtime.sysMap(0xc420880000, 0x100000, 0x0, 0x7178d8)

I've changed it to ```sqrt(4)``` and it worked, but I see how it might be confusing to someone new.

Cheers

**Comment by ALTree** [comment]
Closing as a dup of  #541
