### ISSUE TITLE
tour: always returns 1024?

### ISSUE THREAD

**Issue by yooakim** [golang/tour#535]
Context: http://127.0.0.1:3999/flowcontrol/2

I'm a newbie to Go and I am going through `A Tour of Go`  the code on this page always returns `1024`  which I do not understand? Can anyone explain why? I have changed the iteration but whatever I use I always get `1024` as the result.

**Comment by bgadrian** [comment]
I cannot replicate, if I change to 
`for sum < 200 {
		sum += sum
	}`
I get `256` , and so on.

Maybe your compiler throws an error and the first value doesn't change, or something to do with the cache? 
Try playing with the online version https://tour.golang.org/flowcontrol/2 in a incognito browser.

**Comment by yooakim** [comment]
It was my bad, sorry. I misread the logic. I was tired… The example works just fine as can be seen here:

![get-started](https://user-images.githubusercontent.com/862546/41971520-02c0baa0-7a0f-11e8-8052-f18833383561.gif)
