### ISSUE TITLE
tour: undefined: math.pi

### ISSUE THREAD

**Issue by TaurusD** [golang/tour#538]
Context: https://tour.golang.org/basics/3

Running the default code gives the following return: 

prog.go:9:14: cannot refer to unexported name math.pi
prog.go:9:14: undefined: math.pi

**Comment by bgadrian** [comment]
Please read the text in the left part of the window, that is the point of the tutorial. 
`To fix the error, rename math.pi to math.Pi and try it again.`

Lower case means the property is private, uppercase is public.

**Comment by ALTree** [comment]
Working as expected and documented. Closing.
