### ISSUE TITLE
tour: syntax error in ru lang description

### ISSUE THREAD

**Issue by hololoev** [golang/tour#539]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15
`Результатом append является Error is here>>> слез <<<, который содержит все элементы оригинального среза, а также новые значения. `

Should be: 

`Результатом append является срез, который содержит все элементы оригинального среза, а также новые значения. `

Wrong just 1 char

**Comment by ALTree** [comment]
We don't control or deploy the tour translations... you should report this to the ru translation maintainer. Closing here.
