### ISSUE TITLE
tour: run failed in the tour

### ISSUE THREAD

**Issue by yjiangnan** [golang/tour#540]
Context: https://tour.golang.org/welcome/4

prog.go:12:2: cannot refer to unexported name time.sleep
prog.go:12:2: undefined: time.sleep

Program exited.

**Comment by bgadrian** [comment]
I cannot find Sleep in the example page.

I presume you typed somewhere `time.sleep` instead of `time.Sleep`. Notice the lowercase, it has to be uppercase to access a public/exported structure from a library.

**Comment by ALTree** [comment]
Yep, it's `time.Sleep` with capital `S`. Closing here, since it's not a bug.

**Comment by ALTree** [comment]
AFAIK modified snippets are kept in the browser's LocalStorage. It's up to the user to delete them if necessary.
