### ISSUE TITLE
UI editor "white box" at slow load when syntax on

### ISSUE THREAD

**Issue by bgadrian** [golang/tour#544]
In a specific scenario, the code editor is not loading properly. Instead of the full source code, only part of it is rendered and the missing code is replaced by an empty white box.

**Repro steps:**
* **slow connection** (dev tools - network conditions - Fast 3G)
* **Syntax on** (editor toggle)
* reload the page concurrency/4 (1+ pages of code)
* Chrome Version 67.0.3396.99 (Official Build) (64-bit) on Linux

Video:
![bug-intro-whitebox-tour](https://user-images.githubusercontent.com/830001/42249973-e751c4b2-7f36-11e8-839b-b5e0ebbe7aae.gif)

It works on any page (from what I can tell, ex: methods/4 ) that has more code then 1 visible editor page.

Any action that triggers the `$('.CodeMirror')[0].CodeMirror.refresh();` fixes the bug.
Clicking on the "white box" triggers the selection method which triggers a repaint, that adds the missing lines. 

It seems to be Chrome related, I tried to reproduce it in Firefox (60.0.2 (64-bit) both 3G options) following the same steps but with no luck. **I could use more confirmations** in order to pinpoint the issue.

It seems to be an async issue, maybe the textarea doesn't have the full code when CodeMirror kicks in.

**Comment by ALTree** [comment]
I can easily reproduce this (without even throttling the network, since my connection is not great) on Chrome

`Version 67.0.3396.87 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`

I can also confirm that it doesn't happen on Firefox.

**Comment by bgadrian** [comment]
![image](https://user-images.githubusercontent.com/830001/42270294-2155654a-7f89-11e8-98bb-7cb35608c086.png)
Code mirror debug

* **setValue and makeChangeInner** (change.text) receive the correct text and line numbers. The `doc.children` are calculated correctly but the end result DOM elements are missing (see the picture). I have lost the trace at `makeChangeSingleDoc` function. 

Updating codemirror at the 5.39 (latest) version doesn't seem to fix the issue, and I cannot find any similar issue on their github, so I guess I will create an issue there. From what I can see, 
1. there is a bug in the CodeMirror code
2. or the Tour is using the CodeMirror wrong somehow 
3. or is an **Angular** update bug (the resulting Divs of the codeMIrror are not propagated correctly in the DOM
