### ISSUE TITLE
tour: ru translation error in concurrency/5 page

### ISSUE THREAD

**Issue by din93** [golang/tour#549]
Context: https://go-tour-ru-ru.appspot.com/concurrency/5

один из его блоков case **не может будет запущен**, а затем

**Comment by bgadrian** [comment]
We should really group all the RU text issues in one issue, there are over 20 of reports, possibly many duplicates.

**Comment by ALTree** [comment]
I opened  #550 for general discussion on how to handle report of translation errors.

**Comment by ALTree** [comment]
Closing here. See #550 for reporting translations errors.
