### ISSUE TITLE
tour: replace "can" with "may"?

### ISSUE THREAD

**Issue by kedarmhaswade** [golang/tour#556]
Context: https://tour.golang.org/basics/6

This slide says:

> A function can return any number of results.

Does 

> A function may return any number of results.

sound better (or, is it more correct)?

**Comment by bgadrian** [comment]
I think "can" is a better representation, meaning it is not only "permitted" to return, but it is also "able" to do that. 

Also "can" is used in other official Go [docs like Effective Go](https://golang.org/doc/effective_go.html#multiple-returns)

So I would leave it as it is.

**Comment by kedarmhaswade** [comment]
I agree, it is minor.
