### ISSUE TITLE
tour: Remove semicolon.

### ISSUE THREAD

**Issue by kedarmhaswade** [golang/tour#557]
Context: https://tour.golang.org/basics/8

This slide says:
> The `var` statement declares a list of variables; as in function argument lists, the type is last.

What comes after the semicolon is unrelated to what comes before it. I believe that the following is simpler, more stylistic (, and correct?) replacement:
> The `var` statement declares a list of variables. As in function argument lists, the type comes last.

**Comment by ALTree** [comment]
I don't think the change you are suggesting is correct. The second sentence is actually related to the first one. The part that says "the type comes last" is directly linked to the first part of the sentence "The var statement declares...". I think a semicolon is perfectly fine there; replacing it with a colon would create an unnecessary and unpleasant separation between two sentences that are mean to be related.
