### ISSUE TITLE
tour: wrong description for "Range continued"

### ISSUE THREAD

**Issue by linamy85** [golang/tour#560]
Context: http://127.0.0.1:3999/moretypes/17

The original: If you only want the index, drop the ", value" entirely.
It should be changed into: drop the "_, " (or things equivalent) since we cannot use _ as value.

**Comment by ALTree** [comment]
Yeah I think that part is a little confusing. The code shows:

```
	for _, value := range pow {
		fmt.Printf("%d\n", value)
	}
```

and the text says

> If you only want the index, drop the ", value" entirely. 

but if you are looking at the code above, dropping the `, value` part doesn't make sense, and it won't give you "only the index".

**Comment by bgadrian** [comment]
I've made a fix, I hope it is ok https://go-review.googlesource.com/c/tour/+/125055 

![image](https://user-images.githubusercontent.com/830001/42963866-148c23c8-8b9e-11e8-9ade-1c3a18d639c7.png)
