### ISSUE TITLE
tour: [Code window lags while scrolling]

### ISSUE THREAD

**Issue by dyllandry** [golang/tour#563]
Context: http://127.0.0.1:3999/flowcontrol/7

When I scroll in the yellow code window the text gets hung up going down or up. Not sure what other details to include. As soon as I remove my fingers from the touch pad, the text window processes the "momentum" of the scroll just fine. Seems to only hang up when my fingers are in direct contact of the mouse pad. 

MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
Safari Version 11.1 (13605.1.33.1.2)

**Comment by bgadrian** [comment]
This reproduces with the syntax off too?

If the problem only appears with the syntax ON, can you test on a few other CodeMirror (the plugin that makes the syntax highlight) [demos to see if that happens](https://codemirror.net/demo/complete.html) too? This way we can see if is a problem with our scripts or theirs.

**Comment by dyllandry** [comment]
I've opened up the tour again today and cannot reproduce the issue. I do not know if that is clause for you to close this issue or not.

**Comment by dyllandry** [comment]
I can close it seems. Still new here.
