### ISSUE TITLE
tour: [Mistake]

### ISSUE THREAD

**Issue by Sergonizer** [golang/tour#565]
Context: https://go-tour-ru-ru.appspot.com/flowcontrol/5

In Russian, "the expression need not be surrounded" must be translated as "выражение нельзя заключать",  not "выражение не должно быть заключено", because it translates as "the expression doesn't need to be surrounded", so the meaning is another.

**Comment by Sergonizer** [comment]
I am sorry, I was incorrect. In this situation, the tranlation is correct.

**Comment by ALTree** [comment]
Ok, no problem. Closing.
