### ISSUE TITLE
tour: [+= used before introduced]

### ISSUE THREAD

**Issue by mbs** [golang/tour#566]
Context: https://tour.golang.org/flowcontrol/3

+= operator is used before introducing it in the tour.

(just learning Go here myself, so I have to assume "x += y" is equivalent to "x = x + y")

**Comment by bgadrian** [comment]
I don't think the operators are introduced, but I agree that the more expressive form `x = x + y` would be better for a newbie. 

PS: it is worse later on, you will encounter bit operators and a lot of math :(

**Comment by ALTree** [comment]
Thanks for the report. This is #436 (tour: briefly explain += operator), so I'm closing this in favour of the older thread.
