### ISSUE TITLE
Error in the text

### ISSUE THREAD

**Issue by yuri-gubsky** [golang/tour#567]
Context: https://go-tour-ru-ru.appspot.com/moretypes/15

The result of append is "tears"
Instead of "tears" you need a "slice"

**Comment by bgadrian** [comment]
Is an error in the RU text? from the left side?

**Comment by yury-gubsky** [comment]
Yes, this is in the Russian version of the site on the left.
I forgot to send you a screen, and now I attach a link to the screen - https://ibb.co/eUrrw8.
Sorry for the bad English, I translated through an interpreter, I'm Russian.

**Comment by ALTree** [comment]
This is fixed in the last version of the ru tour, AFAICT https://go-tour-ru-ru.appspot.com/moretypes/15, so I'm closing this issue.
