### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION] out of memory

### ISSUE THREAD

**Issue by krasincos** [golang/tour#578]
Context: https://tour.golang.com/moretypes/8

when I try execute example code snippet, I get next exception:
`fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc225c2, 0x16)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc420100000, 0x1f0000, 0xc41fffbf00, 0x1027058)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1001fa0, 0x1f0000, 0x7f1fe61d33a0)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1001fa0, 0xf5, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x1001fa0, 0xf5, 0x1027068, 0x7fffedfedc00)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x1001fa0, 0xf5, 0x410100, 0xc41fff96ff)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x1001fa0, 0xf5, 0x7fffed010100, 0x4133ac)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x1e8480, 0x450001, 0x7f1fe61cd6c8)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1175

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc420041c10 sp=0xc420041c08 pc=0x452ce0
runtime.mallocgc(0x1e8480, 0xba6b40, 0xbf6501, 0xc420070510)
	/usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc420041cb0 sp=0xc420041c10 pc=0x40fae2
runtime.newobject(0xba6b40, 0xc144c3)
	/usr/local/go/src/runtime/malloc.go:839 +0x38 fp=0xc420041ce0 sp=0xc420041cb0 pc=0x40fd88
cmd/compile/internal/gc.init()
	/usr/local/go/src/cmd/compile/internal/gc/gsubr.go:40 +0x14e fp=0xc420041f38 sp=0xc420041ce0 pc=0xb3bc2e
cmd/compile/internal/amd64.init()
	<autogenerated>:1 +0x4d fp=0xc420041f48 sp=0xc420041f38 pc=0xb4b1ed
main.init()
	<autogenerated>:1 +0x4b fp=0xc420041f88 sp=0xc420041f48 pc=0xb74b2b
runtime.main()
	/usr/local/go/src/runtime/proc.go:186 +0x1ca fp=0xc420041fe0 sp=0xc420041f88 pc=0x42ae9a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420041fe8 sp=0xc420041fe0 pc=0x4556b1
`
The interesting fact is when I modify code a little (even insert empty line) code executes fine

**Comment by ALTree** [comment]
Closing as a dup of  #541
