### ISSUE TITLE
tour: Suggested print 'needInt(Big)' overflows integer

### ISSUE THREAD

**Issue by hkra** [golang/tour#58]
Context: https://tour.golang.org/basics/16

The explanation of numeric constants says, "Try printing `needInt(Big)` too." However, attempting to do so results in the following compiler error.

```
# command-line-arguments
./compile34.go:16: constant 1267650600228229401496703205376 overflows int

Program exited: exit status 2
```

Is this the expected behavior? If the goal was just to show that numeric constants can hold really big numbers, I'm sure there's a better way to do that than a compiler error and no explanation :)

**Comment by hkra** [comment]
Please disregard this issue. Took a while for that last line to sink in.

**Comment by pramodshinde** [comment]
@hkra What was your finding on this? How can I print `Big`?

**Comment by hkra** [comment]
@pramodshinde the point is that you cannot because the value of Big is too large to pass as an int.
