### ISSUE TITLE
The example should be Println instead of Pizza

### ISSUE THREAD

**Issue by Chuseuiti** [golang/tour#592]
Context: https://tour.golang.org/basics/3

I believe that the word Pizza shouldnt be on this page and instead it should be Println.

**Comment by ALTree** [comment]
It's just an example, any symbol would be fine, it doesn't need to exist. Also changing it to `Println` would be wrong, because the following sentence would become

> println and pi do not start with a capital letter, so they are not exported. 

But actually `println` exists, and it works, it's a predefined function: https://golang.org/ref/spec#Predeclared_identifiers

**Comment by Chuseuiti** [comment]
thanks for the clarification!

**Comment by ALTree** [comment]
Closing here, then.
