### ISSUE TITLE
tour: error when running /basics/3

### ISSUE THREAD

**Issue by 16c7x** [golang/tour#594]
Context: https://tour.golang.org/basics/3

prog.go:9:14: cannot refer to unexported name math.pi
prog.go:9:14: undefined: math.pi

Program exited.

**Comment by ALTree** [comment]
This is expected, it's in the accompanying text:

>  Run the code. Notice the error message.
> To fix the error, rename math.pi to math.Pi and try it again. 

it's to show that lower-case idents are not exported.
