### ISSUE TITLE
Does not show correct time

### ISSUE THREAD

**Issue by krskv** [golang/tour#598]
Context: https://tour.golang.org/flowcontrol/11

The t variable gives me that time:
2009-11-10 23:00:00 +0000 UTC m=+0.000000001
That's why it's always evening for me=)

**Comment by ALTree** [comment]
Thanks for the report.

On the slide before:

> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader. 

So this is working as intended. Closing here.
