### ISSUE TITLE
tour: [default code run: process took too long]

### ISSUE THREAD

**Issue by cooladam201212** [golang/tour#602]
Context: https://tour.golang.org/basics/8

The default code in basics/8 returns 

```
package main

import "fmt"

var c, python, java bool

func main() {
	var i int
	fmt.Println(i, c, python, java)
}
```
But after I add `return` upon the close bracket, it returns the right output.

**Comment by bgadrian** [comment]
I can confirm the bug, I think is a cache issues, the same code returns t he same error on t he playground too.

I thought that these issues were supposed to be solved by https://github.com/golang/go/issues/26926

![image](https://user-images.githubusercontent.com/830001/45476730-68e27500-b748-11e8-8314-bfeab0eebf6f.png)

**Comment by ALTree** [comment]
It was a caching issue but it's now solved, closing.
