### ISSUE TITLE
tour: typo "sized"

### ISSUE THREAD

**Issue by yogeshagr** [golang/tour#605]
Context: https://tour.golang.org/basics/11

Hi Team,

First of all thank you very much for creating a wonder full golang tour. I am really enjoying it :)
I just noticed a typo at the last line of https://tour.golang.org/basics/11, with "sized", shouldn't it be "signed". Please check and correct me if I am wrong.

Please review the PR for the fix: https://github.com/golang/tour/pull/606

Thank you.

**Comment by ALTree** [comment]
Thanks for the report. 

This is actually correct as it is. A "sized" type is one of the named types with explicit width (e.g. int64).

Closing here, since the wording is correct.

**Comment by yogeshagr** [comment]
@ALTree Apologise for raising the incorrect issue. Thanks for the correction and explaining about the "sized" named types.
