### ISSUE TITLE
tour: imports.go Printf call needs newline character

### ISSUE THREAD

**Issue by acrophain** [golang/tour#615]
Context: https://tour.golang.org/basics/2

VERSION INFO:
at cmd window outside vagrant I'm running 
     go version go1.11 windows/amd64

using go install inside Vituralbox vagrant for Ubuntu, the go version command 
vagrant@precise64:/vagrant/go/src/tour_imports$ go version
go version go1

```
vagrant@precise64:/etc$ go env
GOROOT="/usr/lib/go"
GOBIN=""
GOARCH="amd64"
GOCHAR="6"
GOOS="linux"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CGO_ENABLED="1"
 ```

This is what I did:
I typed the imports.go example into nano tour_imports.go
then : go install
then executed on the command line: tour_imports

Very minor issue. As a suggestion:
The imports.go example, when run in a unix environment command line, does not have a newline character at the end of the Printf function, this causes the cursor string to appear to be part of the output.

`fmt.Printf("Now you have %g problems.", math.Sqrt(7))` displays as:
```
vagrant@precise64:/vagrant/go/src/tour_imports$ tour_imports
Now you have 2.6457513110645907 problemsvagrant@precise64:/vagrant/go/src/tour_imports$
```

but  `fmt.Printf("Now you have %g problems.\n", math.Sqrt(7))` displays as
```
vagrant@precise64:/vagrant/go/src/tour_imports$ tour_imports
Now you have 2.6457513110645907 problems.
```

**Comment by ALTree** [comment]
Thanks for the report. I've sent a fix at [CL 138615](https://go-review.googlesource.com/c/tour/+/138615).
