### ISSUE TITLE
tour: [Spanish link is not working]

### ISSUE THREAD

**Issue by PedroEscudero** [golang/tour#618]
The link https://go-tour-es.appspot.com/ (translation for Spanish) is not working. 

File with the wrong link: https://github.com/golang/tour/blob/master/content/welcome.article

**Comment by ALTree** [comment]
Thanks for the report. This was already reported as #596. 

Unfortunately we don't control or deploy the tour translations, they're maintained by external contributors; we just link them. Maybe the spanish tour will come back online in the future. I would ping the maintaner, but I don't have an email address...

Anyway, closing as a dup of #596.

**Comment by cyncyncyn** [comment]
> Thanks for the report. This was already reported as #596.
> 
> Unfortunately we don't control or deploy the tour translations, they're maintained by external contributors; we just link them. Maybe the spanish tour will come back online in the future. I would ping the maintaner, but I don't have an email address...
> 
> Anyway, closing as a dup of #596.

Hi @ALTree , who is the mantainer? Is there any repo to collaborate?
Thanks!
