### ISSUE TITLE
tour: possible spelling mistake

### ISSUE THREAD

**Issue by psaradhi** [golang/tour#62]
Context: https://tour.golang.org/basics/11

The last statement states "When you need an integer value you should use int unless you have a specific reason to use a **_sized_** or unsigned integer type."  

Did you mean "signed"  instead of sized ?

**Comment by wjh** [comment]
No. It should indeed be "sized", as instead of ``int`` one can write ``int16`` (which would be sized) or ``uint`` which would be unsigned, or ``uint16`` which would be both sized and unsigned.

**Comment by robphoenix** [comment]
This can be closed, unless @wjh is mistaken. @adg @broady @rakyll
