### ISSUE TITLE
tour: Typo in the "Slice defaults" section.

### ISSUE THREAD

**Issue by Ahmkel** [golang/tour#623]
Context: https://tour.golang.org/moretypes/10

I think there is a typo in the "Slice defaults" section in the sentence:
"The default is zero for the low bound and the length of the slice for the high bound."

shouldn't it be:
"The default is zero for the low bound and the length of the array for the high bound."

because the high bound is the length of the original array we are slicing from.

**Comment by ALTree** [comment]
Thanks for the report. This was reported in #182 (and there's some discussion there). I'm closing this thread in favour of the older one.
