### ISSUE TITLE
tour: "Run" stalls with "Waiting for remote server"

### ISSUE THREAD

**Issue by adtm** [golang/tour#627]
Running the `basic-packages` returns "Internal Server Error" at the HTTP response.
In the `welcome-hello` everything is fine.

I'm using Mac OS X on Chrome, Opera.
If any clarification is needed - tell me, will provided what I'm able.

**Comment by fedir** [comment]
:+1: Same issue. And after it breaks.
![image](https://user-images.githubusercontent.com/306586/46801527-30d84d00-cd5b-11e8-804d-81cfdfa4e48e.png)

**Comment by fedir** [comment]
P.S. Even on the main page it bugs in the same way. Here's a test from my phone (4G connection).

![image](https://user-images.githubusercontent.com/306586/46802953-27e97a80-cd5f-11e8-8593-d29a764fbdd9.png)

**Comment by bweston92** [comment]
Getting same.

![screenshot_20181011_151019](https://user-images.githubusercontent.com/1764057/46810146-f2955a80-cd67-11e8-86eb-c917130d96a2.png)

**Comment by bweston92** [comment]
It is now working for me, is this closable?
