### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by seobadazz** [golang/tour#63]
Context: https://tour.golang.org/flowcontrol/11

Change the title above to describe your issue and add your feedback here, including code if necessary

**Comment by alebaffa** [comment]
@seobadazz please change the title and description of this issue explaining your problem otherwise it's going to be closed, i guess.

**Comment by robphoenix** [comment]
Looks like this can probably be closed @adg @seobadazz
