### ISSUE TITLE
tour: [Sample code does NOT compile]

### ISSUE THREAD

**Issue by 0syntrax0** [golang/tour#632]
Context: https://tour.golang.org/moretypes/18

Sample code does NOT compile. It returns this error `prog.go:6:1: missing return at end of function`

**Comment by ALTree** [comment]
Hi, at that page there's an exercise. The accompanying text says (first sentence):

> Implement Pic.

The code on the right needs to be completed to make it compile. I'm closing this issue, since I don't believe this is a bug.
