### ISSUE TITLE
tour: Add explicit run command when running offline ?

### ISSUE THREAD

**Issue by arjunbazinga** [golang/tour#633]
Context: https://tour.golang.org/welcome/3

> To run the tour locally install and run the tour binary: go get golang.org/x/tour tour 

could be converted to 

To run the tour locally install and run the tour binary: go get golang.org/x/tour; tour 
 
or even

"To run the tour locally, install using ` go get golang.org/x/tour`, and  then run the tour binary by calling `tour`

**Comment by jschulenklopper** [comment]
Currently, the page at https://tour.golang.org/welcome/3 reads:

> To run the tour locally install and run the tour binary: go get golang.org/x/tour tour The tour program will open a web browser displaying your local version of the tour.

The text is currently rendered as one sentence in the normal text font style, and not as separate lines like (in the HTML source):

> To run the tour locally install and run the tour binary:
> `go get golang.org/x/tour`
> `tour`
> The tour program will open a web browser displaying your local version of the tour.

Additionally, the `tour` command doesn't (always?) work. It'd better be replaced by `go tool tour`, as mentioned by @bradfitz in https://github.com/golang/go/issues/24819. Not sure whether it was working earlier but now it does (locally, on my macOS machine).

**Comment by jschulenklopper** [comment]
OK, closed... but not solved? Also https://github.com/golang/go/issues/24819 is still open (and the issue in the tracker here is more appropriate?)
