### ISSUE TITLE
tour: newline missing from default switch case

### ISSUE THREAD

**Issue by joshu017** [golang/tour#642]
Context: https://tour.golang.org/flowcontrol/9

Hello,

Thanks for the great tour of Go!  This is super nitpicky, but I read that no issue is too small so here goes: In the switch statement example, the first two cases print with a newline but the default case doesn't.  For consistency I would recommend adding newline to the printf on line 19:

fmt.Printf("%s.\n", os)

Thanks again!
-Josh

**Comment by ALTree** [comment]
Thanks for the report. 

While you won't notice the missing `\n` when running the program in the browser (since the web-editor puts a newline at the end of the input), it's better to be consistent with the newlines. I've sent [CL 148617](https://go-review.googlesource.com/c/tour/+/148617).

**Comment by joshu017** [comment]
Thanks!  I am actually reproducing all of the tour programs in command line for practice, which is how I noticed - have a great day!
-Josh
