### ISSUE TITLE
tour: example /basics/1 rand function always return 1

### ISSUE THREAD

**Issue by dnuske** [golang/tour#648]
Context: http://127.0.0.1:3999/basics/1

Pretty much explained in the title, no matter how many times I run the example I always get the result `My favorite number is 1`.

**Comment by bgadrian** [comment]
Please read the text on the right of the screen/page:

> Note: The environment in which these programs are executed is deterministic, so each time you run the example program rand.Intn will return the same number. (To see a different number, seed the number generator; see rand.Seed. Time is constant in the playground, so you will need to use something else as the seed.)

It is a on-purpose limitation of the tour.golang which the devs do not want to change, even if it produces a lot of confusion among the new users.

You can close this issue if you understand now.

**Comment by dnuske** [comment]
thank you for the response

**Comment by king7777** [comment]
Yes
