### ISSUE TITLE
tour: "go tool tour" and "go get golang.org/x/tour/gotour" aint working

### ISSUE THREAD

**Issue by kakulukia** [golang/tour#653]
Im on ubuntu, installed go via its package manager and have no tool called tour. So i installed "golang.org/x/tour/gotour" but this only gave my a binary telling me that "golang.org/x/tour/gotour has moved to golang.org/x/tour". 

How hard can it be to have a working tour of go for people who are interested in the language?
I saw a lot of issues with that, but none about even the mentioned "go get golang.org/x/tour/gotour" not working so i created a new one.

Its a real pity nobody cares about first time user experience. :(

The tour itself is great tho!

**Comment by ALTree** [comment]
Thanks for the report.

The tour offline instructions, in the tour welcome, says:

>  To run the tour locally install and run the tour binary: 
>   go get golang.org/x/tour

which is the rigth path. You wrote:

> So i installed "golang.org/x/tour/gotour"

where did you find instructions to do so (with that outdated path)? We may have forgotten to update all the help docs.

**Comment by kakulukia** [comment]
I cant find it anymore .. forget about it.
Sorry!
