### ISSUE TITLE
tour: "Exercise: Fibonacci closure" sample currently returns an error

### ISSUE THREAD

**Issue by Mariano76** [golang/tour#667]
Context: https://tour.golang.org/moretypes/26

Running the example "exercise-fibonacci-closure.go" inside the online tour currently returns an error.

Error returned:
prog.go:8:1: missing return at end of function

**Comment by bgadrian** [comment]
Hello,

Please read the left description, is an Exercise, as in you have to write code to make it work! 

If you understand you can close the ticket, thanks!

**Comment by Mariano76** [comment]
Many thanks! Did not read correctly the description. Sorry! :-(

**Comment by MrWoodward** [comment]
Maybe add a comment in the function that says "Insert your fibonacci code here"?
