### ISSUE TITLE
Tour: wong format in welcome/3 and welcome/4

### ISSUE THREAD

**Issue by OlingCat** [golang/tour#677]
The format in [welcome/3](https://tour.golang.org/welcome/3) and [welcome/4](https://tour.golang.org/welcome/4) is missing.

Should we replace stand-alone `appengine:` with newline in [welcome.article#L72-L108](https://github.com/golang/tour/blob/master/content/welcome.article#L72-L108)?

**Comment by ALTree** [comment]
This was fixed recently, so closing here.
