### ISSUE TITLE
tour: [prog.go:6:1: missing return at end of function]

### ISSUE THREAD

**Issue by tomxlawson** [golang/tour#682]
Context: https://tour.golang.org/moretypes/18

error:
prog.go:6:1: missing return at end of function

correct code is here:
https://github.com/benoitvallon/a-tour-of-go/blob/master/exercise-slices.go

**Comment by ALTree** [comment]
That's an exercise, so it'll not compile unless you fill in the code. This is explained in the text on the left. Closing here.
