### ISSUE TITLE
"as is Pi, which is exported from the math package." Implies math.Pizza is a thing - use Intn instead of Pizza!

### ISSUE THREAD

**Issue by dchahla** [golang/tour#683]
"as is Pi, which is exported from the math package...." Implies math.Pizza is a thing.

You shall either amend the tour's documentation or remove Pizza.

![image](https://user-images.githubusercontent.com/2994164/51417690-deba7b00-1b44-11e9-8753-267918f1b455.png)

**Comment by ALTree** [comment]
>"as is Pi, which is exported from the math package...." Implies math.Pizza is a thing.

I don't think it does. The "which" in the sentence "as is Pi, which is exported by math" refers to Pi, not to both Pi and Pizza.
