### ISSUE TITLE
slight typo/bug in execution? 

### ISSUE THREAD

**Issue by nlangufl** [golang/tour#693]
Context: https://tour.golang.org/moretypes/5
If vertex p printing as &{1 2} is intententional, close this. However, the previous page was about pointers and how to interact with them, so it seems odd to print a pointer instead of the value pointed to by said pointer in the context of the tour.

Code, as is current.
```
package main

import "fmt"

type Vertex struct {
	X, Y int
}

var (
	v1 = Vertex{1, 2}  // has type Vertex
	v2 = Vertex{X: 1}  // Y:0 is implicit
	v3 = Vertex{}      // X:0 and Y:0
	p  = &Vertex{1, 2} // has type *Vertex
)

func main() {
	fmt.Println(v1, p, v2, v3)
}
```

output:
```
{1 2} &{1 2} {1 0} {0 0}

Program exited.
```
I'm not sure if the Vertex p printing as a reference value is intentional, but if not the edited code at line 17 should be `fmt.Println(v1, *p, v2, v3)`

**Comment by ALTree** [comment]
This is definitely intentional. The comment says `// has type *Vertex`, after all. The goal of the code is also to show how those value are printed (and the difference between a type and a pointer type).

**Comment by nlangufl** [comment]
@ALTree word, thx
