### ISSUE TITLE
tour: Can't install tour

### ISSUE THREAD

**Issue by mikeweilgart** [golang/tour#702]
Context: https://tour.golang.org/welcome/3

Here's what I get on my Mac:

```
$ go get golang.org/x/tour
# golang.org/x/tools/internal/module
term/gobook/src/golang.org/x/tools/internal/module/module.go:350: undefined: sort.Slice
# golang.org/x/tools/go/internal/packagesdriver
term/gobook/src/golang.org/x/tools/go/internal/packagesdriver/sizes.go:94: undefined: types.SizesFor
# golang.org/x/tools/go/internal/gcimporter
term/gobook/src/golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
```

```
$ go version
go version go1.7.1 darwin/amd64
```

This is on Mac OS 10.11.6, though I don't think that's relevant.

**Comment by ALTree** [comment]
Thanks for reporting this.

Go 1.7 is very old, and no longer supported. Please nuke your current Go installation and then upgrade  to 1.11.5, then try again to install the tour.

I'm closing this issue, but feel free to comment if you're still getting tour errors after the upgrade.
