### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pangodream** [golang/tour#703]
Context: https://tour.golang.org/welcome/2

The link https://go-tour-es.appspot.com/ is broken

Although the nissue was closed on Nov 5th 2018 **the link remains broken**

**Comment by ALTree** [comment]
Thanks for report,

The link was changed recently (838ce51196a7e9f9bff83402caf4f678dc0f0d75). As soon as the new tour will get deployed, it'll be fixed. Closing here, since there's nothing else to do.
