### ISSUE TITLE
tour: [Shows wrong answer on change of code]

### ISSUE THREAD

**Issue by Rumata888** [golang/tour#705]
Context: http://127.0.0.1:3999/flowcontrol/10
Running on ubuntu 16.04 LTS. Today is saturday, so  the initial code just printed "Today". After changing "time.Saturday" to "time.Sunday" in switch initialization it printed "Too far away" instead of "Tomorrow"

**Comment by ALTree** [comment]
Please note (in the text beside the code):

> Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader. 

For caching reasons, the time is frozen on the playground. So any time-related code will run as the current time is 2009-11-10 23:00:00 UTC.

Closing here, since there's no bug.
