### ISSUE TITLE
modification of the value in a variable, in the handling of pointers

### ISSUE THREAD

**Issue by CesarDelgadoM** [golang/tour#706]
Context: https://tour.golang.org/moretypes/1

at what time the value of variable j is being modified?

package main

import "fmt"

func main() {
	i := 34
	j := 1200

	//declare a pointer
	p := &i
	fmt.Println(p, " ", *p, " ", i, " ", &i)

	p = &j
	fmt.Println(p, " ", *p, " ", j, " ", &j)
	
	*p = i
	
	sum:= *p + j
	fmt.Println(*p, "+", j, "=", sum)
}

**Comment by WeirdMagician** [comment]
At this line
*p = i
the variable j got modified

*p  refers to the "value at the address p pointing to"
so after executing the above line indirectly (i is equal to j) because assigning i value to j
the expected output is 34 + 34 = 68
