### ISSUE TITLE
tour: outdated tour version for korean translation

### ISSUE THREAD

**Issue by Lisphy** [golang/tour#709]
Context: https://tour.golang.org/welcome/2

Change the title above to describe your issue and add your feedback here, including code if necessary

---------------------------

Hello, tour site team.

Our team needed Go language how to work and process internal, So we have found this site.
and we have translated those for sharing the knowledge.

I have translated korean from original (current)lastest english version, today is 13/2/2019 GMT+8

So, How can I contribute to your team?
Could I fork it new branch of my own github?

If you have another process or a guide, Please let me know anything.

Thank you very much

**Comment by ALTree** [comment]
Hi, and thanks for translating the tour!

The tour translations, unlike the original (English) tour, are not directly deployed by people in the Go team; instead they are controlled by the people that did the translation, deployed by them on appspot, and then linked in the welcome page of the official English tour.

You can find information about this process here:

https://github.com/golang/tour/blob/master/TRANSLATE

One minor issue here is that we already have an (outdated) Korean translation of the tour, at https://go-tour-kr.appspot.com; so you won't be able to claim the suggested tour-kr.appspot url. 

To solve this issue, you could either:

1. Send a push request to the korean translation repository with your translation of the latest version of the tour, here: https://github.com/atomaths/go-tour-kr, and ask the owner to re-deploy your version at the tour-kr.appspot.com url they control. This way, we'll have an update korean version at the old appspot url already linked in the English version. This requires the collaboration of the current owner of the korean translation, clearly.

2. If the current owner of tour-kr.appspot.com is not willing to accept push requests, or you can't reach them, you could register a new, different appspot url (e.g. tour-korea.appspot.com ?) and deploy there your updated translation (following the instructions I linked above). Then, when your version is online, we can change the link to the korean translation to point to your version.

**Comment by umi0410** [comment]
@ALTree Hi, I'm thinking about contributing Korean translation of tour.
But I have no idea about how to create a new appspot url like tour-xx.appspot.com as you said.
according to this [appengine docs](https://cloud.google.com/appengine/docs/standard/python/getting-started/deploying-the-application#viewing_your_deployed_application)  we can create a new url like https://PROJECT_ID.REGION_ID.r.appspot.com
Can you give me an idea?
