### ISSUE TITLE
tour:Corrupting GO Installation, system variables, & environmental variables.

### ISSUE THREAD

**Issue by ghost** [golang/tour#73]
1. What version of Go are you using (go version)? GO 1.7
2. What operating system and processor architecture are you using? WINDOWS 7 Professional, 4GB RAM, 64BIT OS, intel core i5, 2.50GHZ
3. What did you do? installed go, started to work through GO's beginning steps, 
4. What did you expect to see? the go tour but locally.  
5.  What did you see instead? A broken web-page, then a broken environment & shell & GO.

Here are some bins that may help illustrate this problem I'm personally experiencing.
https://ghostbin.com/paste/5rrcr
https://ghostbin.com/paste/2u5jq
https://ghostbin.com/paste/5feuc
https://ghostbin.com/paste/yhcwt

**Please help**, this is such an issue, I have to repair GO at any attempt of **the go tour locally.** 
I've tried gotour which, does as the title of this post says, I am the only one having this problem. I had @mohae help me on irc #go-nuts, but he replicated the problem without my issue. 

> [20:42]   mohae   I use W10 Pro, and just upgraded to 1.7 and everything works as expected

Let me repeat that running the go tool tour, corrupts go, deletes the go.exe, makes changes to PATH, gopath, & other stuff that is scary, & I have to use the msi to do a repair. Here's a big future thanks.

**Comment by mohae** [comment]
I was not able to replicate the issue.  Both Go and the `go tool tour` command work as expected.  I tried to replicate @joses-soul's issue with 1.6.3, 1.7, and 1.71 and was unable to.

**Comment by jimmywilk** [comment]
Hola jose

**Comment by ALTree** [comment]
Very old issue, difficult to reproduce and we can't ask questions to OP because they are no longer registered... closing here, since it's hard to see what else we could do.
