### ISSUE TITLE
tour: [Option to change language]

### ISSUE THREAD

**Issue by alifkaputra** [golang/tour#731]
Context: https://tour.golang.org/

Can u add an option to change the language on navigation menu or hamburger menu? So that i can change the language anywhere in the web (https://tour.golang.org/)

**Comment by ALTree** [comment]
I think it would waste a lot of space for little gain. We link to the tour translations at the beginning of the tour; most people then go on with the English version or click on their language translation, and I think they'd be pretty annoyed to see the full list of translation on every page.

Closing here.
