### ISSUE TITLE
tour: Switch with no condition - Remind the freezed time

### ISSUE THREAD

**Issue by MichelJe** [golang/tour#737]
Context: https://tour.golang.org/flowcontrol/11

Please include a reminder that the time on the tool system is freezed to 2009-11-10 23:00:00 +0000 UTC m=+0.000000001.

(I was wondering why he didn´t say Good morning)

**Comment by ALTree** [comment]
Thanks for the report.

There's a warning about this on the page immediately before that one:

> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader

I think it would get tiring to repeat that on every slide. We say that in several places, but it two occurrences of `time` calls occurs in the span of two slides I don't think we need to repeat the warning on both pages.

Closing here.

**Comment by MichelJe** [comment]
Hi Alberto,

 

works for me J

 

Regards Michel

 

Von: Alberto Donizetti [mailto:notifications@github.com] 
Gesendet: Samstag, 18. Mai 2019 12:01
An: golang/tour
Cc: MichelJe; Author
Betreff: Re: [golang/tour] tour: Switch with no condition - Remind the freezed time (#737)

 

Thanks for the report.

There's a warning about this on the page immediately before that one:

Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader

I think it would get tiring to repeat that on every slide. We say that in several places, but it two occurrences of time calls occurs in the span of two slides I don't think we need to repeat the warning on both pages.

Closing here.
