### ISSUE TITLE
tour: The rand.Intn example introducing 'packages' is deterministic.

### ISSUE THREAD

**Issue by fragmede** [golang/tour#75]
Context: https://tour.golang.org/basics/1

Hi,

Just want to note that, coming from a C programming background, the shortcut of plugging time into the seed is still deterministic given how the app engine run time environment is configured. (Lower bits of time.Now().UTC().UnixNano() are all zero.)

The text in parens on the page could be read misleadingly, so different example could be chosen or the comment even more explicit.

Attached works as expected locally, but not on https://tour.golang.org/basics/1

[foo.go.txt](https://github.com/golang/tour/files/466137/foo.go.txt)

**Comment by robphoenix** [comment]
This is fixed by https://github.com/golang/tour/commit/d844dc7a157c5d2e92bccc9732530c37bc7ef33b

@fragmede @adg This issue can be closed.
