### ISSUE TITLE
tour: fmt.Print should be fmt.Printf in the description

### ISSUE THREAD

**Issue by kpym** [golang/tour#768]
Context: https://tour.golang.org/methods/14

The code use `fmt.Printf` but in the description the ending `f` is missing.

**Comment by ALTree** [comment]
Thanks for reporting this. I don't think this is a typo. See my comment at https://go-review.googlesource.com/c/tour/+/175597

**Comment by kpym** [comment]
Thanks for considering this issue. I agree with your logic. 

But still, it's a little disturbing to have `print` and `printf` for a newcomer. So maybe the `print` function in the example can be replaced by another one that takes `interface{}` as parameter?
