### ISSUE TITLE
tour: [https://tour.golang.org/concurrency/9 misleading by GOMAXPROCS(1)]

### ISSUE THREAD

**Issue by chalvern** [golang/tour#771]
This may not be a big deal, but it will bring confusion to beginners. On the web of https://tour.golang.org/concurrency/9, the code would RUN NORMALLY if `c.mux.Lock()` and `c.mux.Unlock()` are commented in `func (c *SafeCounter) Inc(key string)`, as follows: 

```go
func (c *SafeCounter) Inc(key string) {
	// c.mux.Lock()
	// Lock so only one goroutine at a time can access the map c.v.
	c.v[key]++
	// c.mux.Unlock()
}
```

It seems like the official TOUR SERVER is single core limited so that the problem of concurrency will not happen.

**Comment by ALTree** [comment]
Those lines are not commented in the original code.

My guess is that someone using the same browser on the same computer changed them to experiment with the code. The editor locally caches changes. You can click on the "reset" button on each page to restore it to the original status.

Closing here.

**Comment by chalvern** [comment]
@ALTree Thanks for your reply. But if `c.mux.Lock()` and `c.mux.Unlock()` are commented in func (c *SafeCounter) Inc(key string), I believe that the code should report an  error instead of running normally...

**Comment by ALTree** [comment]
Ah, I misunderstood your report. What you're saying is that *you* commented the mutex calls and expected the compiler and or runtime to raise an error. Sorry for the confusion.

To answer your question: this is not actually possible. The Go runtime doesn't "know" that the mutex is supposed to protect the map itself. So it's the programmer that is in charge of locking and unlocking the variables that the mutex was created to protect before and after each access. 

In general, Go does not (and cannot) guarantee data-race free code at a compiler level. What Go programmers usually do is test their code with the `-race` flag enabled (see https://blog.golang.org/race-detector). The race detector can detect and report data races at runtime.

**Comment by chalvern** [comment]
@ALTree Thanks your detailed explanation. After my verification, the code can report an error if GOMAXPROCS is set as 3.

```go
func main() {
	runtime.GOMAXPROCS(3)
	// other lines
}
```

As an experienced Golang developer, I agree that `-race` is a obvious way to check the data-race. But It would be better reporting errors of `concurrent map writes` for beginners in https://tour.golang.org/concurrency/9.
