### ISSUE TITLE
malformed sentence.

### ISSUE THREAD

**Issue by terrybytes** [golang/tour#773]
Context: https://tour.golang.org/concurrency/4

what is the purpose/meaning of "after" in this string?...

"A sender can close a channel to indicate that no more values will be sent. Receivers can test whether a channel has been closed by assigning a second parameter to the receive expression: after"

**Comment by ALTree** [comment]
Hi, read it like this:

> after `v, ok := <-ch`,  ok is false if there are no more values

In other terms, it's saying that after the `v, ok := <-ch` assignment is executed, `ok` will be false if etc etc

Closing here.

**Comment by terrybytes** [comment]
ah, i see. it was the formatting that confused me.

"after" could have been "after:" or perhaps been on the same line as the example.

thnx
