### ISSUE TITLE
tour: Kazakh Translations for Go Tour

### ISSUE THREAD

**Issue by kergalym** [golang/tour#78]
Context: https://tour.golang.org/welcome/2
Can I start translate it into my native language? It would help me a lot in learning Go

**Comment by alebaffa** [comment]
HI @kergalym, i suggest you to first check in the mailing list [golang-nuts](https://groups.google.com/forum/#!forum/golang-nuts) and ask if other people are already working on it. I did like this when I translated the italian tour 😄. You will also probably find someone willing to review your translation and give you other help in general.
If nobody is working on it already, go for it 👍

**Comment by ALTree** [comment]
We don't manage tour translation, but if you do one you can ping us and we'll add the link to that page. In the meantime... closing this issue. Thanks.
