### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by RAVIROC** [golang/tour#786]
Context: https://tour.golang.org/flowcontrol/8

Change the title above to describe your issue and add your feedback here, including code if necessary
package main

import (
	"fmt"
)

func Sqrt(x float64) float64 {
}

func main() {
	fmt.Println(Sqrt(2))
}

**Comment by ALTree** [comment]
Not an issue, closing.
