### ISSUE TITLE
tour: wrong return value of time.Now().Weekday()

### ISSUE THREAD

**Issue by yongkui** [golang/tour#797]
Context: https://tour.golang.org/flowcontrol/10

In the example, if I add a line after  today := time.Now().Weekday()
	today := time.Now().Weekday()
	fmt.Println(today)

The output will be:

When's Saturday?
Tuesday
Too far away.

But today is Monday, not Tuesday. BTW, I am in China.

**Comment by teh-f00l** [comment]
I got Tuesday as well(writing this on a Thursday)

**Comment by khan19lc** [comment]
im on wedsnesday tge fourth

**Comment by khan19lc** [comment]
im in provo utah gmt

**Comment by khan19lc** [comment]
at my freand bentens house

**Comment by CornePlas** [comment]
The date / time is always: 2009-11-10 23:00:00 +0000 UTC m=+0.000000001. There is nothing wrong with the source code.

**Comment by ALTree** [comment]
yeah, this is also explained in the lesson text:

> Note: Time in the Go playground always appears to start at 2009-11-10 23:00:00 UTC, a value whose significance is left as an exercise for the reader. 

closing this, since it's working as expected.
