### ISSUE TITLE
tour: change to use int instead of map[string]int as c.v?

### ISSUE THREAD

**Issue by bluekvirus** [golang/tour#803]
Context: https://tour.golang.org/concurrency/9

With the use of a map and without using the sync.Mutex, the `go run` command will complain of multi-accessing to the map object directly.

Using an int in such a case won't cause a 'fatal' panic and will still run the program but just output incorrect result. (I believe this is what we wanted to showcase)

Also, in the web runtime, neither using a map nor an int var will cause incorrect result ever (doesn't matter if you use sync.Mutex or not) due to the single thread JS VM underneath. Which is another issue but can't seem to be addressable at all in the web runtime.

**Comment by ALTree** [comment]
I'm confused.

> With the use of a map and without using the sync.Mutex

But the code in the slide you linked does use `sync.Mutex` correctly.

> but just output incorrect result. (I believe this is what we wanted to showcase)

I believe that what we wanted to showcase is the how to correctly used a Mutex-ed map in a concurrent program, and that's what the code shows. What makes you believe that we wanted to showcase a bad output?

**Comment by bluekvirus** [comment]
Yeah, the code was correct, but as the code to demo the necessity of using
sync.Mutex is somehow not enough. That's what I meant.

`but just output incorrect result` (if sync.Mutex lines are removed)

I believe we do want to showcase the difference between using a sync.Mutex
and not using it in the playground tour. In current slide, removing the
sync.Mutex lines entirely will result in neither a 'fatal' panic nor
incorrect number.

Sorry about being too brief in previous message.

**Comment by ALTree** [comment]
Thanks for elaborating, I get your point now.

Your suggestion makes sense, but I'm not convinced we should do that.

The playground's nacl environment is quite limited, and many failure modes that are easily triggered on a physical machine are hard (or downright impossible) to set off on the playground. For this reason, historically – while it's true that sometimes explicitly showing a specific failure mode can be useful from a didactic point of view – we didn't bother showing the learner subtly-wrong code that triggers data-races or similar issues. Even when the examples work and a failure is triggered, they're often brittle on nacl.

So I don't think we should bother changing the code just to make it (hopefully) fail when someone edits the code removing the locks. We do this "try to run the code, look at the error, fix the code, run it again" in other lessons, but while it's okay for things like compile-time or runtime errors (that are deterministic), I wouldn't do this for data-races and other non-deterministic errors.

**Comment by bluekvirus** [comment]
Thanks for the writeup!

Yeah I agree in this case showing how to guard against racing access for
maps are more useful than just integers. I hope we can put the nacl
limitations as a note on the slide to encourage newcomers to run the
program on their local machines to see the difference.

**Comment by ALTree** [comment]
> I hope we can put the nacl limitations as a note on the slide

I'm a little reluctant to do this. We have been trying to keep the notes simple and strictly related to the lesson. I don't think we want to venture into a tangential explanation of the playground limitations. 

We put the "time is frozen" warning on a few pages since it's something that users can hit when running one of the code examples with `time` calls, on the code "happy path"; in this case we're talking about a missing data-race but it's not like we *guarantee* that a data race will corrupt the result or anything like that, so I don't feel it's worth confusing a beginner with an explanation of why the data race doesn't not corrupt the result and so on.

I'm closing this issue, since I believe we shouldn't change the lesson.
