### ISSUE TITLE
tour: Struct Literals playground populates with typo

### ISSUE THREAD

**Issue by j0rdnh** [golang/tour#823]
Context: https://tour.golang.org/moretypes/5

in the line of code that prints the variables, the pointer "p" doesn't have an asterisk in front of it so it prints it's addressed value with an ampersand like "&{1 2}"

**Comment by j0rdnh** [comment]
Also and issue on "Methods and pointer indirection"

**Comment by j0rdnh** [comment]
As well as on "Choosing a value or pointer receiver"

**Comment by ALTree** [comment]
Hi,

hum... this is clearly done on purpose, to show how pointers are printed. Not sure why you think it's a mistake. It's even called `p` and it has a comment that says `// this one is a pointer` to make the difference clear.

Closing here, since this is not a typo.
