### ISSUE TITLE
Problem to generate a random number in go tour

### ISSUE THREAD

**Issue by msenkiv** [golang/tour#829]
I'm trying to execute this code in play.golang. But the same just return 0.

package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	s1 := rand.NewSource(time.Now().UnixNano())
	r1 := rand.New(s1)
	fmt.Println(r1.Intn(10))
}

**Comment by murfel** [comment]
`time.Now()` is always the same in the playground as described in [the first lesson](https://tour.golang.org/basics/1).

**Comment by ALTree** [comment]
Yep, the playground environment is deterministic. Closing here.
