### ISSUE TITLE
tour: short variable declarations incompletely describe possible type annotation

### ISSUE THREAD

**Issue by ybakos** [golang/tour#835]
Context: https://tour.golang.org/basics/10

Inside a function, the := short assignment statement can be used in place of a var declaration with *implicit* type.

Should be:

Inside a function, the := short assignment statement can be used in place of a var declaration with *implicit or explicit* type.

We can substitute either:

```
var x = 42
```
or
```
var x int = 42
```
with
```
x := 42
```

**Comment by ybakos** [comment]
Or, perhaps it might best read "implicit or explicit" type, as we can substitute either:

```
var x = 42
```

or

```
var x int = 42
```
with

```
x := 42
```

**Comment by crisman** [comment]
Implicit type is where `x :=` can be used that `var x int =` can not be used.

I am not sure where the `var x = 42` suggested changes are as I do not see them in code history anywhere.  The current code does have an example with `k := 3` so I expect this request is covered.

Can be closed.
