### ISSUE TITLE
tour: Amend print statement to reflect order of created variables

### ISSUE THREAD

**Issue by whosthatknocking** [golang/tour#86]
Context: https://tour.golang.org/moretypes/5

Amending `Println` statement to reflect order of created variables makes code easier to follow,

Example, change,

```
fmt.Println(v1, p, v2, v3)
```

with,

```
fmt.Println(v1, v2, v3, p)
```

**Comment by robphoenix** [comment]
duplicate of https://github.com/golang/tour/issues/164

**Comment by robphoenix** [comment]
Though actually that is a dup of this, so I'll move my comment here, and suggest both be closed? @adg @rakyll @broady 

I would guess that they are printed to stdout this way to highlight the comparison between the struct `Vertex` and the pointer to the struct `*Vertex`.

**Comment by adg** [comment]
Correct. Thanks @robphoenix
