### ISSUE TITLE
Specifying how to run tour offline

### ISSUE THREAD

**Issue by SomtochiAma** [golang/tour#871]
Most people using the tour for the first time who have no programming experience might not understand how exactly to run the tour after getting the tour binary.

I can update the docs and make a PR for this if anyone else thinks this is needed

**Comment by slimlime** [comment]
I think this extant issue can now be closed ? The instructions now say how to run the tour (i.e. run the `tour` binary to get the web service running and similarly use a web browser to browse the local website )


However, the latest instruction gives yet another obsolete command 

`go get golang.org/x/tour`

https://github.com/golang/tour/issues/1218#issuecomment-875145650
