### ISSUE TITLE
tour: Correction to slice defaults wording

### ISSUE THREAD

**Issue by menehune23** [golang/tour#89]
Context: https://tour.golang.org/moretypes/10

The following:

> The default is zero for the low bound and the length of the slice for the high bound.

should probably be this, for clarity:

> The default is zero for the low bound and the length of the **referenced array** for the high bound.

(changes in **bold**)

since the length of the slice is not yet determined.

**Comment by bgadrian** [comment]
The sentence "The default is zero for the low bound and the length of the slice for the high bound." is also discussed in https://github.com/golang/tour/issues/182

**Comment by ALTree** [comment]
Closing as a dup of #182
