### ISSUE TITLE
tour:  missing output

### ISSUE THREAD

**Issue by bab9e9** [golang/tour#890]
Context: https://tour.golang.org/basics/11
After [Run] all I see is "Program exited.".

Code works correctly if executed locally:
C:\Users\bab9e\go\basic-types>basic-types
Type: bool Value: false
Type: uint64 Value: 18446744073709551615
Type: complex128 Value: (2+3i)

**Comment by bab9e9** [comment]
BTW I was running Firefox 72.0.1 64-bit, if that's relevant.

**Comment by epiwd** [comment]
Seems the cached version is incorrect; I get the same thing on Chrome. Changing the program slightly in the browser editor results in the correct output.

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.
