### ISSUE TITLE
tour: No output is displayed when you run

### ISSUE THREAD

**Issue by md-farhan-memon** [golang/tour#892]
Context: https://tour.golang.org/basics/11

The following code in the tutorial doesn't display anything when you run it.

```
package main

import (
	"fmt"
	"math/cmplx"
)

var (
	ToBe   bool       = false
	MaxInt uint64     = 1<<64 - 1
	z      complex128 = cmplx.Sqrt(-5 + 12i)
)

func main() {
	fmt.Printf("Type: %T Value: %v\n", ToBe, ToBe)
	fmt.Printf("Type: %T Value: %v\n", MaxInt, MaxInt)
	fmt.Printf("Type: %T Value: %v\n", z, z)
}
```

Please look into that.
![screencapture-tour-golang-org-basics-11-2020-01-24-14_37_39](https://user-images.githubusercontent.com/16094436/73057320-3c4f7900-3eb7-11ea-8f31-f4abf96cbaaf.png)

**Comment by willrazen** [comment]
Same thing with https://tour.golang.org/flowcontrol/6

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.
