### ISSUE TITLE
tour: does not produce output as is

### ISSUE THREAD

**Issue by jennievh** [golang/tour#893]
Context: https://tour.golang.org/basics/11

I can comment out any one of the three println lines and will see output when I click Run. with all 3 lines uncommented, no output is produced except "Program Exited."

Chrome browser Version 79.0.3945.117 (Official Build) (64-bit)
Identical results on Safari browser Version 13.0.4 (13608.4.9.1.4)
Macbook Pro running High Sierra macOS 10.13.6 (17G10021)
Processor: Intel Core i7

**Comment by jennievh** [comment]
Tried making my window longer and that didn't help.

Same behavior on https://tour.golang.org/flowcontrol/6

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.

**Comment by scotmatson** [comment]
Just did a fresh installation of Go and pulled down the tour package. The console still has no output.

macOS Catalina 10.15.3
Chrome 79.0.3945.130
go1.13.7 darwin/amd64
