### ISSUE TITLE
tour: [slice of length 1:4 returns no results]

### ISSUE THREAD

**Issue by jacobr2009** [golang/tour#895]
Context: https://tour.golang.org/moretypes/10

the following code prints 0 results

s := []int{2, 3, 5, 7, 11, 13}
s = s[1:4]
fmt.Println(s)

the following code all prints more than one result
s := []int{2, 3, 5, 7, 11, 13}
s = s[2:4] // s = s[1:5] // s = s[2:5]
fmt.Println(s)

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.
