### ISSUE TITLE
tour: no output with single space

### ISSUE THREAD

**Issue by APJaiswal** [golang/tour#898]
Context: https://tour.golang.org/welcome/1

output is empty with one space between "", and parameter 
for example
1.  hello.go there is one space between Hello, and 世界
2. in sandbox.go there is one space between "The time is", and time.Now()
If I removed the space or added few more space its working fine.
Tested on Chrome and Safari browser on MAC OSX.

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.
