### ISSUE TITLE
tour: there is no output from fmt.Println(add(42, 13))

### ISSUE THREAD

**Issue by brempusz** [golang/tour#901]
Context: https://tour.golang.org/basics/4

![image](https://user-images.githubusercontent.com/2048634/73390815-2be43780-42d7-11ea-9526-3b73df6e329c.png)

If I change it to `fmt.Println(0+add(42, 13))` it shows 55

windows 10, 1903 , 
chrome, Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by brempusz** [comment]
It works as expected on basic/5...

**Comment by brempusz** [comment]
After going back to basic/4 - it works...

**Comment by brempusz** [comment]
Ok, if I press "format" on page 4, then run - the result is not visible.
On 5 - its ok.

**Comment by ALTree** [comment]
There was a caching issues with the playground (which stores the tour programs); which is now fixed. Closing here.
