### ISSUE TITLE
Program throwing error

### ISSUE THREAD

**Issue by rehandxtr** [golang/tour#904]
Context: https://tour.golang.org/methods/9

the error is as follows
./prog.go:37:4: cannot use v (type Vertex) as type Abser in assignment:
	Vertex does not implement Abser (Abs method has pointer receiver)

**Comment by ALTree** [comment]
From the text on the left:

> Note: There is an error in the example code on line 22. Vertex (the value type) doesn't implement Abser because the Abs method is defined only on *Vertex (the pointer type). 

So this is expected. Closing here.
