### ISSUE TITLE
tour: Code in "Exercise: Loops and Functions" is uncompleted

### ISSUE THREAD

**Issue by shuhari** [golang/tour#905]
Context: https://tour.golang.org/flowcontrol/8

When I follow the tour into "Exercise: Loops and Functions", the body of function Sqrt() have no content and the code just can't run. The github code in `content/flowcontrol/exercise-loops-and-functions.go` is also missing function body. Is it a bug?

**Comment by ALTree** [comment]
No, it's an exercise. The text says:

> Implement this in the func Sqrt provided.

Closing here.
