### ISSUE TITLE
tour: methods/25 fails

### ISSUE THREAD

**Issue by ivhome** [golang/tour#915]
Context: https://tour.golang.org/methods/25

Run example and get error:
go: finding golang.org/x/tour latest
go: downloading golang.org/x/tour v0.0.0-20200201212631-8f38c9a8d074
go: extracting golang.org/x/tour v0.0.0-20200201212631-8f38c9a8d074
./prog.go:9:15: cannot use m (type Image) as type image.Image in argument to pic.ShowImage:
	Image does not implement image.Image (missing At method)

**Comment by ALTree** [comment]
Hi,

that page is an exercise. The title is "Exercise: Images" and it says:

> Define your own Image type, implement the necessary methods, and call pic.ShowImage. 

It won't compile until you solve the exercise correctly.

Closing here.
