### ISSUE TITLE
tour: Welcome page makes it look like Go properly supports Unicode when it doesn't

### ISSUE THREAD

**Issue by trejkaz** [golang/tour#92]
Context: https://tour.golang.org/welcome/1

This tour page had some Unicode text on it, including some in the code sample which I took as a challenge to find something that wasn't implemented correctly. So I tried this:

    fmt.Println("café" == "café")

Which prints:

    false

Whoops.

**Comment by quentinmit** [comment]
Are those actually the same string, or is one of them using a combining character? Equality is difficult for Unicode strings. == checks if the strings contain the exact same runes. If you want to check if they look the same, you need to use a normalization form (and Unicode has more than one to choose from). Go supports normalization, see https://godoc.org/golang.org/x/text/unicode/norm

**Comment by trejkaz** [comment]
Yeah, there are certainly ways to transform it, but modern languages like Swift and Elixir don't require me to - their string comparisons work correctly without additional hoop-jumping.

In my opinion, if `==` isn't going to work correctly, it shouldn't be added at all, which would also remove the problem. Of course, it's too late now.

**Comment by quentinmit** [comment]
`==` works correctly according to the spec.

There are different normalization forms, with subtle differences in equality. You need to pick the right one for your application. Go cannot choose that for you. (For example, should all forms of whitespace compare equal since they look the same?)

**Comment by trejkaz** [comment]
If all forms of whitespace did look the same, I would say yes, but some of them don't look the same, and some whitespace isn't even entirely white. ;)
