### ISSUE TITLE
Site is Completely Unreadable from Text Browser (without JavaScript)

### ISSUE THREAD

**Issue by rwxrob** [golang/tour#923]
Seriously, who made that design decision? Welcome to the shameful-shitty-sites list. How you became linked from the main page is beyond my comprehension. Zero design or web sense with zero accessibility. This is not an *app* it's a documentation site.

![stupid-design-decision](https://user-images.githubusercontent.com/3749067/76684472-aeecf300-65e2-11ea-94b0-2493de256f90.png)

**Comment by ALTree** [comment]
> This is not an app it's a documentation site.

Not really. It's an interactive tutorial. And the interactivity is implemented using javascript. If you prefer a less interactive experience, I suggest buying a book.
