### ISSUE TITLE
tour: I think reference to slice really should say array

### ISSUE THREAD

**Issue by mroseman95** [golang/tour#925]
Context: https://tour.golang.org/moretypes/10

For the description on this page, it says...

> Slice defaults
> When slicing, you may omit the high or low bounds to use their defaults instead.
> 
> The default is zero for the low bound and the length of the slice for the high bound.
> 
> For the array
> 
> ```
> var a [10]int
> ```
> 
> these slice expressions are equivalent:
> 
> ```
> a[0:10]
> a[:10]
> a[0:]
> a[:]
> ```

But I think the default upper bound for a slice is the length of the array not the slice.

> Slice defaults
> When slicing, you may omit the high or low bounds to use their defaults instead.
> 
> The default is zero for the low bound and the length of the **array** for the high bound.
> 
> For the array
> 
> ```
> var a [10]int
> ```
> 
> these slice expressions are equivalent:
> 
> ```
> a[0:10]
> a[:10]
> a[0:]
> a[:]
> ```

**Comment by ALTree** [comment]
It's correct. From [the spec](https://golang.org/ref/spec#Slice_expressions):

> For convenience, any of the indices may be omitted. A missing low index defaults to zero; a missing high index defaults to the length of the sliced operand: 

The current wording is confusing, but your new one is wrong. A slice has a backing array, but if I create a slice and then use it omitting the high index, it defaults to the length of *the slice* operand, not the backing array.

The fact that this could be clarified is #182, but your proposed patch is not correct.
