### ISSUE TITLE
tour: slice

### ISSUE THREAD

**Issue by buzzersdad** [golang/tour#928]
Context: https://tour.golang.org/moretypes/23

You don't indicate how one can remove just the nth element in a slice. You show how to drop off the first n elements.  If the elements were, say, 1,2,3,4,5,6, I'd like to be able to drop, say, element 3 (=4) so the slice becomes 1,2,3,5,6,

**Comment by ALTree** [comment]
See https://github.com/golang/go/wiki/SliceTricks#delete
