### ISSUE TITLE
tour: moretypes/18

### ISSUE THREAD

**Issue by markuszeller** [golang/tour#933]
Context: https://tour.golang.org/moretypes/18

Ends up with an **error**.

```
go: finding golang.org/x/tour latest
go: downloading golang.org/x/tour v0.0.0-20200201212631-8f38c9a8d074
go: extracting golang.org/x/tour v0.0.0-20200201212631-8f38c9a8d074
./prog.go:6:1: missing return at end of function
```

**Comment by ALTree** [comment]
See the text on the right:

> **Exercise: Slices**
>
> Implement Pic. [...]

So yes, it will not compile if you don't complete the exercise. As the error says, the `Pic` function is missing its return statement.

**Comment by markuszeller** [comment]
The solution should be inside the code commented or as an summary on the left side. Hitting **run** as in all the slides complete successful. So IMHO the flow should be all the same.

**Comment by ALTree** [comment]
Putting the solution in a comment or in the text would not make `run` work. 

> Hitting run as in all the slides complete successful.

Except in the several ones that are exercised, when `run` is to be used to test your solution.

I don't think this is particularly confusing. I believe you're supposed to read the text on the left before blindly pushing the run button on every page. In this case you just need to read literally the first 4 words, 

> **Exercise: Slices**
>
> Implement Pic. [...]

this clearly explains 1) that this is an exercise 2) that you have to implement the method.
