### ISSUE TITLE
Web based GoLang tutorial > multiple results code does not print "world hello"

### ISSUE THREAD

**Issue by bsheps** [golang/tour#948]
Context: https://tour.golang.org/basics/6

```go
package main

import "fmt"

func swap(x, y string) (string, string) {
	return y, x
}

func main() {
	a, b := swap("hello", "world")
	fmt.Println(a, b)
}
```
Result: A blank line.

Expectation: It should print "world hello" when I run the program.

Work around: I added a semi colon to the return statement in swap. (But I thought semicolons were optional?)

**Comment by bsheps** [comment]
Browsers tested: Safari 13.1 and Firefox 75.0

**Comment by ALTree** [comment]
It was a caching issue (adding a semicolon changed the program, by-passed the cache, that's why it worked). Now fixed, so closing.
