### ISSUE TITLE
tour: [REPLACE WITH SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by tartrsn** [golang/tour#949]
Context: https://tour.golang.org/basics/6

We've got

```
	a, b := swap("hello", "world")
	fmt.Println(a, b)
```

In main, however it doesn't print anything

**Comment by tangsaidi** [comment]
I was not able to reproduce the bug

It prints out `world hello` for me. Could you provide more context

**Comment by ALTree** [comment]
There were some server-side issue 2 weeks ago that could cause no output, but they should be fixed now. Closing here.
