### ISSUE TITLE
tour: add link to "the picture generator you wrote earlier"

### ISSUE THREAD

**Issue by bdlow** [golang/tour#95]
Context: https://tour.golang.org/methods/25

The exercise says 

> Remember the picture generator you wrote earlier? Let's write another one, ...

No, I don't remember the picture generator (I presume this one?: https://tour.golang.org/moretypes/18 ?). It'd be good to include a link.

**Comment by ALTree** [comment]
Considering how much earlier the picture general is, it would be good to link it.
