### ISSUE TITLE
tour: Worst ever welcome

### ISSUE THREAD

**Issue by frikiluser** [golang/tour#952]
Context: https://tour.golang.org/welcome/1

Post response to click with default code:
`{"Errors":"","Events":null,"Status":0,"IsTest":false,"TestsFailed":0}`

Expected response:
`{"Errors":"","Events":[{"Message":"Hello, 世界\n","Kind":"stdout","Delay":0}],"Status":0,"IsTest":false,"TestsFailed":0}`

Easy reproducible with next curl command:
`curl -v 'https://tour.golang.org/compile' --data 'version=2&body=package+main%0A%0Aimport+%22fmt%22%0A%0Afunc+main()+%7B%0A%09fmt.Println(%22Hello%2C+%E4%B8%96%E7%95%8C%22)%0A%7D%0A'`

Workaround: Changing the Println() message fixes the problem

**Comment by frikiluser** [comment]
FTR: Now it's working fine

**Comment by ALTree** [comment]
Yeah there was an issue with the cached responses I guess (that's why changing the program in any way fixed it).

Closing here, since it appears to be fixed.
