### ISSUE TITLE
 How to use the Go language to display the current time

### ISSUE THREAD

**Issue by wangzhaoyang2025** [golang/tour#96]
This Go language code runs out of time is 2009-11-10
How to display the current time?
`package main

import (
    "fmt"
    "time"
)

func main() {
    fmt.Println("When's Wednesday?")
    today := time.Now().Weekday()
    switch time.Wednesday {
    case today + 0:
        fmt.Println("Today.")
    case today + 1:
        fmt.Println("Tomorrow.")
    case today + 2:
        fmt.Println("In two days.")
    default:
        fmt.Println("Too far away.")
    }
}
`

**Comment by ALTree** [comment]
Closing as a dup of #91.
