### ISSUE TITLE
tour: Picture exercises: wrong imports

### ISSUE THREAD

**Issue by yartem** [golang/tour#966]
Context: https://tour.golang.org/methods/25

Hey, I noticed that the imports are wrong in exercises [Exercise: Slices](https://tour.golang.org/moretypes/18) and [Exercise: Images](https://tour.golang.org/methods/25)

Actual:
```
import "golang.org/x/tour/pic"
```

Working: (taken from [this gist](https://gist.github.com/tetsuok/2280162#file-answer_pic-go-L3))
```
import "code.google.com/p/go-tour/pic"
```

**Comment by ALTree** [comment]
Why do you say the import is wrong? It looks okay to me.

**Comment by ALTree** [comment]
Closing here as I don't think there's a bug here.
