### ISSUE TITLE
tour: numeric constants: wrong comment on operator

### ISSUE THREAD

**Issue by mat90x** [golang/tour#973]
Context: https://tour.golang.org/basics/16

Second comment is wrong: binary left shift multiplies by two, so the result certainly won't be one followed by hunred zeroes.
```go
const (
	// Create a huge number by shifting a 1 bit left 100 places.
	// In other words, the binary number that is 1 followed by 100 zeroes.
	Big = 1 << 100
	// Shift it right again 99 places, so we end up with 1<<1, or 2.
	Small = Big >> 99
)
```

**Comment by ALTree** [comment]
Nope, the comment is correct. It says "**the binary number** that is 1000..000". And it's right. `Big` is a number with binary representation `100....000`. 

Closing here.
