### ISSUE TITLE
tour: Any one can tell me why Exercise: Readers of Go Tour cannot work with []byte?

### ISSUE THREAD

**Issue by davidxyz981** [golang/tour#983]
Context: https://tour.golang.org/methods/22

Any one can tell me why Exercise: Readers of Go Tour canot work?

byte[0] =  ,can work but []byte cannot work,

package main

import 
(
"golang.org/x/tour/reader"

)
type MyReader struct{

 //Reader rd;

}
func (MyReader) Read(r []byte) (int, error) {
    	r =[]byte{'A','A'} // this cannot work
        //r[0]='A'  //<----this can work!
	//r[1]='A'
	return 2,nil
}

// TODO: Add a Read([]byte) (int, error) method to MyReader.
func main() {
	reader.Validate(MyReader{})
}

**Comment by ALTree** [comment]
`r =[]byte{'A','A'}` this line replaces `r` with a local variable, so you're changing the original one and the caller cannot see the change.
