### ISSUE TITLE
tour: incorrect operator ( = ) used instead of ( := )

### ISSUE THREAD

**Issue by vaeroon** [golang/tour#986]
Context: https://tour.golang.org/moretypes/1

The description on the left should be corrected to use `p := &i`

It currently shows `p = &i`

**Comment by ALTree** [comment]
Someone using the same machine changed it (and changes are saved, locally). You can press the Reset button to restore the original program.

Closing here.

**Comment by vaeroon** [comment]
Please see the attached screenshot. I am referring to the explanation on the left, it needs to be corrected. It is out of sync with the code (shown by default) no the right. Am I missing something?

![screenshot](https://user-images.githubusercontent.com/925007/84139826-35905f80-aa6e-11ea-92a3-3f6086d95dc1.jpg)

**Comment by ALTree** [comment]
Oh, you mean that one. No but the description and the code here are different things. In the description it does `var p *int` so `p` is already declared and using `:=` would be wrong. It's either

```
var p *int
p = &i
``

or  `p := &i` (if `p` was not declared previously). Code and description are using both variants.

**Comment by vaeroon** [comment]
Ok, as long as doing this is intentional. I mean, this is an introduction to Go; probably best if we use one variant at both places.
